### PR TITLE
Fix the building highlighting loss after out of map boundary and rerouting

### LINKED ISSUE #4033: [Bug]: Highlight building at unexpected coordinate
### Mapbox Navigation SDK version

v2.7.0-beta.2

### Steps to reproduce

1. on `main` branch,  build `Example` App
2. long press a building to choose it as a waypoint to highlight it.
3. choose another waypoint

### Expected behavior

The first waypoint building should keep the highlighted state.

### Actual behavior

The first waypoint building is not highlighted. But an unexpected coordinate is highlighted.
highlight

### Is this a one-time issue or a repeatable issue?

repeatable

### PR DESCRIPTION
**Pull request by ShanMa1991**
### Description
This PR is to fix the building highlighting issues.

### Implementation
- [x] When the building coordinate is out of the map boundary, the map query won't work for this case. Added `NavigationMapView.highlightBuildings` to remember the past query result to provide the valid identifier of the building coordinate.
- [x] According to [test comment](https://github.com/mapbox/mapbox-maps-ios/issues/1488#issuecomment-1197372757),  when not extrude all buildings, don't apply the `extrusion` check for the building identifier. But a building may have multiple identifiers, the identifier from map query result may has `extrusion: false`
- [x] fixed #4033 , when the coordinate is out of map boundary and screen coordinate as `CGPoint(x: -1.0, y: -1.0)`, don't do the map query, because it will give an unmatched result. 
- [x] fixed an issue where the destination building is not highlighted after rerouting

### Screenshots or Gifs
rerouting

### CODE REVIEW

File: Sources/MapboxNavigation/BuildingHighlighting.swift [hunk 1]
```diff
@@ -49,8 +49,9 @@ extension BuildingHighlighting {
         
         // In case if not all buildings were found and user is within allowed destination
         // threshold - attempt to highlight buildings based on destination coordinate.
+        let destination = progress.currentLeg.destination
         if !buildingWasFound, passedApproachingDestinationThreshold,
-           let currentLegWaypoint = progress.currentLeg.destination?.targetCoordinate {
+           let currentLegWaypoint = destination?.targetCoordinate ?? destination?.coordinate {
```
Comment (ShanMa1991) [inline Sources/MapboxNavigation/BuildingHighlighting.swift:54]: The `targetCoordinate` may be lost after the rerouting event

File: Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift [hunk 2]
```diff
@@ -23,17 +23,20 @@ extension NavigationMapView {
...
         let identifiers = mapView.mapboxMap.style.allLayerIdentifiers
             .compactMap({ $0.id })
             .filter({ $0.contains("building") })
         let layerPosition = identifiers.last.map { LayerPosition.above($0) }
         
-        coordinates.forEach {
-            group.enter()
+        for coordinate in coordinates {
+            let screenCoordinate = mapView.mapboxMap.point(for: coordinate)
+            if screenCoordinate == CGPoint(x: -1.0, y: -1.0) {
```
Comment (ShanMa1991) [inline Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift:35]: If the coordinate is out of map boundary, don't do the map query, because it will return a false result.

File: Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift [hunk 3]
```diff
@@ -90,18 +95,15 @@ extension NavigationMapView {
...
-                highlightedBuildingsLayer.filter = extrudeExpression
+                highlightedBuildingsLayer.filter = Exp(.eq) {
+                    Exp(.get) {
+                        "extrude"
+                    }
+                    "true"
+                }
             } else {
                 highlightedBuildingsLayer.filter = Exp(.all) {
-                    extrudeExpression
```
Comment (ShanMa1991) [inline Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift:104]: Some buildings have multiple identifiers, the query result may has `extrusion: false`

File: Sources/MapboxNavigation/NavigationMapView.swift [hunk 4]
```diff
@@ -886,6 +886,11 @@ open class NavigationMapView: UIView {
      */
     var mostRecentUserCourseViewLocation: CLLocation?
     
+    /**
+     The coordinates and corresponding identifiers for highlight buildings.
+     */
+    var highlightBuildings = [CLLocationCoordinate2D: Int64]()
```
Comment (ShanMa1991) [inline Sources/MapboxNavigation/NavigationMapView.swift:892]: To store the coordinate and identifier pairs when the building is out of map boundary.

File: Sources/MapboxNavigation/BuildingHighlighting.swift (hunk 1 above)
Comment (MaximAlien) [reply Sources/MapboxNavigation/BuildingHighlighting.swift:54]: I don't think that usage of final destination coordinate is a reliable source. In most of the cases it'll contain coordinate that is snapped to the road network, and building identifier querying will fail. Would it be possible to copy `targetCoordinate` right before rerouting event? If not, we should discuss this with Navigation Native folks on how it can be improved.

Comment (ShanMa1991) [reply Sources/MapboxNavigation/BuildingHighlighting.swift:54]: I see. I'll ask Navigation Native about that and remove this one. The query failed with the destination coordinate.

File: Sources/MapboxNavigation/NavigationMapView.swift (hunk 4 above)
Comment (1ec5) [reply Sources/MapboxNavigation/NavigationMapView.swift:902]: Let’s give this a more descriptive name, such as `highlightedBuildingIdentifiersByCoordinate` to avoid sounding like a method like `highlightBuildings(at:in3D:extrudeAll:completion:)`.

A given building be found at multiple coordinates depending on the coordinates that happen to be passed into `highlightBuildings(at:in3D:extrudeAll:completion:)`. Is this potential duplication a problem?

File: Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift [hunk 5]
```diff
@@ -23,17 +23,20 @@ extension NavigationMapView {
                                    in3D extrudesBuildings: Bool = true,
                                    extrudeAll: Bool = false,
                                    completion: ((_ foundAllBuildings: Bool) -> Void)? = nil) {
-        var foundBuildingIds = Set<Int64>()
+        highlightBuildings = highlightBuildings.filter{ coordinates.contains($0.key) }
```
Comment (1ec5) [inline Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift:26]: `highlightBuildings` effectively caches building identifiers between calls to this method, but this method doesn’t consult the cache before querying and adding results to it. Do we really need the cache?

File: Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift (hunk 2 above)
Comment (ShanMa1991) [reply Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift:35]: Because the `CGPoint(x: -1.0, y: -1.0)` is the value the `MapView.mapboxMap.point(for:)` will return if the coordinate is out of map bounds.

File: Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift (hunk 5 above)
Comment (MaximAlien) [reply Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift:26]: I think that we should not use intermediate cache in `NavigationMapView` specifically. Not sure if it's the right word to describe it, but they should be *idempotent*. 

IMHO all logic related to building highlighting during navigation specifically is meant to be implemented by users of this API (in this case it's `NavigationViewController` or `CarPlayNavigationViewController`). Both of them conform to `BuildingHighlighting` with default implementation in `attemptToHighlightBuildings(_:,navigationMapView:completion:)`.

File: Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift (hunk 2 above)
Comment (MaximAlien) [reply Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift:35]: I propose just to verify whether coordinate is out of map view bounds, if so - simply do not perform querying, and do not add anything to `foundBuildingIds`. At the end users will be notified that not all buildings at specific coordinates were highlighted and member variable in `NavigationMapView` will not be needed.

File: Sources/MapboxNavigation/NavigationMapView.swift (hunk 4 above)
Comment (ShanMa1991) [reply Sources/MapboxNavigation/NavigationMapView.swift:902]: If a building could be found at multiple coordinates. If one of the coordinate is stored, and we try to highlight it with another coordinate. The previous one will be removed, and the new one will be queried and stored. And when we unhighlight buildings, all the coordinates stored will be removed. The property has key for coordinate, so there shouldn't be the duplication problem.

File: Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift (hunk 5 above)
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift:26]: I see. Right now the `extrudeAll` feature is till kept. Because the identifiers will only be used to filter the building when `extrudeAll` is `false`.

Comment (ShanMa1991) [reply Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift:26]: I think we need this cache. For example, right now on the main branch. If we add a waypoint and highlight it, pan the mapView and move the waypoint out of bounds, and then choose another waypoint. Because the previous waypoint coordinate is out of mapView bound, the query will fail. So we could only highlight the last waypoint in the mapView bounds. It's not an expected behavior.
With the cache, when we choose multiple waypoint, if the previous one has been highlighted before, its identifier will be kept and highlighted even it's out of the map bounds.

File: Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift (hunk 2 above)
Comment (ShanMa1991) [reply Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift:35]: Because the query is done inside the `mapView`, we only need to check whether the coordinate is outside the `mapView` bound. And that's the value the `mapView` will return if the coordinate is out of `mapView` bound.

File: CHANGELOG.md [hunk 6]
```diff
@@ -13,6 +13,7 @@
 * Each alternative route shown during turn-by-turn navigation is now annotated with the amount of time it saves or adds to the trip. To hide these annotations, set the `NavigationMapView.showsRelativeDurationOnContinuousAlternativeRoutes` property to `false`. ([#3956](https://github.com/mapbox/mapbox-navigation-ios/pull/3956))
 * Fixed the issue where the route line endpoint is ahead of user location indicator on short straight-line route step when `NavigationViewController.routeLineTracksTraversal` enabled in active navigation. ([#3992](https://github.com/mapbox/mapbox-navigation-ios/pull/3992))
 * Added the ability to provide duration and completion handler while visualizing routes using `NavigationMapView.showcase(_:animated:duration:completion:)`. ([#4022](https://github.com/mapbox/mapbox-navigation-ios/pull/4022))
+* Fixed the issue of unexpected building highlighted when the coordinate is out of map boundary. ([#4034](https://github.com/mapbox/mapbox-navigation-ios/pull/4034))
```
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply CHANGELOG.md:16]: Thanks for the suggestion, I'll update the changeLog.

File: Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift (hunk 5 above)
Comment (1ec5) [reply Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift]: I think I understand now how `highlightedBuildingIdentifiersByCoordinate` prevents the problem you’re describing, but it’s kind of confusing. The method never checks whether a coordinate is already in `highlightedBuildingIdentifiersByCoordinate` before it queries rendered features at the coordinate. Instead, it relies on the fact that the query will come back with no results, allowing a fallback to the existing value in `highlightedBuildingIdentifiersByCoordinate`.

So `highlightedBuildingIdentifiersByCoordinate` isn’t actually a cache in the sense of avoiding redundant work. Rather, it just memoizes previous successful results. Memoization normally doesn’t require a dictionary, but it does in this case because we need to keep track of both coordinates and building IDs. The initial filter mostly addresses the question of clearing the dictionary. Because of the filter, every call to this method effectively shrinks `highlightedBuildingIdentifiersByCoordinate` to just the results for the passed-in coordinates. (It’s possible that the method could be called with slightly different coordinates for the same building, which would effectively clear the dictionary.)

**Review by 1ec5 — APPROVED** [review]
