### PR TITLE
Use Mapbox designed shield from status for road name labeling

### LINKED ISSUE #3716: Expose the Shield and legacy shield URL from NavigationStatus for the road label.
Right now during passive and active navigation, we have exposed the current road name from `NavigationStatus` to `Notification` for the road labeling . To adopt the new Mapbox designed shield for road labeling in `WayNameView`, we also need to expose the Shield and legacy shield URL as well.

### LINKED ISSUE #3730: [Bug]: When drive from named road to unnamed road, the resume button would cause the `wayNameView` blinks showing previous road name
### Mapbox Navigation SDK version

2.2.0

### Steps to reproduce

1. Choose a route that has named road and unnamed road, for example, from highway to a small road.
2. Start the simulated navigation.
3. When user drives from the named road to unnamed road, see the `wayNameView` hidden.
4. change the camera state to `.idle` by dragging the view. And then click the `resume button`.

### Expected behavior

The `wayNameView` would be hidden on the unnamed road no matter the camera state.

### Actual behavior

The `wayNameView` blinks with the previous road name.
roadNameBlinks

### Cause
This issue is caused by we label the current road every 1 second. When the current road name is empty or not valid, it only `hide` it without `clear` its label text. So when the resume button clicked or camera state change, it would check the label text of `wayNameView`, because it's using the `previous` road name, it's not empty so the road label would be shown.  

When the next `routeProgress` comes in and the current label be updated, it would be hidden again because it's on an unnamed road. The showing and hiding would lead to the blinking effect on the unnamed road.

### Is this a one-time issue or a repeatable issue?

repeatable

### PR DESCRIPTION
**Pull request by ShanMa1991**
### Description
This pr is to fix #3716 and also to use the road shield information from `NavigationStatus` through `Notification` to label the current road, instead of using map feature query.
This pr also fix #3730 by clearing the road name label text on unnamed road, and updating the `WayNameView` hidden status with the road name check and the resume button check.

### Implementation
- [x] Added `imageRepresentationKey` to both `PassiveLocationManager.passiveLocationManagerDidUpdate` and `RouteController.currentRoadNameDidChange` notifications from `NavigationStatus`. So during passive and active navigation, developers could receive the update of the road shield as `MapboxDirections.VisualInstruction.Component.ImageRepresentation` object.
- [x] Added the `UIImage.withFontSize(font:size:)` to render the `legacy` shield icon in `WayNameView`.
- [x] Added the `WayNameLabel.setupWithShield(roadName:shieldIcon:)` to create the road label with the `roadName` and Mapbox designed shield icon.  Added `WayNameView.setupWithLegacy(roadName:shieldIcon:)` to create the road label with the `roadName` and legacy shield icon. 
- [x] Added `SpriteRepository` to `WayNameLabel`. And it would be updated when the map style change through `WayNameView.updateStyle(styleURI:)` and when the road shield info changes the  through `WayNameView.updateRoad(roadName:imageRepresentation:)`.
- [x] In `OrnamentsController`, `CarPlayNavigationViewController` and `CarPlayMapViewController`, add the notification observer to listen to the road name and the road shield, and to update the `WayNameView`.
- [x] Fixed #3730 by remove the control of the camera state to the road name label. Hide the label when the road is unnamed.

#### Label set up
- [x] When no `valid(non empty string)` road name provided,`nil out` the road name label text and  `hide` the WayNameView.
- [x] When the road is not `us-state` road, use the Mapbox designed shield for labeling first. If there's no valid Mapbox designed shield, use the legacy shield from the `imageBaseURL` of the `ImageRepresentation`. If no valid legacy shield,  present the road name only.

### Screenshots or Gifs
It supports the road labeling using `SpriteRepository` for `mobile` during `active` navigation through `WayNameView`.
mobile

It supports the road labeling using `SpriteRepository` for `CarPlay` during `active` navigation through `WayNameView` in `CarPlayNavigationViewController`.
carPlayActive

It supports the road labeling using `SpriteRepository` for `CarPlay` during `passive` navigation through `WayNameView` in `CarPlayMapViewController`.
carPlayPassive

### CODE REVIEW

**Comment by 1ec5** [comment]
[CocoaPods builds are failing](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/7189/workflows/25967237-6886-41a1-8289-057873b391e0/jobs/59918) with the following linker error:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MBNNShield", referenced from:
      objc-class-ref in CarPlayMapViewController.o
      objc-class-ref in CarPlayNavigationViewController.o
      objc-class-ref in OrnamentsController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

However, everything is fine with SPM-based builds. The CocoaPods builds are pulling in the same MapboxNavigationNative v87.0.2 as the SPM builds.

File: Sources/MapboxCoreNavigation/CoreConstants.swift [hunk 1]
```diff
@@ -292,6 +292,16 @@ extension RouteController {
          */
         public static let roadNameKey: NotificationUserInfoKey = .init(rawValue: "roadName")
         
+        /**
+         A key in the user info dictionary of a `Notification.Name.currentRoadNameDidChange` notification. The corresponding value is a `MapboxNavigationNative.Shield` object representing the road shield the user is currently traveling on.
```
Comment (1ec5) [inline Sources/MapboxCoreNavigation/CoreConstants.swift:296]: The notification user info dictionary is also used by application code. We shouldn’t store any C++ wrapper objects from MapboxNavigationNative directly in this dictionary, because these objects have different semantics than in pure Swift code. Instead, convert the shield object into a `VisualInstruction.Component.ShieldRepresentation` instance.

Comment (1ec5) [reply Sources/MapboxCoreNavigation/CoreConstants.swift:296]: This _might_ be the reason for the CocoaPods linker errors. MapboxNavigation.podspec doesn’t directly depend on MapboxNavigationNative, because the expectation is that anything vended by MapboxCoreNavigation can be used in pure Swift code without a separate MapboxNavigationNative dependency.

Comment (ShanMa1991) [reply Sources/MapboxCoreNavigation/CoreConstants.swift:296]: Thanks for the suggestion, I'll update this part and to solve this issue.

Comment (ShanMa1991) [reply Sources/MapboxCoreNavigation/CoreConstants.swift]: Yes, the error is solved with the `VisualInstruction.Component.ShieldRepresentation`  instead of the `NavigationStatus.Shield`.

File: Sources/MapboxNavigation/WayNameView.swift [hunk 2]
```diff
@@ -2,12 +2,161 @@ import Foundation
...
+        case "red":
+            return .red
+        case "white":
+            return .white
+        case "yellow":
+            return .yellow
+        case "orange":
+            return .orange
+        default:
+            return .black
```
Comment (1ec5) [inline Sources/MapboxNavigation/WayNameView.swift:142]: The text color should match the color scheme of the spritesheet and stylesheet. For example, green is approximately `#00ff00` (depending on color correction and color profile), which is much too green for any visually pleasing map style. For now, we may need to hardcode values in the UI style based on what’s being used in the map style.

File: Tests/MapboxNavigationTests/WayNameViewTests.swift [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+        ImageLoadingURLProtocolSpy.registerData(Fixture.JSONFromFileNamed(name: "sprite-info"), forURL: metadataRequestURL)
+        ImageLoadingURLProtocolSpy.registerData(ShieldImage.shield.image.pngData()!, forURL:  URL(string: ShieldImage.i280.baseURL.absoluteString + "@\(scale)x.png")!)
+    }
+    
+    func testUpdateStyle() {
+        let baseURL = wayNameView.label.spriteRepository.baseURL
+        let styleID = "/mapbox/navigation-night-v1"
+        loadingURL(baseURL: baseURL, styleID: styleID)
+        
+        let shield = VisualInstruction.Component.ShieldRepresentation(baseURL: baseURL, name: "us-interstate", textColor: "white", text: "280")
```
Comment (1ec5) [inline Tests/MapboxNavigationTests/WayNameViewTests.swift:52]: The `za-national` (South African national route) shield type has yellow text, which would make for a more interesting test of our color conversion capabilities.

File: Tests/MapboxNavigationTests/WayNameViewTests.swift [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+        let representation = VisualInstruction.Component.ImageRepresentation(imageBaseURL: ShieldImage.i280.baseURL, shield: shield)
+        
+        wayNameView.updateRoad(roadName: roadName, imageRepresentation: representation)
+        expectation(description: "Road label updated.") {
+            self.wayNameView.label.text != nil
+        }
+        waitForExpectations(timeout: 3, handler: nil)
+        
+        XCTAssertEqual(wayNameView.label.representation, representation, "Failed to update the imageRepresentation of WayNameView label.")
+        XCTAssertTrue(wayNameView.label.attributedText!.containsAttachments(in: NSRange(location: 0, length: 1)), "Failed to update the shield images when update style.")
```
Comment (MaximAlien) [inline Tests/MapboxNavigationTests/WayNameViewTests.swift:87]: Better to omit force-unwrapping as it'll cause inconvenience on local runs.

**Comment by MaximAlien** [comment]
Speaking of:

> When the mobile not in .following camera state, hide the WayNameView.

Should we still do this? I think main reason for this was inability to query map view features on low zoom levels. With current implementation this shouldn't be a problem. In current state there is also inconsistency as on CarPlay still shows `WayNameView` even in `.overview` mode.

File: Sources/MapboxNavigation/NavigationMapView+RoadNameLabeling.swift [hunk 5]
```diff
@@ -1,171 +0,0 @@
-import MapboxMaps
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/NavigationMapView+RoadNameLabeling.swift:1]: Since this file was removed please also update `MapboxNavigation.xcodeproj`.

File: Sources/MapboxNavigation/WayNameView.swift [hunk 6]
```diff
@@ -2,12 +2,161 @@ import Foundation
...
 import MapboxMaps
+import MapboxDirections
 
 /**
  A label that is used to show a road name and a shield icon.
  */
 @objc(MBWayNameLabel)
-open class WayNameLabel: StylableLabel {}
+open class WayNameLabel: StylableLabel {
+    var spriteRepository = SpriteRepository.shared
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/WayNameView.swift:12]: I did not have a chance to review `SpriteRepository` implementation it time, but I'd consider adding `Result` usage (which contains error and expected value) to completion handlers there, it'll give us the ability to track possible issues that might arise.

Comment (MaximAlien) [reply Sources/MapboxNavigation/WayNameView.swift:12]: I've also walked though APIs in `SpriteRepository` and think that some methods/properties should be simplified. For example: why do we need initializer with all default parameters? If it's not used anywhere and main point of access in `shared` property we can remove it. Some properties are public, I'd consider making them internal, as they're not meant to be used by anybody else for now.

File: Sources/MapboxNavigation/CarPlayMapViewController.swift [hunk 7]
```diff
@@ -366,7 +369,10 @@ extension CarPlayMapViewController: StyleManagerDelegate {
     public func styleManager(_ styleManager: StyleManager, didApply style: Style) {
         let mapboxMapStyle = navigationMapView.mapView.mapboxMap.style
         if mapboxMapStyle.uri?.rawValue != style.mapStyleURL.absoluteString {
-            mapboxMapStyle.uri = StyleURI(url: style.previewMapStyleURL)
+            let styleURI = StyleURI(url: style.mapStyleURL)
+            mapboxMapStyle.uri = styleURI
+            // Update the sprite repository of wayNameView when map style changes.
+            wayNameView?.updateStyle(styleURI: styleURI)
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/CarPlayMapViewController.swift:375]: What about accessing label directly and calling similar method on it?

File: Sources/MapboxNavigation/NavigationViewController.swift [hunk 8]
```diff
@@ -781,11 +781,7 @@ extension NavigationViewController: NavigationServiceDelegate {
         let preventRerouting = navigationService.delegate?.navigationService(navigationService, shouldPreventReroutesWhenArrivingAt: destination) ?? RouteController.DefaultBehavior.shouldPreventReroutesWhenArrivingAtWaypoint
         let userArrivedAtWaypoint = progress.currentLegProgress.userHasArrivedAtWaypoint && (progress.currentLegProgress.distanceRemaining <= 0)
 
-        if snapsUserLocationAnnotationToRoute && (!userArrivedAtWaypoint || preventRerouting) {
-            ornamentsController?.labelCurrentRoad(at: rawLocation, suggestedName: roadName(at: rawLocation), for: location)
-        } else  {
-            ornamentsController?.labelCurrentRoad(at: rawLocation, suggestedName: roadName(at: rawLocation))
-        }
+        ornamentsController?.labelCurrentRoadName(suggestedName: roadName(at: rawLocation))
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/NavigationViewController.swift:784]: I wonder if we should keep using `rawLocation` in this case. Should we also check whether snapped location is also available and make use of it in first place?

File: Sources/MapboxNavigation/WayNameView.swift [hunk 9]
```diff
@@ -2,12 +2,161 @@ import Foundation
...
+    /**
+     Fills contents of the `WayNameLabel` with the road name and shield icon from the spriteRepository.
+     
+     - parameter roadName: The road name `String` that should be presented on the view.
+     - parameter shieldIcon: The  `UIImage` that represents the current road shield.
+     - returns: `true` if operation was successful, `false` otherwise.
+     */
+    @discardableResult
+    private func setupWithShield(roadName: String, shieldIcon: UIImage) -> Bool {
+        guard let shield = representation?.shield else { return false }
```
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/WayNameView.swift:103]: The class store a copy of it because when the shield `ImageRepresentation` changes, we need to update the cache to re-download the sprite sheet, sprite info and the legacy shield icon. We only update the cache when the  `ImageRepresentation` change or when the map style changes.

File: Sources/MapboxNavigation/WayNameView.swift [hunk 10]
```diff
@@ -2,12 +2,161 @@ import Foundation
...
+        setUpWith(roadName: roadName)
+    }
+    
+    // Set up the `WayNameLabel` with the road name. Try to use the Mapbox designed shield first, if failed, fall back to use the legacy road shield icon.
+    // If there's no valid shield image, display the road name only.
+    private func setUpWith(roadName: String) {
+        var didSetUp = false
+        
+        if let shield = representation?.shield,
+           let shieldIcon = spriteRepository.getShield(displayRef: shield.text, name: shield.name) {
```
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/WayNameView.swift:47]: Thanks for the suggestion, I'll add a TODo mark when it's ready to use the shield for `us-state` first.

File: Sources/MapboxNavigation/NavigationViewController.swift (hunk 8 above)
Comment (ShanMa1991) [reply Sources/MapboxNavigation/NavigationViewController.swift]: Thanks for the suggestion, the snapped location would be checked first.

**Comment by ShanMa1991** [comment]
> Should we still do this? I think main reason for this was inability to query map view features on low zoom levels. With current implementation this shouldn't be a problem. In current state there is also inconsistency as on CarPlay still shows `WayNameView` even in `.overview` mode.

I think we could make it a tail work. Because both the `resume` button and the `wayNameView` are very likely to overlapping each other. We should modify the layout of them to avoid the overlapping and then make the `wayNameView` presenting without the concerns of the `resume` button or the `camera` state.

File: Sources/MapboxNavigation/WayNameView.swift (hunk 6 above)
Comment (ShanMa1991) [reply Sources/MapboxNavigation/WayNameView.swift:12]: Thanks for the suggestion about the `Result` usage. Yes it should be good if we could use the `result` that has image/data/error for the completion handlers. But the issue is that when we update the `SpriteRepository` with the `ImageRepresentation` or the road shield. We may need to request the sprite info data, the sprite image and the single legacy shield icon at the same time. The three are different in types. 

And the result of the sprite info data would be parsed into dictionary and stored in cache, the sprite image and  the legacy shield icon would also be stored in cache in the `completion` of the downloading request of `imageDownloader`. So the `CompletionHandler` of the sprite update call in fact receives all the process. Right now I haven't found a way to do it separately. Because the single shield icon need both the Sprite info and Sprite image to conduct the cutting process.

Comment (ShanMa1991) [reply Sources/MapboxNavigation/WayNameView.swift:12]: Yes, I'll remove the `shared` property and the initializer for the `SpriteRepository`, also change these public properties to internal because they're not used anywhere. For the default parameter, because the changes of the shield baseURL and map style don't happen at the same time, we need to stored the value when each one of them change.

File: Sources/MapboxNavigation/WayNameView.swift [hunk 11]
```diff
@@ -2,12 +2,137 @@ import Foundation
...
+        self.representation = representation
+        setUpWith(roadName: roadName)
+    }
+    
+    // Set up the `WayNameLabel` with the road name. Try to use the Mapbox designed shield first, if failed, fall back to use the legacy road shield icon.
+    // If there's no valid shield image, display the road name only.
+    private func setUpWith(roadName: String) {
+        // TODO: Use shield for us-state shield first
+        if let shield = representation?.shield,
+           shield.name != "us-state",
```
Comment (1ec5) [inline Sources/MapboxNavigation/WayNameView.swift:44]: If the legacy endpoint doesn’t have an image for a particular `us-state` shield, we should fall back to the new codepath – essentially the reverse of the fallback for other shield types.

File: Sources/MapboxNavigation/SpriteRepository.swift [hunk 12]
```diff
@@ -156,6 +140,27 @@ class SpriteRepository {
...
     }
     
+    func shieldColor(from shieldTextColor: String) -> UIColor {
+        switch shieldTextColor {
+        case "black":
+            return .black
+        case "blue":
+            return .blue
+        case "green":
+            return #colorLiteral(red: 0, green: 0.5, blue: 0, alpha: 1)
```
Comment (1ec5) [inline Sources/MapboxNavigation/SpriteRepository.swift:150]: All of these colors should be specified by the Style, not hard-coded here in the sprite repository. A different map style could have a completely different color scheme, which would lead to a spritesheet with a different color scheme too. We wouldn’t want to composite text onto the image that uses a mismatching color.

We can split out DayStyle/NightStyle modifications as tail work, since it might require investigating the specific colors used by the most popular map styles, but let’s make sure we have a plan for how to expose the color settings to Style and how to clear the cache when the UI style changes between day and night.

File: CHANGELOG.md [hunk 13]
```diff
@@ -51,6 +51,8 @@
...
 * Fixed an issue where release builds would crash on invalid navigator initialization. ([#3738](https://github.com/mapbox/mapbox-navigation-ios/pull/3738))
+* Added `routeShieldRepresentationKey` to the user info dictionary of `Notification.Name.passiveLocationManagerDidUpdate` posted by `PassiveLocationManager`, and the `Notification.Name.currentRoadNameDidChange` posted by `RouteController`. The corresponding value is a `MapboxDirections.VisualInstruction.Component.ImageRepresentation` object representing the road shield the user is currently traveling on. ([#3723](https://github.com/mapbox/mapbox-navigation-ios/pull/3723))
+* Removed `NavigationMapView.labelCurrentRoadFeature(at:router:wayNameView:roadNameFromStatus:)`. Instead, updating the road label through the `WayNameView.label.updateRoad(roadName:representation:)` and `WayNameView.label.updateStyle(styleURI:)`. ([#3723](https://github.com/mapbox/mapbox-navigation-ios/pull/3723))
```
Comment (1ec5) [inline CHANGELOG.md:55]: This is an internal method, so we don’t need to mention it in the changelog. However, we should mention that route shields in the instruction banner are now visually consistent with route shields on the map and in the current road name label.

**Review by 1ec5 — APPROVED** [review]
A couple more things to address before we can land this PR. Some of it can be tail work, but we just need to make sure the current architecture doesn’t preclude the tail work fix.

File: CHANGELOG.md (hunk 13 above)
Comment (ShanMa1991) [reply CHANGELOG.md:55]: Thanks for the suggestion. Because this PR doesn't include the instruction banner replacement. And the road shield in the road name label used to use map query, which already is consistent with the map. I think this changeLog entry should be left for the instruction banner update one.

File: Sources/MapboxNavigation/SpriteRepository.swift (hunk 12 above)
Comment (ShanMa1991) [reply Sources/MapboxNavigation/SpriteRepository.swift:150]: Thanks for the suggestion, I'll add the enumeration of each road shield text color corresponding UIColor in the Style. So we could work on the different color style. Right now the `WayNameLabel` would do the work to match the shield text color of the  road shield UIColor.

File: CHANGELOG.md [hunk 14]
```diff
@@ -51,8 +51,6 @@
...
 * Fixed an issue where release builds would crash on invalid navigator initialization. ([#3738](https://github.com/mapbox/mapbox-navigation-ios/pull/3738))
-* Added `routeShieldRepresentationKey` to the user info dictionary of `Notification.Name.passiveLocationManagerDidUpdate` posted by `PassiveLocationManager`, and the `Notification.Name.currentRoadNameDidChange` posted by `RouteController`. The corresponding value is a `MapboxDirections.VisualInstruction.Component.ImageRepresentation` object representing the road shield the user is currently traveling on. ([#3723](https://github.com/mapbox/mapbox-navigation-ios/pull/3723))
```
Comment (1ec5) [inline CHANGELOG.md]: Sorry for the confusion – this entry is worth mentioning, because it’s public. The other one is internal.

**Review by 1ec5 — APPROVED** [review]
