### PR TITLE
Fix attribution and logo layout

### LINKED ISSUE #236: Attribution and info button should be visible
image

image

/cc @frederoni

### PR DESCRIPTION
**Pull request by frederoni**
Fixes #236 

Besides moving the ornaments, this PR also changes the partially revealed height from 75% to 60% of the screen height.

@bsudekum 👀

### CODE REVIEW

File: MapboxNavigation/RouteMapViewController.swift [hunk 1]
```diff
@@ -47,8 +47,6 @@ class RouteMapViewController: UIViewController, PulleyPrimaryContentControllerDe
     var arrowCurrentStep: RouteStep?
     var isInOverviewMode = false
 
-    let overviewContentInset = UIEdgeInsets(top: 65, left: 15, bottom: 55, right: 15)
```
Comment (bsudekum) [inline MapboxNavigation/RouteMapViewController.swift]: Overview mode required some extra padding on all sides to account for the marker height. How does it look right now?

**Comment by bsudekum** [comment]
Looks good other than in this mode, two things:

* The 17m is clipped
* This image is also in overview mode. When we try and fit the bounds in this view, it zooms all the way out it looks like.

simulator screen shot jun 20 2017 9 53 23 am

**Comment by frederoni** [comment]
@bsudekum good catch. The overview content insets have been reverted.
The overlapping was an iOS 11 beta issue. It's the exact opposite but let's not make an exception for the first beta since it's still very flaky.



Here's another iOS 11 shot for demonstration:
