### PR TITLE
Show `UserHaloCourseView` only when `NavigationMapview.reducedAccuracyActivatedMode` is true under reducedAccuracy mode

### LINKED ISSUE #4027: [Bug]: Reduced accuracy view is not controllable
### Mapbox Navigation SDK version

2.7.0.beta2

### Steps to reproduce

Set the reducedAccuracyActivatedMode to false during initialisation.
The core location manager will fire an event after, making the reduced view appearing

### Expected behavior

I'm expecting to have control if I want to see the reduced ring view or not

### Actual behavior

Since mapbox navigation is using an internal location manager the user cannot override, we don't have control of it
Also there is a  condition with a OR in accuracy autorization that doesn't make sense. It should be a AND to give control to the user to show or not the accuracy ring view.

### Is this a one-time issue or a repeatable issue?

repeatable

### PR DESCRIPTION
**Pull request by ShanMa1991**
### Description
This Pr is to fix #4027. 

### Implementation
The `UserHaloCourseView` will be shown only when `NavigationMapview.reducedAccuracyActivatedMode` set to `true` and the `Precise Location` property in the settings of current application is disabled by user.

When `NavigationMapview.reducedAccuracyActivatedMode` is `false`, even when the location accuracy is reduced, the user location will still be drawn based on style, which was set in `NavigationMapView.userLocationStyle`.

### CODE REVIEW

File: Sources/MapboxNavigation/NavigationMapView.swift [hunk 1]
```diff
@@ -983,13 +983,16 @@ open class NavigationMapView: UIView {
...
      Allows to control current user location styling based on accuracy authorization permission on iOS 14 and above.
+     Defaults to `true`.
      
-     If `false`, user location will be drawn based on style, which was set in `NavigationMapView.userLocationStyle`.
+     When user disable the `Precise Location` property in the settings of current application:
      If `true`, `UserHaloCourseView` will be shown.
+     If `false`, user location will be drawn based on style, which was set in `NavigationMapView.userLocationStyle`.
      */
-    @objc dynamic public var reducedAccuracyActivatedMode: Bool = false {
+    @objc dynamic public var reducedAccuracyActivatedMode: Bool = true {
```
Comment (kried) [inline Sources/MapboxNavigation/NavigationMapView.swift:992]: Changing the default value of a public property feels kind of a breaking change.

Comment (ShanMa1991) [reply Sources/MapboxNavigation/NavigationMapView.swift:992]: Yes, I agree. Because previously when we set the `reducedAccuracyActivatedMode ` to `true`, it will automatically switch to the `UserHaloView` even the `precise location` is enabled. But it defaults to `false`, so when the  `precise location` is disabled, it will still show the `UserHaloView`, which causes some issue as in #4027 .

So I think this property should control whether we want to display the `UserHaloView` when the `precise location` is disabled. Because usually when `precise location` is enabled, we don't want to display this reduced view. If users don't want this automatic switch, they could change the It changes `reducedAccuracyActivatedMode ` to false. So even when the the `precise location` is disabled, it will still use the style defined `userLocationStyle`. 

I think it makes more sense but It changes the previous logic as well as the default value. So I add the ChangeLog entry for this change and also update the snapshot tests for these different circumstances.

Comment (ShanMa1991) [reply Sources/MapboxNavigation/NavigationMapView.swift]: I updated the default value to `false` as before.
