### PR TITLE
Fix the moment of custom feedback event creation

### LINKED ISSUE #2484: Feedback event should be created when tapping feedback button, not when completing the form
For feedback events, `NavigationEventDetails` is populated with coordinates, a screenshot, etc. when the structure is initialized as part of a call to `NavigationEventsManager.recordFeedback(type:description:)`. With the normal built-in feedback flow, this method gets called by side effect when getting `FeedbackViewController.uuid`, which currently only happens once the user taps a feedback category, right before we complete the feedback event with a category:

https://github.com/mapbox/mapbox-navigation-ios/blob/50def9e3dacb22c9ae3c95d54067afbcf1584afd/MapboxNavigation/FeedbackViewController.swift#L230-L234 https://github.com/mapbox/mapbox-navigation-ios/blob/50def9e3dacb22c9ae3c95d54067afbcf1584afd/MapboxNavigation/FeedbackViewController.swift#L126-L128

However, if the user taps the feedback button in CarPlay, `CarPlayNavigationViewController.createFeedbackUI()` creates the event and populates it right away when showing the feedback UI. mapbox/mapbox-navigation-android#3274 also moved the coordinate and screenshot capturing earlier to when the user taps the feedback button and the feedback UI appears.

For consistency with CarPlay and Android, we should do the same on iOS by getting `uuid` when initializing the FeedbackViewController. To avoid future confusion, we should also turn `uuid` into a method that obviously has a side effect.

/cc @mapbox/navigation-ios @avi-c @JunDai

### PR DESCRIPTION
**Pull request by dersim-davaod**
Fixes #2484

### CODE REVIEW

**Comment by Udumft** [comment]
This may not be related to this change, but to the mechanism in general. 
As I understood, each time we call `eventsManager?.recordFeedback()` there is a new`FeedbackEvent` created and enqueued. So, even if user opened the Feedback UI and then closed it, we still create 2 events (1 at `commonInit()` and 2 in `dismissFeedback()` method. `eventsManager?.recordFeedback()` effectively creates and enqueues new event). Shouldn't we instead create only one`FeedbackEvent` and 'cache' it's `uuid` in `FeedbackViewController` instance for further manipulations?

**Comment by dersim-davaod** [comment]
@Udumft yes, makes sense for me to implement this. Will update PR soon.

File: MapboxNavigation/FeedbackViewController.swift [hunk 1]
```diff
@@ -226,30 +224,49 @@ public class FeedbackViewController: UIViewController, DismissDraggable, UIGestu
...
     }
+
+    /**
+     Gets an unique identifier used to identify the current feedback event.
+
+     The UUID that method returns is the result of calling `NavigationEventsManager.recordFeedback()`.
+
+     - Returns: UUID used to identify the current feedback event.
+     */
+    @discardableResult private func currentFeedbackEventID() -> UUID? {
```
Comment (1ec5) [inline MapboxNavigation/FeedbackViewController.swift:267]: This method’s name should indicate that it has a side effect, not just that it returns a UUID. `recordFeedback()` would be appropriate here.

**Comment by bamx23** [comment]
The feedback UUID is still generated for every call of `currentFeedbackEventID()`, so I guess the @Udumft's comment above is still actual.

File: Sources/MapboxNavigation/FeedbackViewController.swift [hunk 2]
```diff
@@ -231,30 +231,48 @@ public class FeedbackViewController: UIViewController, DismissDraggable, UIGestu
...
-    
+
+    /**
+     Sends the current feedback event for the specific feedback item.
+
+     - Parameter item: a feedback item for which feedback will be sent.
+     */
     func send(_ item: FeedbackItem) {
-        if let uuid = self.uuid {
+        if let uuid = currentFeedbackUUID {
```
Comment (bamx23) [inline Sources/MapboxNavigation/FeedbackViewController.swift:241]: When does this fail? Should we handle such errors explicitly?

File: Sources/MapboxNavigation/FeedbackViewController.swift [hunk 3]
```diff
@@ -156,6 +154,8 @@ public class FeedbackViewController: UIViewController, DismissDraggable, UIGestu
     func commonInit() {
         self.modalPresentationStyle = .custom
         self.transitioningDelegate = self
+
+        currentFeedbackUUID = self.recordCurrentFeedback()
```
Comment (bamx23) [inline Sources/MapboxNavigation/FeedbackViewController.swift:158]: Is it OK to make a screenshot implicitly in the constructor of this class?

**Review by bamx23 — APPROVED** [review]
LGTM overall. I haven't checked this PR in the 1Tap, but it seems to solve the issue of wrong screenshots/data.

File: Sources/MapboxNavigation/FeedbackViewController.swift (hunk 2 above)
Comment (dersim-davaod) [reply Sources/MapboxNavigation/FeedbackViewController.swift:241]: Agreed to leave it as it is. Possible error handling can be done in scope of separate PR.

File: Sources/MapboxNavigation/FeedbackViewController.swift (hunk 3 above)
Comment (dersim-davaod) [reply Sources/MapboxNavigation/FeedbackViewController.swift]: Agreed to make currentFeedbackUUID lazy var to avoid creation of cached UUID in the init method.

But there're another topics to discuss:
- in the future we might want to have an opportunity to control the moment of feedback creation explicitly (say, using public API method)
- this also causes creation and immediate removal of feedback screenshot in the `dismissFeedbackItem` method.

Comment (dersim-davaod) [reply Sources/MapboxNavigation/FeedbackViewController.swift]: Reverted, as it is better to call `recordFeedback` in the constructor, otherwise the screenshot will have a different UI at the moment of sending.

File: Sources/MapboxNavigation/FeedbackViewController.swift [hunk 4]
```diff
@@ -129,11 +129,9 @@ public class FeedbackViewController: UIViewController, DismissDraggable, UIGestu
      The events manager used to send feedback events.
      */
     public weak var eventsManager: NavigationEventsManager?
-    
-    var uuid: UUID? {
-        return eventsManager?.recordFeedback()
-    }
-    
+
+    private var currentFeedbackUUID: UUID?
```
[the remark this answers is not in the document]
Comment (dersim-davaod) [reply Sources/MapboxNavigation/FeedbackViewController.swift:133]: Fixed.

**Review by bamx23 — APPROVED** [review]

File: Sources/MapboxNavigation/FeedbackViewController.swift (hunk 4 above)
[the remark this answers is not in the document]
Comment (1ec5) [reply Sources/MapboxNavigation/FeedbackViewController.swift:133]: [Current builds are still failing on the same error](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/2929/workflows/43180726-7aaf-47f5-84ef-eddedeb4d449/jobs/29106).

File: Sources/MapboxNavigation/FeedbackViewController.swift [hunk 5]
```diff
@@ -133,6 +133,11 @@ public class FeedbackViewController: UIViewController, DismissDraggable, UIGestu
     var uuid: UUID? {
```
Comment (bamx23) [inline Sources/MapboxNavigation/FeedbackViewController.swift:133]: Do we need this now?

File: Sources/MapboxNavigation/Resources/de.lproj/Localizable.strings [hunk 6]
```diff
@@ -91,6 +94,9 @@
 /* Label indicating the device volume is too low to hear spoken instructions and needs to be manually increased */
 "INAUDIBLE_INSTRUCTIONS_CTA" = "Lautstärke anpassen, um Anweisungen zu hören";
 
+/* Specific route feedback that a speed limit is incorrect. */
+"INCORRECT_SPEED_LIMIT" = "Speed limit incorrect";
```
Comment (bamx23) [inline Sources/MapboxNavigation/Resources/de.lproj/Localizable.strings:98]: Why are there so many unrelated changes?

File: Sources/MapboxNavigation/FeedbackViewController.swift (hunk 5 above)
Comment (dersim-davaod) [reply Sources/MapboxNavigation/FeedbackViewController.swift:133]: removed.

File: Sources/MapboxNavigation/Resources/de.lproj/Localizable.strings (hunk 6 above)
Comment (dersim-davaod) [reply Sources/MapboxNavigation/Resources/de.lproj/Localizable.strings:98]: These changes are not intented for this PR, should be updated, thanks!

**Comment by S2Ler** [comment]
Removed unnecessary commits introduced due to incorrect rebase.

File: Sources/MapboxNavigation/FeedbackViewController.swift (hunk 5 above)
Comment (bamx23) [reply Sources/MapboxNavigation/FeedbackViewController.swift:133]: Once again, do we need this now?

**Comment by S2Ler** [comment]
The builds are failing because the machine can't download needed simulators.

File: Sources/MapboxNavigation/FeedbackViewController.swift (hunk 5 above)
Comment (bamx23) [reply Sources/MapboxNavigation/FeedbackViewController.swift:133]: сс @S2Ler

Comment (S2Ler) [reply Sources/MapboxNavigation/FeedbackViewController.swift]: Not needed. Removed.

Comment (S2Ler) [reply Sources/MapboxNavigation/FeedbackViewController.swift]: Removed. No longer used.

**Comment by bamx23** [comment]
LGTM, thanks
