### PR TITLE
Fix lifecycle issue when using storyboard

### LINKED ISSUE #273: Obj-C demo app crashes when selecting destination
When long-pressing to select a destination in the Obj-C demo app, the segue to the route controller crashes.

```
fatal error: unexpectedly found nil while unwrapping an Optional value
```

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x1023e0448)
  * frame #0: 0x00000001023e0448 libswiftCore.dylib`function signature specialization <preserving fragile attribute, Arg[2] = Dead, Arg[3] = Dead> of Swift._fatalErrorMessage (Swift.StaticString, Swift.StaticString, file : Swift.StaticString, line : Swift.UInt, flags : Swift.UInt32) -> Swift.Never + 120
    frame #1: 0x00000001006c7f40 MapboxNavigation`NavigationViewController.setupRouteController(self=0x000000010388dc00) -> () at NavigationViewController.swift:361
    frame #2: 0x00000001006c1ca8 MapboxNavigation`NavigationViewController.route.didset(oldValue=nil, self=0x000000010388dc00) at NavigationViewController.swift:118
    frame #3: 0x00000001006c1c50 MapboxNavigation`NavigationViewController.route.setter(newValue=0x000000017087eb00, self=0x000000010388dc00) at NavigationViewController.swift:0
    frame #4: 0x00000001006c1ba4 MapboxNavigation`@objc NavigationViewController.route.setter at NavigationViewController.swift:0
    frame #5: 0x00000001000696cc Example-Objective-C`-[ViewController prepareForSegue:sender:](self=0x000000010320e7c0, _cmd="prepareForSegue:sender:", segue=0x0000000170475880, sender=0x000000010320e7c0) at ViewController.m:139
    frame #6: 0x000000018f2bcb90 UIKit`-[UIStoryboardSegueTemplate _performWithDestinationViewController:sender:] + 352
    frame #7: 0x000000018f2bc9fc UIKit`-[UIStoryboardSegueTemplate _perform:] + 92
    frame #8: 0x000000018ee5be7c UIKit`-[UIViewController performSegueWithIdentifier:sender:] + 108
    frame #9: 0x00000001000697e0 Example-Objective-C`-[ViewController startNavigation:](self=0x000000010320e7c0, _cmd="startNavigation:", route=0x000000017087eb00) at ViewController.m:148
    frame #10: 0x00000001000694d4 Example-Objective-C`__26-[ViewController getRoute]_block_invoke((null)=<unavailable>, waypoints=0x0000000170246bd0, routes=0x0000000170249d50, error=0x0000000000000000) at ViewController.m:130
    frame #11: 0x00000001001c7c10 MapboxDirections`thunk at MBDirections.swift:0 [opt]
    frame #12: 0x00000001001c79a0 MapboxDirections`Directions.(calculate(RouteOptions, completionHandler : ([Waypoint]?, [Route]?, NSError?) -> ()) -> URLSessionDataTask).(closure #1) [inlined] function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Owned To Guaranteed> of MapboxDirections.Directions.(options=0x0000000170287e90) -> ()) -> __ObjC.URLSessionDataTask).(closure #1) at MBDirections.swift:171 [opt]
    frame #13: 0x00000001001c7918 MapboxDirections`Directions.(calculate(RouteOptions, completionHandler : ([Waypoint]?, [Route]?, NSError?) -> ()) -> URLSessionDataTask).(closure #1) at MBDirections.swift:169 [opt]
```

### PR DESCRIPTION
**Pull request by frederoni**
Fixes #273 

RouteController and delegates were unset when using the storyboard approach.
Also fixed so that SimulatedLocationManager bridges to Obj-C

@friedbunny 👀

### CODE REVIEW

File: MapboxCoreNavigation/RouteController.swift [hunk 1]
```diff
@@ -88,7 +88,11 @@ open class RouteController: NSObject {
     /**
      The route controller’s associated location manager.
      */
-    public var locationManager: NavigationLocationManager!
+    public var locationManager: NavigationLocationManager! {
+        didSet {
+            locationManager.delegate = self
```
Comment (1ec5) [inline MapboxCoreNavigation/RouteController.swift]: Good idea. Should we unset `oldValue`’s delegate too, just in case the developer swaps location managers?
