### PR TITLE
Move location calculation to a background queue

### LINKED ISSUE #3129: SimulatedLocationManager on long routes consumes a lot of CPU on the main thread
**Mapbox Navigation SDK version:** release-v2.0 aa442b9191e8efe79cf35dd790526c8e3a45615b

### Steps to reproduce

 1. Take a 10000 km long route
 2. Start simulated navigation
 3. Check CPU usage on the main thread

### Expected behavior
SimulatedLocationManager doesn't consume a lot of CPU on the main thread.

### Actual behavior
SimulatedLocationManager consumes a lot of CPU on the main thread. 

### Proposed solution 

Move time consuming work in SimulatedLocationManager to a non-main DispatchQueue.

### PR DESCRIPTION
**Pull request by chezzdev**
Fixes #3129.

### CODE REVIEW

File: Sources/MapboxCoreNavigation/SimulatedLocationManager.swift [hunk 1]
```diff
@@ -160,9 +162,9 @@ open class SimulatedLocationManager: NavigationLocationManager {
                                   course: newCoordinate.direction(to: lookAheadCoordinate).wrap(min: 0, max: 360),
                                   speed: currentSpeed,
                                   timestamp: Date())
-        
+
         self.simulatedLocation = location
-        
+
         delegate?.locationManager?(self, didUpdateLocations: [location])
```
Comment (Udumft) [inline Sources/MapboxCoreNavigation/SimulatedLocationManager.swift:168]: Since `tick` is now executed on another thread, should this delegate call be explicitly done on `main`?

Default `CLLocationManager` captures the thread it was instantiated on for location update calls, but our implementation forced a main thread

Comment (bamx23) [inline Sources/MapboxCoreNavigation/SimulatedLocationManager.swift:168]: Should this call me made on the main queue?

**Review by bamx23 — COMMENTED** [review]
What about a changelog line?

**Review by Udumft — COMMENTED** [review]
Did you manage to measure CPU usage change after these changes?

**Review by 1ec5 — COMMENTED** [review]
If the performance improvement is non-negligible for long routes, consider adding a changelog entry to that effect. Thanks!

File: Sources/MapboxCoreNavigation/SimulatedLocationManager.swift (hunk 1 above)
Comment (chezzdev) [reply Sources/MapboxCoreNavigation/SimulatedLocationManager.swift]: It may make sense to get back a delegate call to the main thread to minimize potential side effects in execution.
However, I doubt that anything downstream should rely on this call being executed on the main thread.

Comment (chezzdev) [reply Sources/MapboxCoreNavigation/SimulatedLocationManager.swift]: Probably yes.
https://github.com/mapbox/mapbox-navigation-ios/pull/3672#discussion_r833390975

**Review by bamx23 — APPROVED** [review]

File: Sources/MapboxCoreNavigation/SimulatedLocationManager.swift (hunk 1 above)
Comment (chezzdev) [reply Sources/MapboxCoreNavigation/SimulatedLocationManager.swift]: Now I remember why I left the delegate call on the same queue as `tick` - out tests heavily rely on synchronous delegate call inside `tick`.

Comment (chezzdev) [reply Sources/MapboxCoreNavigation/SimulatedLocationManager.swift:168]: @bamx23 multiple tests and test fixtures rely on a synchronous delegate call inside the `tick` method. Since we're not guaranteeing execution on a specific queue, I'm proposing leaving it on a custom background queue.

Comment (bamx23) [reply Sources/MapboxCoreNavigation/SimulatedLocationManager.swift:168]: IMO it's a risky change. What if we add a nullable parameter to the manager with the queue on which the callback should be called and keep it `nil` in tests to make calls synchronous while having the default value of `main` queue?

Comment (Udumft) [reply Sources/MapboxCoreNavigation/SimulatedLocationManager.swift:168]: But I believe the point of this PR is to make it non-main thread by default... As Alex said, our tests are failing if we introduce explicit main thread call, so there's a good chance the same will happen with user code. We could instead document that delegate will be called on a background instead, so user will be able to manage threading himself if he needs it.

**Review by Udumft — APPROVED** [review]
LGTM, but please also document delegate calling thread change.
