### PR TITLE
Remove arrow if the route line is removed after arrival

### LINKED ISSUE #4035: [Bug]:  Arrow not removed after arrival.
### Mapbox Navigation SDK version

v2.6.0 -

### Steps to reproduce

1. build `Example ` app, choose  a destination very close to the road turn.
2. start navigation, with the default example to allow the vanishing effect of the route line.

### Expected behavior

After arrival, the maneuver will be removed, because the route line removed for the vanishing effect. 

### Actual behavior

The maneuver is shown with the route line removed.
arrowArrive

### Is this a one-time issue or a repeatable issue?

repeatable

### PR DESCRIPTION
**Pull request by ShanMa1991**
### Description
This Pr is to fix #4035 by removing arrow when the route line is removed after arrival. 

### Screenshots or Gifs
arrivalArrow

### CODE REVIEW

File: Sources/MapboxNavigation/RouteLineController.swift [hunk 1]
```diff
@@ -106,7 +106,8 @@ extension NavigationMapView {
         }
         
         private func updateMapOverlays(for routeProgress: RouteProgress) {
-            if routeProgress.currentLegProgress.followOnStep != nil {
+            if routeProgress.currentLegProgress.followOnStep != nil,
+               navigationMapView.routes != nil {
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/RouteLineController.swift:110]: Why do we need this additional condition? We have similar code in `CarPlayNavigationViewController`, so if it's really needed we have to update CarPlay part as well.

File: Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift [hunk 2]
```diff
@@ -63,6 +63,7 @@ extension NavigationMapView {
         guard !routeProgress.routeIsComplete else {
             removeRoutes()
             removeContinuousAlternativesRoutes()
+            removeArrow()
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift:66]: This issue only happens when vanishing route line functionality is enabled?

File: CHANGELOG.md [hunk 3]
```diff
@@ -13,6 +13,7 @@
 * Each alternative route shown during turn-by-turn navigation is now annotated with the amount of time it saves or adds to the trip. To hide these annotations, set the `NavigationMapView.showsRelativeDurationOnContinuousAlternativeRoutes` property to `false`. ([#3956](https://github.com/mapbox/mapbox-navigation-ios/pull/3956))
 * Fixed the issue where the route line endpoint is ahead of user location indicator on short straight-line route step when `NavigationViewController.routeLineTracksTraversal` enabled in active navigation. ([#3992](https://github.com/mapbox/mapbox-navigation-ios/pull/3992))
 * Added the ability to provide duration and completion handler while visualizing routes using `NavigationMapView.showcase(_:animated:duration:completion:)`. ([#4022](https://github.com/mapbox/mapbox-navigation-ios/pull/4022))
+* Fixed the issue where the route line is removed after arrival but arrow is remained. ([#4040](https://github.com/mapbox/mapbox-navigation-ios/pull/4040))
```
Comment (MaximAlien) [inline CHANGELOG.md:16]:
```suggestion
* Fixed an issue where the maneuver arrow is not removed after arriving to the final destination. ([#4040](https://github.com/mapbox/mapbox-navigation-ios/pull/4040))
```

**Review by MaximAlien — APPROVED** [review]

File: Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift (hunk 2 above)
Comment (ShanMa1991) [reply Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift:66]: Yes. If the vanishing route line functionality is not enabled, the route line will not be removed. So it's reasonable to keep the arrow. 
And we only remove the route and route line when the vanishing route line functionality is enabled and route is complete. So it's safe that we check whether the route is removed after  `navigationMapView?.updateRouteLine(routeProgress:coordinate:shouldRedraw:)`, and if the route is removed, we should remove the arrow.

File: Sources/MapboxNavigation/RouteLineController.swift (hunk 1 above)
Comment (ShanMa1991) [reply Sources/MapboxNavigation/RouteLineController.swift:110]: Thanks for the suggestion, I'll update the CarPlay part as well.
