### PR TITLE
Fix MapboxCoreNavigationTests and TestHelper build errors

### LINKED ISSUE #2866: MapboxCoreNavigation fails to build on CI — Multiple commands produce MapboxCoreNavigation.swiftmodule
As of #2863, the Carthage-based MapboxCoreNavigation build is [failing](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/2778/workflows/c3e405b9-70c0-4ec4-95ff-03d213ead388/jobs/28199) on the release-v2.0 branch with lots of errors like this:

```
error: Multiple commands produce '/Users/distiller/Library/Developer/Xcode/DerivedData/MapboxNavigation-gtrukiuwvhbmctfcsthejciepfao/Build/Intermediates.noindex/MapboxNavigation.build/Debug-iphonesimulator/MapboxCoreNavigation.build/Objects-normal/x86_64/MapboxCoreNavigation.swiftmodule':
1) Target 'MapboxCoreNavigation' (project 'MapboxNavigation') has compile command for Swift source files
2) Target 'MapboxCoreNavigation' (project 'MapboxNavigation') has compile command for Swift source files
```

I think it might have something to do with the fact that Xcode automatically generates a scheme with the same “MapboxCoreNavigation” name as the shared scheme in the Xcode project. But the error message seems to indicate that it found the right scheme and target – just that the target has been duplicated for some reason. I haven’t managed to reproduce this issue locally in Xcode 12.4, so I don’t know if it’s specific to the rest of the CircleCI configuration.

/cc @mapbox/navigation-ios

### PR DESCRIPTION
**Pull request by 1ec5**
Updated test code to reflect file moves related to expanded SPM support in #2808 and the shared navigator refactor in #2823. Removed a broken file reference left over from when #2834 included a unit test of electronic horizon functionality.

Fixes #2866.

/cc @mapbox/navigation-ios

### CODE REVIEW

**Comment by 1ec5** [comment]
Locally, I’m able to build successfully for a specific simulator but get the following error when building for Any iOS Device:

> error: Cycle inside MapboxCoreNavigationTests; building could produce unreliable results.
> Cycle details:
> → Target 'MapboxCoreNavigationTests': CodeSign /path/to/Library/Developer/Xcode/DerivedData/MapboxNavigation-alytgpeiocddhmempehvwkpsbezh/Build/Products/Debug-iphoneos/Example.app
> ○ Target 'MapboxCoreNavigationTests': CodeSign /path/to/Library/Developer/Xcode/DerivedData/MapboxNavigation-alytgpeiocddhmempehvwkpsbezh/Build/Products/Debug-iphoneos/Example.app

On CI, [this job](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/2811/workflows/5a5f33b1-c844-4ada-b0bd-b960db3a2526/jobs/28388) sucessfully builds for a specific simulator but fails to launch Example.app – even though we removed the dependency on Example.app:

> Example.app encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/distiller/Library/Developer/Xcode/DerivedData/MapboxNavigation-gtrukiuwvhbmctfcsthejciepfao/Logs/Test/Run-MapboxCoreNavigation-2021.03.17_19-56-20-+0000.xcresult. (Underlying Error: Failed to install the requested application. The bundle identifier of the application could not be determined. Ensure that the application's Info.plist contains a value for CFBundleIdentifier.))

**Comment by 1ec5** [comment]
The following tests [fail](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/2812/workflows/ac853660-6885-4d47-90cb-e8ab76f38184/jobs/28392) because of #2851:

```
		MapboxCoreNavigationTests.testArrive()
		MapboxCoreNavigationTests.testDepart()
		MapboxCoreNavigationTests.testFailToReroute()
		MapboxCoreNavigationTests.testJumpAheadToLastStep()
		MapboxCoreNavigationTests.testNavigationNotificationsInfoDict()
		MapboxCoreNavigationTests.testNewStep()
		MapboxCoreNavigationTests.testOrderOfExecution()
		MapboxCoreNavigationTests.testShouldReroute()
		MapboxNavigationServiceSpec.MapboxNavigationService__Must_not_leak_()
		NavigationEventsManagerTests.testNavigationEventDetailsGlobalQueue()
		NavigationServiceTests.testCountdownTimerDefaultAndUpdate()
		NavigationServiceTests.testDefaultUserInterfaceUsage()
		NavigationServiceTests.testGeneratingAnArrivalEvent()
		NavigationServiceTests.testLegacyRouteControllerDoesNotHaveRetainCycle()
		NavigationServiceTests.testLocationCourseShouldNotChange()
		NavigationServiceTests.testMultiLegRoute()
		NavigationServiceTests.testNoReroutesAfterArriving()
		NavigationServiceTests.testNotReroutingForAllSteps()
		NavigationServiceTests.testProactiveRerouting()
		NavigationServiceTests.testReroutingFromALocationSendsEvents()
		NavigationServiceTests.testReroutingFromLocationUpdatesSimulatedLocationSource()
		NavigationServiceTests.testRouteControllerDoesNotHaveRetainCycle()
		NavigationServiceTests.testRouteControllerDoesNotRetainDataSource()
		NavigationServiceTests.testSnappedAtEndOfStepLocationWhenCourseIsSimilar()
		NavigationServiceTests.testSnappedAtEndOfStepLocationWhenMovingSlowly()
		NavigationServiceTests.testSnappedLocationForUnqualifiedLocation()
		NavigationServiceTests.testTurnstileEventSentUponInitialization()
		NavigationServiceTests.testUnimplementedLogging()
		NavigationServiceTests.testUserIsOffRoute()
		NavigationServiceTests.testUserIsOnRoute()
		RouteControllerTests.testRouteSnappingOvershooting()
		SimulatedLocationManagerTests.testSimulateRouteDoublesBack()
```

**Comment by ShanMa1991** [comment]
The tests failed by the #2851 could be fixed in #2876, some other tests integration errors would be fixed in #2876 as well.

File: Tests/MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift [hunk 1]
```diff
@@ -69,13 +69,9 @@ class PassiveLocationDataSourceTests: XCTestCase {
         let filePathURL: URL = URL(fileURLWithPath: bundle.bundlePath.appending("/tiles/liechtenstein"))
 
         // Create PassiveLocationDataSource and configure it with the tiles version (version is used to find the tiles in the cache folder)
+        Navigator.tilesVersion = tilesVersion
```
Comment (MaximAlien) [inline Tests/MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift:72]: Is this change really going to affect underlying navigator configuration? I think if shared navigator was created elsewhere underlying properties will change, but Navigator will still use previous ones.

**Review by MaximAlien — APPROVED** [review]

File: Tests/MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift (hunk 1 above)
Comment (1ec5) [reply Tests/MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift:72]: Yes, this test will have side effects in Navigator that would affect any other test in this class. We can move the settings to `setUpWithError()` to ensure consistency regardless of execution order, but otherwise I don’t think we can be any more robust, because ultimately Navigator’s underlying `MapboxNavigationNative.Navigator` is also a singleton that lasts for the remainder of the process.
