### PR TITLE
Adjust the layer position to make puck layer at topmost

### LINKED ISSUE #3098: 3D puck layer not at the top most of navigationMapView
**Mapbox Navigation SDK version: v2.0.0-beta.13 to v2.0.0-beta.14

### Steps to reproduce
provide 3D configuration to the `navigationMapView.userLocationStyle`
 1. start navigation
 2. clear map
 3. start again

### Expected behavior
The 3D puck should be at the top most, same as 2D puck

### Actual behavior
It's covered by maneuvers as following:
puck3D

### PR DESCRIPTION
**Pull request by ShanMa1991**
### Description
This pr is to fix #3098 , because the 3D puck from map side doesn't support the default topmost layer position similar as 2D puck. This pr is to check the 3D puck layer and make it above the maneuvers when we call `func navigationMapView.addArrow`.

### Implementation
Because the 3D puck from map side doesn't support the default topmost layer position similar as 2D puck. This pr is to check the 3D puck layer and make it above the maneuvers when we call `func navigationMapView.addArrow`

### Screenshots or Gifs

### CODE REVIEW

File: Sources/MapboxNavigation/NavigationMapView.swift [hunk 1]
```diff
@@ -904,7 +905,9 @@ open class NavigationMapView: UIView {
                     try mapView.mapboxMap.style.addSource(arrowSource, id: NavigationMapView.SourceIdentifier.arrowSource)
                     arrowLayer.source = NavigationMapView.SourceIdentifier.arrowSource
                     
-                    if mapView.mapboxMap.style.sourceExists(withId: NavigationMapView.LayerIdentifier.waypointCircleLayer) {
+                    if allLayerIds.contains(NavigationMapView.LayerIdentifier.puck3DLayer) {
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/NavigationMapView.swift:908]: If layer already exists why're we adding it, instead of updating?

Comment (ShanMa1991) [reply Sources/MapboxNavigation/NavigationMapView.swift:908]: It is to check whether the 3D puck layer exists, if the 3D puck layer exists, we add the `arrowLayer` below the puck3D layer. It's the same case for `arrowSymbolLayer`, to add it below the 3D puck layer.

**Comment by ShanMa1991** [comment]
The CarPlay has issue with adding maneuvers based on the following error, which leads to the abrupt stop of adding the `arrowStrokeLayer`, `arrowSymbolLayer` and `arrowSymbolCasingLayer`
```
Failed to perform operation while adding maneuver arrow with error: Cannot find layer with id: 0x000060000070eb00.main.route_line.
```

File: Sources/MapboxNavigation/NavigationMapView.swift (hunk 1 above)
Comment (ShanMa1991) [reply Sources/MapboxNavigation/NavigationMapView.swift:910]: The CarPlay issue with maneuvers should be related with the layerID problem as [below](https://github.com/mapbox/mapbox-navigation-ios/pull/3106#issuecomment-867119146) , add the check of layer existence before set layer position. Similar issue happened for the way point circle layer.

File: Sources/MapboxNavigation/NavigationMapView.swift [hunk 2]
```diff
@@ -929,7 +932,11 @@ open class NavigationMapView: UIView {
                     
                     try mapView.mapboxMap.style.addSource(arrowStrokeSource, id: NavigationMapView.SourceIdentifier.arrowStrokeSource)
                     arrowStrokeLayer.source = NavigationMapView.SourceIdentifier.arrowStrokeSource
-                    try mapView.mapboxMap.style.addLayer(arrowStrokeLayer, layerPosition: .above(mainRouteLayerIdentifier))
+                    if allLayerIds.contains(mainRouteLayerIdentifier) {
```
Comment (ShanMa1991) [inline Sources/MapboxNavigation/NavigationMapView.swift:935]: The CarPlay's issue with maneuvers should be related with the layerID problem here. Sometimes the `mapView` could not find the `mainRouteLayerIdentifier`. Thus add the check of layer existence before setting layer position. Similar issue happened for the waypoint circle layer.

**Comment by S2Ler** [comment]
Thanks for writing tests 👍

File: Sources/MapboxNavigation/NavigationMapView.swift [hunk 3]
```diff
@@ -929,7 +932,11 @@ open class NavigationMapView: UIView {
...
+                        try mapView.mapboxMap.style.addLayer(arrowStrokeLayer, layerPosition: .above(mainRouteLayerIdentifier))
+                    } else {
+                        try mapView.mapboxMap.style.addLayer(arrowStrokeLayer, layerPosition: .below(NavigationMapView.LayerIdentifier.arrowLayer))
```
Comment (1ec5) [inline Sources/MapboxNavigation/NavigationMapView.swift:938]: Nit: factor this line out of the conditional so that only the layer position is in the conditional.

File: Tests/MapboxNavigationTests/NavigationViewControllerTests.swift [hunk 4]
```diff
@@ -235,6 +235,32 @@ class NavigationViewControllerTests: XCTestCase {
         XCTAssert(newAnnotations.contains { $0.coordinate.distance(to: secondDestination) < 1 }, "New destination annotation does not exist on map")
     }
     
+    func testpuck3DLayerPosition() {
```
Comment (1ec5) [inline Tests/MapboxNavigationTests/NavigationViewControllerTests.swift:238]: Nit:

```suggestion
    func testPuck3DLayerPosition() {
```

**Review by 1ec5 — APPROVED** [review]
