### PR TITLE
Align the margin of floating buttons with map attribution button during active navigation.

### LINKED ISSUE #3775: [Bug]: Floating buttons not aligned with map attribution button when device rotates.
### Steps to reproduce

1. Build the `Example` or the test app, and allow the screen to rotate.

### Expected behavior

The floating buttons should be aligned with the map attribution button when device rotates.

### Actual behavior

1. When we start from the regular screen, rotate it to the compact, and make the status bar at the landscape right node. It shows correctly. Then we rotate it to upside down screen, and then to the landscape left mode. 
    It should have the floating buttons adjust to the landscape left mode, but it doesn't, which make the floating buttons not aligned with the attribution button.
2. When we start from the regular screen or rotate to the make the status bar at the landscape left node. It shows correctly. Then we rotate it to upside down screen, and then to the landscape right mode. 
    It should have the floating buttons adjust to the landscape right mode, but it doesn't, which make the floating buttons not aligned with the attribution button.

The issue is caused by the rotating of `landscape left - upside down mode - landscape right mode`, wouldn't trigger the `traitCollectionDidChange` of the `navigationView` to update the floating buttons layout. But the map attribution button is listening to the device orientation change, and could be updated.

### Is this a one-time issue or a repeatable issue?

repeatable

### PR DESCRIPTION
**Pull request by ShanMa1991**
### Description
This PR is to fix #3775 and to align the floatings buttons margin with the map info button during active navigation.

### Implementation
Update the layout of the `NavigationView` when the device orientation change instead of the `traitCollectionDidChange`. And increase the distance of the map info button to the same as the floating buttons. It could fix the issue where the map info button at the safe area margin and sometimes unclickable.

### Screenshots or Gifs
The updated `landscapeLeft` mode.
updatedLandscapeLeft

The updated `landscapeRight` mode.
updated_landscapeRight

### CODE REVIEW

File: Sources/MapboxNavigation/OrnamentsController.swift [hunk 1]
```diff
@@ -153,10 +154,10 @@ class OrnamentsController: NavigationComponent, NavigationComponentDelegate {
                                                                                             y: y - navigationView.safeAreaInsets.bottom)
         case .compact:
             if UIApplication.shared.statusBarOrientation == .landscapeRight {
-                navigationMapView.mapView.ornaments.options.attributionButton.margins = CGPoint(x: -navigationView.safeAreaInsets.right,
+                navigationMapView.mapView.ornaments.options.attributionButton.margins = CGPoint(x: x - navigationView.safeAreaInsets.right,
```
Comment (ShanMa1991) [inline Sources/MapboxNavigation/OrnamentsController.swift:157]: Increase the margin distance to the same as the floating buttons. It would solve the issue where the button is sometimes untappable in landscape mode because too close to the margin.

File: CHANGELOG.md [hunk 2]
```diff
@@ -51,6 +51,7 @@ The v2.2.0 release notes [clarified](https://github.com/mapbox/mapbox-navigation
 * Fixed an issue where changing `NavigationViewController.showsReportFeedback`, `NavigationViewController.showsSpeedLimits`, `NavigationViewController.detailedFeedbackEnabled`, `NavigationViewController.floatingButtonsPosition` and `NavigationViewController.floatingButtons` before presenting `NavigationViewController` had no effect. ([#3718](https://github.com/mapbox/mapbox-navigation-ios/pull/3718))
 * Fixed an issue where `SpeechSynthesizing.managesAudioSession` was ignored by `RouteVoiceController`. ([#3572](https://github.com/mapbox/mapbox-navigation-ios/pull/3572))
 * Fixed the gap between the end-of-route feedback panel and the bottom of the screen in landscape orientation. ([#3769](https://github.com/mapbox/mapbox-navigation-ios/pull/3769))
+* Fixed an issue where the floating buttons not aligned with map attribution button when device rotates during active navigation. ([#3776](https://github.com/mapbox/mapbox-navigation-ios/pull/3776))
```
Comment (1ec5) [inline CHANGELOG.md:54]:
```suggestion
* Fixed an issue where the map’s floating buttons are misaligned with its attribution button and sometimes untappable after rotating the device during turn-by-turn navigation. ([#3776](https://github.com/mapbox/mapbox-navigation-ios/pull/3776))
```

**Review by 1ec5 — APPROVED** [review]

File: Sources/MapboxNavigation/NavigationViewLayout.swift [hunk 3]
```diff
@@ -281,10 +281,4 @@ extension NavigationView {
         compactConstraints.forEach({ $0.isActive = traitCollection.verticalSizeClass == .compact })
         regularConstraints.forEach({ $0.isActive = traitCollection.verticalSizeClass == .regular })
     }
-    
-    open override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
-        if previousTraitCollection == traitCollection { return }
-        
-        setupConstraints()
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/NavigationViewLayout.swift:288]: Why you've decided to call this method only during orientation change?

Comment (ShanMa1991) [reply Sources/MapboxNavigation/NavigationViewLayout.swift:288]: Because on mobile the size class changes when the device rotates and a duplicate call for the orientation change. But it happens on other circumstances as well on other devices. I'll add it back.

File: CHANGELOG.md (hunk 2 above)
Comment (ShanMa1991) [reply CHANGELOG.md]: Thanks for the suggestion, the changeLog has been updated.
