### PR TITLE
Fix MapboxCoreNavigationTests failures with reset of navigator before location update each time

### LINKED ISSUE #2913: MapboxCoreNavigationTests failures related with RouteController and Navigator need to fix
The MapboxCoreNavigationTests failed in the following tests as in [the workflow](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/2950/workflows/920fa868-d1c5-4e45-b33a-a280266b252c/jobs/29227). They seem to be related with RouteController and Navigator, which need to investigate and fix.
```
MapboxCoreNavigationTests.testDepart()
		MapboxCoreNavigationTests.testDepart()
		MapboxCoreNavigationTests.testNewStep()
		MapboxCoreNavigationTests.testNewStep()
		MapboxCoreNavigationTests.testOrderOfExecution()
		MapboxCoreNavigationTests.testOrderOfExecution()
		MapboxCoreNavigationTests.testOrderOfExecution()
		MapboxCoreNavigationTests.testShouldReroute()
		MapboxCoreNavigationTests.testShouldReroute()
		NavigationServiceTests.testGeneratingAnArrivalEvent()
		NavigationServiceTests.testLocationCourseShouldNotChange()
		NavigationServiceTests.testMultiLegRoute()
		NavigationServiceTests.testMultiLegRoute()
		NavigationServiceTests.testProactiveRerouting()
		NavigationServiceTests.testReroutingFromALocationSendsEvents()
		NavigationServiceTests.testSnappedAtEndOfStepLocationWhenCourseIsSimilar()
		NavigationServiceTests.testSnappedAtEndOfStepLocationWhenCourseIsSimilar()
		NavigationServiceTests.testSnappedAtEndOfStepLocationWhenCourseIsSimilar()
		NavigationServiceTests.testSnappedAtEndOfStepLocationWhenCourseIsSimilar()
		NavigationServiceTests.testSnappedAtEndOfStepLocationWhenCourseIsSimilar()
		NavigationServiceTests.testSnappedAtEndOfStepLocationWhenMovingSlowly()
		NavigationServiceTests.testSnappedAtEndOfStepLocationWhenMovingSlowly()
		NavigationServiceTests.testSnappedAtEndOfStepLocationWhenMovingSlowly()
		NavigationServiceTests.testSnappedAtEndOfStepLocationWhenMovingSlowly()
		NavigationServiceTests.testSnappedAtEndOfStepLocationWhenMovingSlowly()
		NavigationServiceTests.testSnappedAtEndOfStepLocationWhenMovingSlowly()
		NavigationServiceTests.testSnappedAtEndOfStepLocationWhenMovingSlowly()
		NavigationServiceTests.testSnappedLocationForUnqualifiedLocation()
		NavigationServiceTests.testSnappedLocationForUnqualifiedLocation()
		NavigationServiceTests.testSnappedLocationForUnqualifiedLocation()
		NavigationServiceTests.testSnappedLocationForUnqualifiedLocation()
		NavigationServiceTests.testSnappedLocationForUnqualifiedLocation()
		NavigationServiceTests.testSnappedLocationForUnqualifiedLocation()
		NavigationServiceTests.testUnimplementedLogging()
		NavigationServiceTests.testUserIsOffRoute()
		NavigationServiceTests.testUserIsOffRoute()
		NavigationServiceTests.testUserIsOnRoute()
		PassiveLocationDataSourceTests.testManualLocations()
```

### PR DESCRIPTION
**Pull request by ShanMa1991**
### Description
This pr is to fix #2913 , to allow the `MapboxCoreNavigationTests` passed with reset of navigator before location update each time.

### Implementation
The tests [failure](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/2950/workflows/920fa868-d1c5-4e45-b33a-a280266b252c/jobs/29227) of `MapboxCoreNavigationTests` , is caused by Navigator single entry point. Every time when the test cases need to update location, they're using the same navigator. So the `navigator.updateLocation` and `navigator.status(at: lastRawLocation.timestamp)` is causing problem in delivering the right location for each teat case running parallel. By adding the `try? Navigator.shared.navigator.resetRideSession()` every time before the location update would reset the navigator and remove the influence of other test cases.

### CODE REVIEW

File: Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift [hunk 1]
```diff
@@ -36,6 +36,7 @@ class MapboxCoreNavigationTests: XCTestCase {
     
     func testNavigationNotificationsInfoDict() {
         navigation = MapboxNavigationService(route: route, routeIndex: 0, routeOptions: routeOptions, directions: directions, simulating: .never)
+        try? Navigator.shared.navigator.resetRideSession()
```
Comment (1ec5) [inline Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift:39]: Would it work to reset the session inside `tearDown()` instead of repeating it for each test?

**Review by 1ec5 — APPROVED** [review]
So nice to see all that green! 🎉

File: Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift (hunk 1 above)
Comment (ShanMa1991) [reply Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift:39]: Yes. I tried to do so. But because the `Navigator.shared.navigator` should be called every time after we set credentials of `Navigator`, through the `MapboxNavigationService`, or `PassiveLocationDataSource` initialization. But inside each test case, the initialization of `MapboxNavigationService` maybe different. So it would be hard to put in the `tearDown()`

Comment (ShanMa1991) [reply Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift:39]: Yes, sure. Thanks for the suggestion. I'll work on it.
