### PR TITLE
Remove the gap between `EndOfRouteViewController` view and screen bottom.

### LINKED ISSUE #3766: [Bug]: The `EndOfRouteViewController` set the view bottom as safe area bottom
Because right now the `EndOfRouteViewController` set the view bottom as the safe area bottom instead of the screen bottom. It also failed to update its height with the 0 `safeAreaInsets`. So there's a gap below the `EndOfRouteViewController` and the mobile screen. 

Because it has a background color the same as the bottom banner, and previously the bottom banner is behind it. We couldn't see the gap. But with the improving of the landscape mode and UI change, the bottom banner is not under the end of route view, then the gap shows up.

### PR DESCRIPTION
**Pull request by ShanMa1991**
### Description
This PR is to fix #3766 by setting the bottom of `EndOfRouteViewController` view to the screen bottom to remove the gap between.

### Implementation
Set the `bottomAnchor` of `EndOfRouteViewController` view to the bottom of `NavigationView` instead of the safeArea's bottom. Fix the `safeAreaInsets` of the `EndOfRouteViewController` view is `0` when its height needs to change.

### Screenshots or Gifs
FixEndView

### CODE REVIEW

File: Sources/MapboxNavigation/EndOfRouteViewController.swift [hunk 1]
```diff
@@ -74,6 +74,10 @@ class EndOfRouteViewController: UIViewController {
         preferredContentSize.height = height(for: .normal)
         updateInterface()
     }
+    
+    override func viewDidLayoutSubviews() {
```
Comment (ShanMa1991) [inline Sources/MapboxNavigation/EndOfRouteViewController.swift:78]: In `height(for:)` the `safeAreaInsets` will have the correct size instead of `0`. It would allow the dynamic change of end of route view height.

Comment (MaximAlien) [reply Sources/MapboxNavigation/EndOfRouteViewController.swift:78]: Please also call `super.viewDidLayoutSubviews()` inside this function.

**Review by MaximAlien — APPROVED** [review]

File: Sources/MapboxNavigation/EndOfRouteViewController.swift (hunk 1 above)
Comment (ShanMa1991) [reply Sources/MapboxNavigation/EndOfRouteViewController.swift:78]: Thanks for the suggestion, I missed that.
