### PR TITLE
Remove dependency on debug build of MapboxDirections

### LINKED ISSUE #1753: MapboxNavigationTests build failure — Module 'MapboxDirections' was not compiled for testing
#1737 and #1740 introduced `@testable` import statements for external libraries, which fails locally in Xcode 10 but somehow not on CI:

https://github.com/mapbox/mapbox-navigation-ios/blob/42b0872b421207d930cf967fc7c3beb1e791f7a7/MapboxNavigationTests/Fixtures/Fixture.swift#L4

```
Swift Compiler Error Group
/path/to/mapbox-navigation-ios/MapboxNavigationTests/Fixtures/Fixture.swift:4:18: Module 'MapboxDirections' was not compiled for testing
/path/to/mapbox-navigation-ios/MapboxNavigationTests/RouteControllerSnapshotTests.swift:6:18: Module 'MapboxDirections' was not compiled for testing
/path/to/mapbox-navigation-ios/MapboxNavigationTests/SimulatedLocationManagerTests.swift:5:18: Module 'MapboxDirections' was not compiled for testing
```

/cc @mapbox/navigation-ios @nitaliano

### PR DESCRIPTION
**Pull request by 1ec5**
~~Stick to MapboxDirections’ public API but stub out Map Matching API access using OHHTTPStubs, the same library that MapboxDirections.swift’s unit tests use.~~ Stick to MapboxDirections’ public API, adapting some internal MapboxDirections code for converting a Map Matching API response to a Route.

Fixes #1753.

/cc @frederoni @JThramer

### CODE REVIEW

**Comment by 1ec5** [comment]
One of the tests crashes in MapboxNavigationNative on CI, but it passes locally for me, which suggests an issue that runs sometime after the code that changed in this PR:

```
Test Case '-[MapboxNavigationTests.SimulatedLocationManagerTests testSimulateRouteDoublesBack]' started.
2018-10-01 22:38:26.260292-0700 Example-Swift[4346:22882] *** Terminating app due to uncaught exception 'Invalid last_traversable_step banner count', reason: 'Invalid last_traversable_step banner count'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f2c21e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010b5c1031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f337975 +[NSException raise:format:] + 197
	3   MapboxNavigationNative              0x0000000109cae32b -[MBNavigator getStatusForTimestamp:] + 491
	4   MapboxCoreNavigation                0x000000010e159fe7 _T020MapboxCoreNavigation23PortableRouteControllerC020userIsWithinRadiusOfE0SbSo10CLLocationC8location_tF + 167
	5   MapboxCoreNavigation                0x000000010e145e85 _T020MapboxCoreNavigation15RouteControllerC08userIsOnD0SbSo10CLLocationCF + 1093
	6   MapboxCoreNavigation                0x000000010e1475b0 _T020MapboxCoreNavigation15RouteControllerC15locationManagerySo010CLLocationG0C_SaySo0H0CG18didUpdateLocationstF + 2736
	7   MapboxCoreNavigation                0x000000010e14c6f1 _T020MapboxCoreNavigation15RouteControllerC15locationManagerySo010CLLocationG0C_SaySo0H0CG18didUpdateLocationstFTo + 97
	8   MapboxCoreNavigation                0x000000010e159c46 _T020MapboxCoreNavigation23PortableRouteControllerC15locationManagerySo010CLLocationH0C_SaySo0I0CG18didUpdateLocationstF + 342
	9   MapboxCoreNavigation                0x000000010e159f21 _T020MapboxCoreNavigation23PortableRouteControllerC15locationManagerySo010CLLocationH0C_SaySo0I0CG18didUpdateLocationstFTo + 97
	10  MapboxCoreNavigation                0x000000010e1649b0 _T0Ta.35 + 48
	11  MapboxCoreNavigation                0x000000010e13f230 _T0So17CLLocationManagerCSo7NSArrayCIegyy_ABSaySo0A0CGIegxx_TR + 64
	12  MapboxCoreNavigation                0x000000010e164a11 _T0So17CLLocationManagerCSo7NSArrayCIegyy_ABSaySo0A0CGIegxx_TRTA + 17
	13  MapboxCoreNavigation                0x000000010e161b6d _T020MapboxCoreNavigation0aC7ServiceC15locationManagerySo010CLLocationF0C_SaySo0G0CG18didUpdateLocationstF + 2157
	14  MapboxCoreNavigation                0x000000010e161e51 _T020MapboxCoreNavigation0aC7ServiceC15locationManagerySo010CLLocationF0C_SaySo0G0CG18didUpdateLocationstFTo + 97
	15  MapboxCoreNavigation                0x000000010e16dce0 _T0Ta + 48
	16  MapboxCoreNavigation                0x000000010e13f230 _T0So17CLLocationManagerCSo7NSArrayCIegyy_ABSaySo0A0CGIegxx_TR + 64
	17  MapboxCoreNavigation                0x000000010e16dd41 _T0So17CLLocationManagerCSo7NSArrayCIegyy_ABSaySo0A0CGIegxx_TRTA + 17
	18  MapboxCoreNavigation                0x000000010e16d2c9 _T020MapboxCoreNavigation24SimulatedLocationManagerC4tickyyF + 7097
	19  MapboxCoreNavigation                0x000000010e16e8ec _T0TA + 28
	20  MapboxCoreNavigation                0x000000010e115c3d _T0Ieg_IeyB_TR + 45
	21  libdispatch.dylib                   0x0000000111b7d6cb _dispatch_call_block_and_release + 12
	22  libdispatch.dylib                   0x0000000111b7e709 _dispatch_client_callout + 8
	23  libdispatch.dylib                   0x0000000111b88708 _dispatch_main_queue_callback_4CF + 1279
	24  CoreFoundation                      0x000000010f284c99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	25  CoreFoundation                      0x000000010f248ea6 __CFRunLoopRun + 2342
	26  CoreFoundation                      0x000000010f24830b CFRunLoopRunSpecific + 635
	27  XCTest                              0x0000000121c3103a -[XCTWaiter waitForExpectations:timeout:enforceOrder:] + 742
	28  XCTest                              0x0000000121bcab66 -[XCTestCase(AsynchronousTesting) waitForExpectations:timeout:enforceOrder:] + 108
	29  MapboxNavigationTests               0x00000001237f2db8 _T021MapboxNavigationTests024SimulatedLocationManagerC0C28testSimulateRouteDoublesBackyyF + 648
	30  MapboxNavigationTests               0x00000001237f39d4 _T021MapboxNavigationTests024SimulatedLocationManagerC0C28testSimulateRouteDoublesBackyyFTo + 36
```

File: MapboxNavigationTests/SimulatedLocationManagerTests.swift [hunk 1]
```diff
@@ -13,7 +13,15 @@ class SimulatedLocationManagerTests: FBSnapshotTestCase {
...
     func testSimulateRouteDoublesBack() {
-        let route = Fixture.routesFromMatches(at: "sthlm-double-back")![0]
+        let routeExpectation = expectation(description: "Gets a matching route")
+        var route: Route!
+        Fixture.getRoutesFromMatches(at: "sthlm-double-back") { (waypoints, routes, error) in
+            route = routes?[0]
+            routeExpectation.fulfill()
+        }
+        wait(for: [routeExpectation], timeout: 1)
+        guard route != nil else { return }
```
Comment (akitchen) [inline MapboxNavigationTests/SimulatedLocationManagerTests.swift]: Shouldn't we fail the test if this guard fails?

File: MapboxNavigationTests/RouteControllerSnapshotTests.swift [hunk 2]
```diff
@@ -22,13 +22,20 @@ class RouteControllerSnapshotTests: FBSnapshotTestCase {
...
     func testRouteSnappingOvershooting() {
-        let route = Fixture.routesFromMatches(at: "sthlm-double-back")![0]
+        let routeExpectation = expectation(description: "Gets a matching route")
+        var route: Route!
+        Fixture.getRoutesFromMatches(at: "sthlm-double-back") { (waypoints, routes, error) in
+            route = routes?[0]
+            routeExpectation.fulfill()
+        }
+        wait(for: [routeExpectation], timeout: 1)
+        guard route != nil else { return }
```
Comment (akitchen) [inline MapboxNavigationTests/RouteControllerSnapshotTests.swift]: Is this guard really needed? If it fails, should the test fail too?

**Comment by akitchen** [comment]
I like the idea of removing the `@testable import` and using a `URLProtocol`-based abstraction for testing URL loading, but I'm less thrilled about round-tripping through `URLProtocol` for getting domain object fixtures. In other words, I don't think we should need to use URL loading for our fixtures at all.

File: MapboxNavigationTests/RouteControllerSnapshotTests.swift (hunk 2 above)
Comment (1ec5) [reply MapboxNavigationTests/RouteControllerSnapshotTests.swift]: The test will already fail if there’s no `route`, because the expectation will fail to be fulfilled. I prefer to minimize cascading test failures to avoid obscuring the original failure.

File: MapboxNavigationTests/SimulatedLocationManagerTests.swift (hunk 1 above)
Comment (1ec5) [reply MapboxNavigationTests/SimulatedLocationManagerTests.swift]: As above, the test will fail due to an unfulfilled expectation. The guard is needed here to keep the test failure from becoming a test crash, which is more difficult to diagnose in CI logs.

**Comment by 1ec5** [comment]
> I'm less thrilled about round-tripping through `URLProtocol` for getting domain object fixtures. In other words, I don't think we should need to use URL loading for our fixtures at all.

The reason this test (and test helper) originally used `@testable` was that MapboxDirections.swift doesn’t expose `MatchOptions.response(containingRoutesFrom:)` or `MatchOptions.response(from:)` publicly.

`Fixture.getRoutesFromMatches(at:completionHandler:)` attempts to go all the way from a Map Matching API request to a Route object. To avoid stubbing the API response, we’d need to scope down this method to start from the response in JSON format and initialize the Route object using `Route(json:waypoints:options:)`.

**Comment by 1ec5** [comment]
> To avoid stubbing the API response, we’d need to scope down this method to start from the response in JSON format and initialize the Route object using `Route(json:waypoints:options:)`.

cb319579e773e98240626388da4922bf221c0d24 pares back the fixture-loading method, so the dependency on OHHTTPStubs has been removed.
