### PR TITLE
Fix auto-hiding status view

### LINKED ISSUE #2180: Device Volume Low status not disappearing
**Mapbox Navigation SDK version: 0.35.0**

After starting navigation with low volume a status is presented but it's not hidden after 3s.
It can disappear only if replaced with "Rerouting..." status.

Root cause:
`isCurrentlyVisible` flag in StatusView.swift is set to true only after `show()` animation is completed but `hide()` checks this flag before scheduling its animation when show animation is ongoing

I can suggest moving line 179 (guard) into the beginning of dispatch async body.

### PR DESCRIPTION
**Pull request by 1ec5**
Fixed an issue where the “iPhone Volume Low” banner would persist until replaced by another banner about simulation or rerouting. Also expanded some code golf.

Fixes #2180. Thanks to @imaginaris for the fix!

/cc @JThramer

### CODE REVIEW

File: MapboxNavigation/StatusView.swift [hunk 1]
```diff
@@ -176,17 +176,21 @@ public class StatusView: UIControl {
...
                 })
             })
         }
         
-        animated ? animate() : hide()
+        if animated {
+            animate()
+        } else {
+            hide()
+        }
```
Comment (JThramer) [inline MapboxNavigation/StatusView.swift]: Sad doctor strange.
