### PR TITLE
Avoid manual index arithmetic

### LINKED ISSUE #2611: Crash when arriving at intermediate waypoint
Example app crashed while simulating navigation on an iPhone 10. This happened while approaching the first maneuver.

This seems to only affect this route.

Origin:
CLLocationCoordinate2D(latitude: 45.514850964102656, longitude: -122.6033354827087)
Waypoint 1:
CLLocationCoordinate2D(latitude: 45.516455182137776, longitude: -122.60103919233336)
Waypoint 2:
CLLocationCoordinate2D(latitude: 45.51960683483267, longitude: -122.60004019263819)

```
2020-09-08 12:00:38.971596-0700 Example[16475:5677110] Fatal error: Index out of range: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1103.2.25.13/swift/stdlib/public/core/ContiguousArrayBuffer.swift, line 444

Backtrace:
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Index out of range
    frame #0: 0x00000001a3e86ec0 libswiftCore.dylib`_swift_runtime_on_report
    frame #1: 0x00000001a3eeed40 libswiftCore.dylib`_swift_stdlib_reportFatalErrorInFile + 188
    frame #2: 0x00000001a3bebca0 libswiftCore.dylib`closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in Swift._assertionFailure(_: Swift.StaticString, _: Swift.StaticString, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never + 452
    frame #3: 0x00000001a3beb164 libswiftCore.dylib`Swift._assertionFailure(_: Swift.StaticString, _: Swift.StaticString, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never + 468
    frame #4: 0x00000001a3bc9e00 libswiftCore.dylib`Swift._ArrayBuffer._checkInoutAndNativeTypeCheckedBounds(_: Swift.Int, wasNativeTypeChecked: Swift.Bool) -> () + 208
    frame #5: 0x00000001a3bcd9f8 libswiftCore.dylib`Swift.Array.subscript.getter : (Swift.Int) -> A + 84
  * frame #6: 0x0000000102a9a6c0 MapboxNavigation`NavigationMapView.combine(coordinates=12 values, congestions=12 values, self=0x00000001560fc000) at NavigationMapView.swift:1173:115
    frame #7: 0x0000000102a99264 MapboxNavigation`NavigationMapView.addCongestion(route=0x00000002822526f0, legIndex=0, self=0x00000001560fc000) at NavigationMapView.swift:1142:48
    frame #8: 0x0000000102a8d424 MapboxNavigation`NavigationMapView.routeLineGradient(route=0x00000002822526f0, fractionTraveled=0, self=0x00000001560fc000) at NavigationMapView.swift:707:44
    frame #9: 0x0000000102a88d5c MapboxNavigation`NavigationMapView.show(routes=1 value, legIndex=0, self=0x00000001560fc000) at NavigationMapView.swift:479:94
    frame #10: 0x0000000102ac28dc MapboxNavigation`RouteMapViewController.navigationService(service=0x0000000282249ab0, routeProgress=0x0000000282d60180, self=0x00000001564a3000) at RouteMapViewController.swift:537:17
    frame #11: 0x0000000102ac2a10 MapboxNavigation`protocol witness for NavigationServiceDelegate.navigationService(_:didRefresh:) in conformance RouteMapViewController at <compiler-generated>:0
    frame #12: 0x0000000102a5e3c4 MapboxNavigation`NavigationViewController.navigationService(service=0x0000000282249ab0, routeProgress=0x0000000282d60180, self=0x0000000156d35c00) at NavigationViewController.swift:547:23
    frame #13: 0x0000000102a62938 MapboxNavigation`protocol witness for NavigationServiceDelegate.navigationService(_:didRefresh:) in conformance NavigationViewController at <compiler-generated>:0
    frame #14: 0x00000001095b7994 MapboxCoreNavigation`MapboxNavigationService.router(router=0x0000000283c0a640, routeProgress=0x0000000282d60180, self=0x0000000282249ab0) at NavigationService.swift:452:19
    frame #15: 0x00000001095b8f8c MapboxCoreNavigation`protocol witness for RouterDelegate.router(_:didRefresh:) in conformance MapboxNavigationService at <compiler-generated>:0
    frame #16: 0x000000010955ad40 MapboxCoreNavigation`closure #1 in InternalRouter<>.refreshRoute(session=MapboxDirections.DirectionsCredentials @ 0x00000002809a8748, result=<invalid> (0x0), self=0x0000000283c0a640, completion=0x0000000109559f64 MapboxCoreNavigation`partial apply forwarder for closure #1 () -> () in (extension in MapboxCoreNavigation):MapboxCoreNavigation.InternalRouter< where A: MapboxCoreNavigation.Router>.refreshAndCheckForFasterRoute(from: __C.CLLocation, routeProgress: MapboxCoreNavigation.RouteProgress) -> () at <compiler-generated>) at Router.swift:171:34
    frame #17: 0x0000000106401818 MapboxDirections`merged closure #2 () -> () in closure #4 () -> () in closure #1 (Swift.Optional<Foundation.Data>, Swift.Optional<__C.NSURLResponse>, Swift.Optional<Swift.Error>) -> () in MapboxDirections.Directions.refreshRoute(responseIdentifier: Swift.String, routeIndex: Swift.Int, fromLegAtIndex: Swift.Int, completionHandler: (MapboxDirections.DirectionsCredentials, Swift.Result<MapboxDirections.RouteRefreshResponse, MapboxDirections.DirectionsError>) -> ()) -> Swift.Optional<__C.NSURLSessionDataTask> + 152
    frame #18: 0x00000001064041c4 MapboxDirections`merged partial apply forwarder for closure #3 () -> () in closure #4 () -> () in closure #1 (Swift.Optional<Foundation.Data>, Swift.Optional<__C.NSURLResponse>, Swift.Optional<Swift.Error>) -> () in MapboxDirections.Directions.refreshRoute(responseIdentifier: Swift.String, routeIndex: Swift.Int, fromLegAtIndex: Swift.Int, completionHandler: (MapboxDirections.DirectionsCredentials, Swift.Result<MapboxDirections.RouteRefreshResponse, MapboxDirections.DirectionsError>) -> ()) -> Swift.Optional<__C.NSURLSessionDataTask> + 32
    frame #19: 0x00000001063fb458 MapboxDirections`thunk for @escaping @callee_guaranteed () -> () at <compiler-generated>:0 [opt]
    frame #20: 0x0000000109786338 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #21: 0x0000000109787730 libdispatch.dylib`_dispatch_client_callout + 16
    frame #22: 0x0000000109795710 libdispatch.dylib`_dispatch_main_queue_callback_4CF + 976
    frame #23: 0x00000001966976bc CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
    frame #24: 0x0000000196692590 CoreFoundation`__CFRunLoopRun + 1724
    frame #25: 0x0000000196691ba8 CoreFoundation`CFRunLoopRunSpecific + 424
    frame #26: 0x00000001a0801344 GraphicsServices`GSEventRunModal + 160
    frame #27: 0x000000019a7cd3e4 UIKitCore`UIApplicationMain + 1932
    frame #28: 0x0000000102683370 Example`main at AppDelegate.swift:5:7
    frame #29: 0x00000001965198f0 libdyld.dylib`start + 4
```

### PR DESCRIPTION
**Pull request by 1ec5**
Hardened the traffic congestion coalescing code against situations where the Directions API returns fewer coordinates or more congestion attributes than expected.

Fixes #2611.

/cc @mapbox/navigation-ios

### CODE REVIEW

File: MapboxNavigation/NavigationMapView.swift [hunk 1]
```diff
@@ -1166,18 +1166,23 @@ open class NavigationMapView: MGLMapView, UIGestureRecognizerDelegate {
...
-            let congestionLevel = congestionSegment.1
-            
+        for (firstSegment, congestionLevel) in zip(zip(coordinates, coordinates.suffix(from: 1)), congestions) {
+            let coordinates = [firstSegment.0, firstSegment.1]
             if segments.last?.1 == congestionLevel {
                 segments[segments.count - 1].0 += coordinates
             } else {
-                segments.append(congestionSegment)
+                segments.append((coordinates, congestionLevel))
             }
```
Comment (1ec5) [inline MapboxNavigation/NavigationMapView.swift:1186]: Can you think of a more elegant way to group elements of an array that are alike, similar to a SQL `GROUP BY` clause?

**Review by Udumft — APPROVED** [review]

**Comment by 1ec5** [comment]
Cherry-picked into the release-v1.0 branch as 4fe6762f1e47c54ca6dd23f30b4d34a0ce20c41c.

File: MapboxNavigation/NavigationMapView.swift (hunk 1 above)
Comment (1ec5) [reply MapboxNavigation/NavigationMapView.swift:1186]: [Swift Algorithms](https://swift.org/blog/swift-algorithms/) has a `Collection.chunked(by:)` method that implements this algorithm functionally.
