### PR TITLE
Add lane guidance to CarPlay. Fix incorrect coloring of dual-use lane icons

### LINKED ISSUE #2796: Dual-use lane icons are highlighted incorrectly
In the lane view that appears below the turn banner, the icon for a dual use lane – a lane that can be used for multiple maneuvers – is highlighted incorrectly.

## Problem

If the user is supposed to continue straight at an intersection and one of the lanes can be used for going straight or turning right, the lane icon is highlighted as if the user is supposed to turn right from that lane.

## Diagnosis

6dc222c618602561504378a2be790d2dc2d840d5 for #1514 removed the ability for LaneView to know the corresponding step’s maneuver direction. Instead, the drawing code takes the maneuver direction from the lane’s own turn indications. If a turn lane can be used for two different maneuvers, then LaneView tries to convert the JSON representation of the array of maneuvers into a ManeuverDirection, which fails. The resulting `nil` value causes us to fall back to a code path that, by process of elimination, is implicitly meant for highlighting the right turn maneuver on a straight-right lane:

https://github.com/mapbox/mapbox-navigation-ios/blob/b6d3a3acbd7c67f75878e7b6a7905a64c41211ad/MapboxNavigation/LaneView.swift#L84 https://github.com/mapbox/mapbox-navigation-ios/blob/b6d3a3acbd7c67f75878e7b6a7905a64c41211ad/MapboxNavigation/LaneView.swift#L126-L128

## Solution

We need to restore the `direction` argument that 6dc222c618602561504378a2be790d2dc2d840d5 removed from LaneView’s initializer and populate it with the step’s maneuver. Because the step went unused after this change, LanesView’s ability to pass in a step also atrophied. We‘ll also need to add a `direction` argument to `LanesView.update(for:)`, to be populated by the upcoming step.

This issue went unnoticed for a long time because of a sprawling nest of conditionals with implicit fallbacks and no assertions. We should take this opportunity to reorganize `LaneView.draw(_:)` with a pattern-matching `switch` statement on a tuple that combines `indications` with `maneuverDirection`.

/cc @mapbox/navigation-ios @avi-c @abhishek1508

### PR DESCRIPTION
**Pull request by avi-c**
### Description

Add support for visual lane guidance instructions in CarPlay. Addresses #1885 
Fix regression that occurred during Swift migration whereby dual use lane icons were not correctly indicating which direction to follow. Fixes #2796  

### Implementation
I used a slightly different approach for adding the Lane views than that which is outlines in #1885. Instead of drawing a snapshot of the `LanesView`, I instead form my own new lane image out of images of each lane.

For the lane coloring, I altered how the lanes are colored to use the Appearance proxy mechanism for the various colors. It no longer hardcodes that `invalid` or unusable lanes are colored with an alpha of 0.4. Instead they use whatever color is specified in the appearance proxy for the LaneView. This gives the client app more control over the visual appearance.

### Screenshots or Gifs
Simulator Screen Shot - iPhone 11 - 2021-02-04 at 15 08 58
Simulator Screen Shot - iPhone 11 - 2021-02-04 at 15 09 00

Simulator Screen Shot - iPhone 11 - 2021-02-04 at 15 14 33
Simulator Screen Shot - iPhone 11 - 2021-02-04 at 15 14 38

### CODE REVIEW

File: Sources/MapboxNavigation/UIImage.swift [hunk 1]
```diff
@@ -33,4 +33,14 @@ extension UIImage {
             (text as NSString).draw(in: rect.offsetBy(dx: 0, dy: (constrainedSize.height - font.lineHeight) / 2).integral, withAttributes: textFontAttributes)
         }
     }
+
+    func scaled(_ size: CGSize) -> UIImage? {
```
Comment (1ec5) [inline Sources/MapboxNavigation/UIImage.swift:37]: Nit: `scaled(to:)` reads more naturally.

File: Sources/MapboxNavigation/UIView.swift [hunk 2]
```diff
@@ -117,7 +117,7 @@ extension UIView {
     
     var imageRepresentation: UIImage? {
         let size = CGSize(width: frame.size.width, height: frame.size.height)
-        UIGraphicsBeginImageContextWithOptions(size, false, UIScreen.main.scale)
+        UIGraphicsBeginImageContextWithOptions(size, false, (window?.screen ?? UIScreen.main).scale)
```
Comment (1ec5) [inline Sources/MapboxNavigation/UIView.swift:120]: I’m glad something in #1885 ended up being relevant still. 😄

File: Tests/MapboxNavigationTests/LaneTests.swift [hunk 3]
```diff
@@ -31,7 +31,7 @@ class LaneTests: FBSnapshotTestCase {
                 let groupView = UIStackView(orientation: .vertical, autoLayout: true)
                 groupView.alignment = .center
                 
-                let laneView = LaneView(indications: lane.indications, isUsable: true)
+                let laneView = LaneView(indications: lane.indications, isUsable: true, direction: ManeuverDirection(rawValue: lane.indications.description))
```
Comment (1ec5) [inline Tests/MapboxNavigationTests/LaneTests.swift:34]: It’s incorrect to create a `ManeuverDirection` from a `LaneIndications.description`. The description could be a comma-separated list.

File: Sources/MapboxNavigation/CarPlayNavigationViewController.swift [hunk 4]
```diff
@@ -433,25 +433,71 @@ public class CarPlayNavigationViewController: UIViewController, NavigationMapVie
...
+                var darkLanesImage = tertiaryInstruction.lanesImage(side: visualInstruction.drivingSide, direction: visualInstruction.primaryInstruction.maneuverDirection, useableColor: darkUseableColor, unuseableColor: darkUnuseableColor, size: CGSize(width: CGFloat(tertiaryInstruction.laneComponents.count) * lanesImageMaxSize.height, height: lanesImageMaxSize.height), scale: (carPlayManager.carWindow?.screen ?? UIScreen.main).scale)
+
+                if let image = lightLanesImage, let darkImage = darkLanesImage, image.size.width > lanesImageMaxSize.width {
+                    let aspectRatio = lanesImageMaxSize.width / image.size.width
+                    let scaledSize = CGSize(width: lanesImageMaxSize.width, height: lanesImageMaxSize.height * aspectRatio)
+                    lightLanesImage = image.scaled(scaledSize)
+                    darkLanesImage = darkImage.scaled(scaledSize)
+                }
+                if let image = lightLanesImage, let darkImage = darkLanesImage {
+                    tertiaryManeuver.symbolSet = CPImageSet(lightContentImage: image, darkContentImage: darkImage)
```
Comment (1ec5) [inline Sources/MapboxNavigation/CarPlayNavigationViewController.swift:479]: #1885 pushed the logic for combining images into an image set down into the extension on VisualInstructionBanner, which seemed to make the code a bit cleaner. Something to consider, but this does appear to work.

**Review by 1ec5 — COMMENTED** [review]
In addition to the feedback below, please add a changelog entry. You can use the entry that was in #1885.

File: Sources/MapboxNavigation/LaneView.swift [hunk 5]
```diff
@@ -110,11 +108,10 @@ open class LaneView: UIView {
             if indications.isSuperset(of: [.straightAhead, .sharpRight]) || indications.isSuperset(of: [.straightAhead, .right]) || indications.isSuperset(of: [.straightAhead, .slightRight]) {
                 if !isValid {
                     if indications == .slightRight {
-                        LanesStyleKit.drawLaneSlightRight(frame: bounds, resizing: resizing, primaryColor: appropriatePrimaryColor)
+                        LanesStyleKit.drawLaneSlightRight(frame: bounds, resizing: resizing, primaryColor: appropriateSecondaryColor)
                     } else {
-                        LanesStyleKit.drawLaneStraightRight(frame: bounds, resizing: resizing, primaryColor: appropriatePrimaryColor)
+                        LanesStyleKit.drawLaneStraightRight(frame: bounds, resizing: resizing, primaryColor: appropriateSecondaryColor)
```
[the remark this answers is not in the document]
Comment (avi-c) [reply Sources/MapboxNavigation/LaneView.swift:113]: Exactly. While there are still some issues to address with non-opaque colors, I think it's best to give the client apps control over the color and alpha using regular appearance proxy color properties.

File: Sources/MapboxNavigation/DayStyle.swift [hunk 6]
```diff
@@ -13,11 +13,14 @@ extension UIColor {
...
     class var defaultTurnArrowSecondaryHighlighted: UIColor { get { return UIColor.white.withAlphaComponent(0.4) } }
-    
+
     class var defaultLaneArrowPrimary: UIColor { get { return #colorLiteral(red: 0, green: 0, blue: 0, alpha: 1) } }
     class var defaultLaneArrowSecondary: UIColor { get { return #colorLiteral(red: 0.6196078431, green: 0.6196078431, blue: 0.6196078431, alpha: 1) } }
     class var defaultLaneArrowPrimaryHighlighted: UIColor { get { return #colorLiteral(red: 1, green: 1, blue: 1, alpha: 1) } }
-    class var defaultLaneArrowSecondaryHighlighted: UIColor { get { return #colorLiteral(red: 1, green: 1, blue: 1, alpha: 1) } }
+    class var defaultLaneArrowSecondaryHighlighted: UIColor { get { return #colorLiteral(red: 0.501960814, green: 0.501960814, blue: 0.501960814, alpha: 1) } }
+
+    class var defaultLaneArrowPrimaryCarPlay: UIColor { get { return #colorLiteral(red: 0.7649999857, green: 0.7649999857, blue: 0.7570000291, alpha: 1) } }
```
[the remark this answers is not in the document]
Comment (avi-c) [reply Sources/MapboxNavigation/DayStyle.swift:22]: You are right. I'm reverting this as it was also something I changed earlier on to try and change the CarPlay colors before I realized that ti was better just to have specific colors for that trait class anyway.

File: Sources/MapboxNavigation/LaneView.swift [hunk 7]
```diff
@@ -124,25 +121,29 @@ open class LaneView: UIView {
                         LanesStyleKit.drawLaneRight(frame: bounds, resizing: resizing, primaryColor: appropriatePrimaryColor, flipHorizontally: true)
                     }
                 } else {
-                    LanesStyleKit.drawLaneRightOnly(frame: bounds, resizing: resizing, primaryColor: appropriatePrimaryColor, secondaryColor: appropriateSecondaryColor)
+                    // pick the color of the two parts (straight & turn) depending on which direction is being suggested
+                    let turnArrowColor = (self.maneuverDirection != ManeuverDirection.straightAhead) ? appropriatePrimaryColor : appropriateSecondaryColor
+                    let straightArrowColor = (self.maneuverDirection == ManeuverDirection.straightAhead) ? appropriatePrimaryColor : appropriateSecondaryColor
```
[the remark this answers is not in the document]
Comment (avi-c) [reply Sources/MapboxNavigation/LaneView.swift:126]: Done.

File: Tests/MapboxNavigationTests/LaneTests.swift (hunk 3 above)
Comment (avi-c) [reply Tests/MapboxNavigationTests/LaneTests.swift:34]: Added specific maneuver direction to TestableLane struct.

File: Sources/MapboxNavigation/UIImage.swift (hunk 1 above)
Comment (avi-c) [reply Sources/MapboxNavigation/UIImage.swift:37]: Done.

File: Sources/MapboxNavigation/CarPlayNavigationViewController.swift [hunk 8]
```diff
@@ -433,25 +433,71 @@ public class CarPlayNavigationViewController: UIViewController, NavigationMapVie
...
-                let attributedTertiary = NSMutableAttributedString(attributedString: attributedTertiary)
-                attributedTertiary.canonicalizeAttachments(maximumImageSize: maximumImageSize, imageRendererFormat: imageRendererFormat)
-                tertiaryManeuver.attributedInstructionVariants = [attributedTertiary]
+            if tertiaryInstruction.containsLaneIndications {
+                // create lanes visual banner
+                // The `lanesImageMaxSize` size is an estimate of the CarPlay Lane Configuration View
+                // The dimensions are specified in the CarPlay App Programming Guide - https://developer.apple.com/carplay/documentation/CarPlay-App-Programming-Guide.pdf
+                let lanesImageMaxSize = CGSize(width: 120, height: 18)
+
+                let lightUseableColor: UIColor
```
[the remark this answers is not in the document]
Comment (avi-c) [reply Sources/MapboxNavigation/CarPlayNavigationViewController.swift:445]: Done.

File: CHANGELOG.md [hunk 9]
```diff
@@ -4,6 +4,8 @@
 
 * Increased the minimum versions of `MapboxNavigationNative` to v30.0 and `MapboxCommon` to v9.2.0. ([#2793](https://github.com/mapbox/mapbox-navigation-ios/pull/2793))
 * Fixed an issue that caused the App Store to reject some application submissions with error ITMS-90338. ([#2793](https://github.com/mapbox/mapbox-navigation-ios/pull/2793))
+* The CarPlay guidance panel now shows lane guidance. ([#1885](https://github.com/mapbox/mapbox-navigation-ios/pull/1885))
+* Fixed an issue where lane guidance icons would indicate the wrong arrow for certain maneuvers. ([#2796](https://github.com/mapbox/mapbox-navigation-ios/pull/2796))
```
Comment (1ec5) [inline CHANGELOG.md:8]: v1.2.1 has already been released. If you rebase atop main, there’s a new v1.3.0 section that these changes can go in. (Technically I should’ve called it “main” but v1.3.0 is probably where this change would end up.)

File: Sources/MapboxNavigation/VisualInstruction.swift [hunk 10]
```diff
@@ -121,5 +121,52 @@ extension VisualInstruction {
         
         return instructionLabel.attributedText
     }
+
+    /// Returns a `CPImageSet` representing the maneuver lane configuration.
+    @available(iOS 12.0, *)
+    public func lanesImageSet(side: DrivingSide, direction: ManeuverDirection?, scale: CGFloat)  -> CPImageSet? {
+        // create lanes visual banner
+        // The `lanesImageMaxSize` size is an estimate of the CarPlay Lane Configuration View
+        // The dimensions are specified in the CarPlay App Programming Guide - https://developer.apple.com/carplay/documentation/CarPlay-App-Programming-Guide.pdf
```
Comment (1ec5) [inline Sources/MapboxNavigation/VisualInstruction.swift:130]: Link to the specific page for convenience:

https://developer.apple.com/carplay/documentation/CarPlay-App-Programming-Guide.pdf#page=38

**Review by 1ec5 — APPROVED** [review]
This will be ready to merge once the colors are adjusted per https://github.com/mapbox/mapbox-navigation-ios/pull/2798#discussion_r571345846 and the minor feedback below is addressed. If you decide to stick with the changes mentioned in https://github.com/mapbox/mapbox-navigation-ios/pull/2798#discussion_r571343386, then I’ll need to redo the changes in navigation-ui-resources and reapply the exported code here as tail work.

File: CHANGELOG.md (hunk 9 above)
Comment (avi-c) [reply CHANGELOG.md]: Rebased the PR and moved the changelog entry.

File: Sources/MapboxNavigation/VisualInstruction.swift (hunk 10 above)
Comment (avi-c) [reply Sources/MapboxNavigation/VisualInstruction.swift]: Done.

File: CHANGELOG.md (hunk 9 above)
Comment (avi-c) [reply CHANGELOG.md]: Also I reverted the change of the method parameter names. No real need to change it if it's from the PaintCode generated code.
