### PR TITLE
Fixes following camera bottom padding calculation

### LINKED ISSUE #3677: [Bug]: Map is not centered on the user location when the navigation UI is embedded in a small view
### Mapbox Navigation SDK version

2.0.1

### Steps to reproduce

Start navigation to a point and embed `NavigationViewController` into a small view (half height of the screen).

This is a screenshot of the modified `MapboxNavigation-SPM`.
NavigationNotCentered

A suggested fix is to use the map view size (`mapView.bounds.height`) instead of the screen size (`UIScreen.main.bounds.height`) when updating the camera [here](https://github.com/mapbox/mapbox-navigation-ios/blob/v2.0.1/Sources/MapboxNavigation/NavigationViewportDataSource.swift#L308).

### Expected behavior

The navigation view is being centered by the user location.

### Actual behavior

The navigation view is NOT being centered by the user location.

### Is this a one-time issue or a repeatable issue?

repeatable

### PR DESCRIPTION
**Pull request by S2Ler**
### Description

Fixes #3677, NAVIOS-439. Thanks to @dmitry-yashkin for the suggested fix.

### CODE REVIEW

**Review by Udumft — APPROVED** [review]

File: Sources/MapboxNavigation/NavigationViewportDataSource.swift [hunk 1]
```diff
@@ -345,7 +345,7 @@ public class NavigationViewportDataSource: ViewportDataSource {
             if options.followingCameraOptions.paddingUpdatesAllowed || followingMobileCamera.padding == nil {
                 followingMobileCamera.padding = UIEdgeInsets(top: followingMobileCameraAnchor.y,
                                                              left: viewportPadding.left,
-                                                             bottom: UIScreen.main.bounds.height - followingMobileCameraAnchor.y + 1.0,
+                                                             bottom: mapView.bounds.height - followingMobileCameraAnchor.y + 1.0,
```
Comment (kried) [inline Sources/MapboxNavigation/NavigationViewportDataSource.swift:348]: Do we need to apply the same fix for CarPlay on line 354?
```mainCarPlayScreen.bounds.height```
I'm wondering if a mapView can take only a part of a screen on CarPlay.

**Review by kried — APPROVED** [review]
