### PR TITLE
Car Play Quick Fixes: Data Race Bug

### LINKED ISSUE #2035: Redundant NavigationViewController presented when CarPlay is connected
If an application programmatically begins navigation on CarPlay by calling `CarPlayManager.beginNavigationWithCarPlay(using:navigationService:)` while presenting a NavigationViewController on the phone, as the CarPlay example application demonstrates, the application ends up with two redundant NavigationViewControllers. Even after patching the application to avoid the second part of #2034, the NavigationViewControllers share a single MapboxNavigationService, but they still have their own separate MapboxVoiceControllers, resulting in an echo.

`AppDelegate.carPlayManager(_:didBeginNavigationWith:)` calls `NavigationViewController.carPlayManager(_:didBeginNavigationWith:window:)` for the case where the user began navigation on CarPlay.

https://github.com/mapbox/mapbox-navigation-ios/blob/5c4d2973cf27754e06bc3b899d4bc9afb158cd17/Example/AppDelegate+CarPlay.swift#L60

Indeed, `NavigationViewController.carPlayManager(_:didBeginNavigationWith:window:)` twice checks whether there’s a NavigationViewController already on the stack and creates a new NavigationViewController if there isn’t:

https://github.com/mapbox/mapbox-navigation-ios/blob/5c4d2973cf27754e06bc3b899d4bc9afb158cd17/MapboxNavigation/NavigationViewController.swift#L345-L346

The topmost view controller is forced to present this redundant NavigationViewController, just before the application’s view controller presents its NavigationViewController. If the application’s view controller lies inside some other view controller, such as a UINavigationController, then both may be present simultaneously.

```
#0	0x00000001025dec58 in RouteVoiceController.observeNotifications(by:) at /path/to/mapbox-navigation-ios/MapboxNavigation/RouteVoiceController.swift:120
#1	0x00000001025ddfac in RouteVoiceController.init(navigationService:) at /path/to/mapbox-navigation-ios/MapboxNavigation/RouteVoiceController.swift:96
#2	0x00000001026f6c08 in MapboxVoiceController.init(navigationService:speechClient:dataCache:audioPlayerType:) at /path/to/mapbox-navigation-ios/MapboxNavigation/MapboxVoiceController.swift:44
#3	0x00000001026f67a0 in MapboxVoiceController.__allocating_init(navigationService:speechClient:dataCache:audioPlayerType:) ()
#4	0x00000001025ed554 in NavigationViewController.init(for:options:) at /path/to/mapbox-navigation-ios/MapboxNavigation/NavigationViewController.swift:215
#5	0x00000001025ec9a8 in NavigationViewController.__allocating_init(for:options:) ()
#6	0x00000001025f05e4 in static NavigationViewController.carPlayManager(_:didBeginNavigationWith:window:) at /path/to/mapbox-navigation-ios/MapboxNavigation/NavigationViewController.swift:353
#7	0x00000001021ae150 in AppDelegate.carPlayManager(_:didBeginNavigationWith:) at /path/to/mapbox-navigation-ios/Example/AppDelegate+CarPlay.swift:60
#8	0x00000001021ae1d0 in @objc AppDelegate.carPlayManager(_:didBeginNavigationWith:) ()
#9	0x00000001026a63b4 in CarPlayManager.mapTemplate(_:startedTrip:using:navigationService:) at /path/to/mapbox-navigation-ios/MapboxNavigation/CarPlayManager.swift:543
#10	0x00000001026a5908 in CarPlayManager.beginNavigationWithCarPlay(using:navigationService:) at /path/to/mapbox-navigation-ios/MapboxNavigation/CarPlayManager.swift:239
#11	0x000000010218e018 in ViewController.presentAndRemoveMapview(_:) at /path/to/mapbox-navigation-ios/Example/ViewController.swift:278
#12	0x000000010218c638 in ViewController.startBasicNavigation() at /path/to/mapbox-navigation-ios/Example/ViewController.swift:225
#13	0x0000000102187414 in closure #1 in ViewController.viewDidLoad() at /path/to/mapbox-navigation-ios/Example/ViewController.swift:80
```

Like #2034, this short feedback loop could be fixed by delaying the call to `CarPlayManager.beginNavigationWithCarPlay(using:navigationService:)` until after the application delegate fully presents the original NavigationViewController. Besides patching the application, we need to document the delicate dance between NavigationViewController and CarPlayManager in `precondition` and `postcondition` commands in SDK documentation comments, as well as in comments in the example application.

/cc @mapbox/navigation-ios

### PR DESCRIPTION
**Pull request by JThramer**
Data Race!

Fixes #2035 and #2034.

* Fixing race-condition bug by waiting until presentation completion to trigger carplay nav
* also changing trip-starting logic to not ask for a NavigationService if the user has already provided one

To-Do: 
- [x] Drive-test this to make sure things are fixed in the way we expect
- [x] Fix test

/cc @mapbox/navigation-ios

### CODE REVIEW

**Comment by JThramer** [comment]
Testing slack integration...

File: MapboxNavigation/CarPlayManager.swift [hunk 1]
```diff
@@ -509,14 +511,19 @@ extension CarPlayManager: CPMapTemplateDelegate {
         var service: NavigationService
         
         let desiredSimulationMode: SimulationMode = simulatesLocations ? .always : .onPoorGPS
-        if let override = delegate?.carPlayManager(self, navigationServiceAlong: route, desiredSimulationMode: desiredSimulationMode) {
-            service = override
+        if let navService = navigationService {
+            service = navService
         } else {
-            service = MapboxNavigationService(route: route, simulating: desiredSimulationMode)
+            if let override = delegate?.carPlayManager(self, navigationServiceAlong: route, desiredSimulationMode: desiredSimulationMode) {
```
Comment (1ec5) [inline MapboxNavigation/CarPlayManager.swift]: This can be written more succinctly as:

```swift
if let navigationService = navigationService ?? delegate?.carPlayManager(self, navigationServiceAlong: route, desiredSimulationMode: desiredSimulationMode) {
    self.navigationService = navigationService
} else {
    navigationService = MapboxNavigationService(route: route, simulating: desiredSimulationMode)
}
```

or even:

```swift
self.navigationService = navigationService ??
    delegate?.carPlayManager(self, navigationServiceAlong: route, desiredSimulationMode: desiredSimulationMode) ??
    MapboxNavigationService(route: route, simulating: desiredSimulationMode)
```

File: Example/ViewController.swift [hunk 2]
```diff
@@ -258,11 +258,14 @@ class ViewController: UIViewController {
...
         
-        if #available(iOS 12.0, *), let service = navigationViewController.navigationService, let location = service.router.location {
-            delegate?.carPlayManager.beginNavigationWithCarPlay(using: location.coordinate, navigationService: service)
-        }
-        
         present(navigationViewController, animated: true) {
+            if #available(iOS 12.0, *),
+                let service = navigationViewController.navigationService,
+                let location = service.router.location {
+                delegate?.carPlayManager.beginNavigationWithCarPlay(using: location.coordinate,
```
Comment (1ec5) [inline Example/ViewController.swift]: The documentation for this method should have a `precondition` about the NavigationViewController already having been presented fully.
