### PR TITLE
Sticky course view tracking and persistent content inset

### LINKED ISSUE #1731: UserCourseView should update instantaneously when user gestures cause camera changes
When the user manually rotates the map using gestures, the puck should rotate synchronously with the map. Currently, there’s a bit of a lag that, while smooth, makes the puck look like it’s on a turntable. Similarly and more noticeably, when the user manually pans the map using gestures, the puck should move synchronously with the map instead of casually mosying over to the new location.

Both these issues would be fixed by disabling UserCourseView’s animation (or setting the animation duration to 0&nbsp;seconds) when the map view’s camera changes for reasons other than course tracking. #1506 fixed the same issue, but only when transitioning between overview and turn-by-turn modes.

/cc @vincethecoder

### LINKED ISSUE #1949: User course view lurches to the side when performing a maneuver
`NavigationMapView.shouldPositionCourseViewFrameByFrame` keeps the user course view (puck) constrained to the map on each frame, but it only ever seems to be enabled in response to external changes to the map view rather than internal changes due to location updates. When this property was originally added in #402, the idea was that the map would lasso the puck and force-synchronize it with the map on each frame, rather than allowing it to roam free using its normal 1-second animation, in response to location updates. At some point, this distinction was lost.

As a result of this omission, as the route takes a right turn, we send the puck to the right based on where the next location along the cross street is currently displayed on the map. That movement is animated with a duration of 1&nbsp;second. But at the same time, we kick off a 1-second-long camera animation that rotates the map to look down the cross street. The effect is that the puck appears to lurch to the right before swinging back to the center of the map to meet the route line. This effect is exacerbated by the route simulation feature’s speedup factor, if specified.

right

At a glance, the fix appears to be simple: we already correctly synchronize the puck to the map when `NavigationMapView.shouldPositionCourseViewFrameByFrame` is enabled, but we need to enable that property via `NavigationMapView.enableFrameByFrameCourseViewTracking(for:)` when approaching a maneuver. There’s some existing logic along these lines, but it only adjusts the map view’s frame rate rather than keeping `shouldPositionCourseViewFrameByFrame` enabled:

https://github.com/mapbox/mapbox-navigation-ios/blob/9e83261e2c768ae815dccae2caba0d9464ffb656/MapboxNavigation/NavigationMapView.swift#L273 https://github.com/mapbox/mapbox-navigation-ios/blob/9e83261e2c768ae815dccae2caba0d9464ffb656/MapboxNavigation/NavigationMapView.swift#L295-L296

/cc @mapbox/navigation-ios

### LINKED ISSUE #2030: CarPlay map fits to previewed route when returning to main map from custom template
When returning to the main CarPlay map from a route preview via a template other than the search template, the map doesn’t enter course tracking mode and in some cases doesn’t tilt. Without course tracking mode, the camera seems to fit to a route that is no longer being previewed.

unfit

To reproduce in the CarPlay example application:

1. Tap on the ⭐️ Favorites button in the navigation bar.
1. Select a favorite to preview.
1. Return to the favorites list.
1. Tap Back to return to the main map.
1. Wait until the navigation bar automatically hides.

The issue doesn’t reproduce when using the search template, because this code in CarPlayManager special-cases CPSearchTemplate:

https://github.com/mapbox/mapbox-navigation-ios/blob/2a75525dd4bcd42f44a136b319910eadc39e4c47/MapboxNavigation/CarPlayManager.swift#L333-L342

/ref #2022
/cc @mapbox/navigation-ios

### PR DESCRIPTION
**Pull request by frederoni**
_work in progress_

- [x] Fixes #1731 - UserCourseView should update instantaneously
- [x] Fixes #1949 - User course view lurches to the side
- [ ] ~~Fix #2030 CarPlay map fitting~~ (already fixed in #2022)

This PR brings back the course tracking similar to the default in MGLMapView where the puck and camera are synchronized which is really noticeable when simulating faster than 1×.

tracking

cc @1ec5 @JThramer

### CODE REVIEW

File: MapboxNavigation/CarPlayNavigationViewController.swift [hunk 1]
```diff
@@ -222,15 +222,29 @@ public class CarPlayNavigationViewController: UIViewController {
...
             }
         }
     }
     
+    func contentInset(forOverviewing overviewing: Bool) -> UIEdgeInsets {
+        var contentInsets = view.safeArea
+        
+        if overviewing {
+            let padding = UIEdgeInsets(top: 40, left: 40, bottom: 40, right: 40)
+            contentInsets += padding
```
Comment (frederoni) [inline MapboxNavigation/CarPlayNavigationViewController.swift]: Max MBRouteLineWidthByZoomLevel should be accounted for.

File: MapboxNavigation/NavigationMapView.swift [hunk 2]
```diff
@@ -331,15 +330,18 @@ open class NavigationMapView: MGLMapView, UIGestureRecognizerDelegate {
...
+            let point = userAnchorPoint
+            let padding = UIEdgeInsets(top: point.y, left: point.x, bottom: bounds.height - point.y, right: bounds.width - point.x)
+            // Omit padding when https://github.com/mapbox/mapbox-gl-native/pull/14081 has landed
             setCamera(newCamera, withDuration: duration, animationTimingFunction: function, edgePadding: padding, completionHandler: nil)
-        }
-        if !tracksUserCourse || userAnchorPoint != userCourseView?.center ?? userAnchorPoint {
-            UIView.animate(withDuration: duration, delay: 0, options: [.curveLinear, .beginFromCurrentState], animations: {
-                self.userCourseView?.center = self.convert(location.coordinate, toPointTo: self)
+            userCourseView?.center = userAnchorPoint
+        } else {
```
Comment (1ec5) [inline MapboxNavigation/NavigationMapView.swift]: This reprises part of #1732. I take it https://github.com/mapbox/mapbox-navigation-ios/pull/1732#discussion_r219017992 is no longer a concern because the puck’s on-screen position is a fixed value now?

File: MapboxNavigation/RouteMapViewController.swift [hunk 3]
```diff
@@ -469,11 +469,28 @@ class RouteMapViewController: UIViewController {
...
+        
+        var insets = UIEdgeInsets(top: instructionBannerHeight,
+                                  left: 0,
+                                  bottom: bottomBannerHeight,
+                                  right: 0)
+        
+        if overviewing {
+            let courseView = mapView.userCourseView != nil ? mapView.userCourseView!.bounds.midX : 0
+            let routeLineWidths = MBRouteLineWidthByZoomLevel.compactMap { $0.value.constantValue as? Int }
+            let maxRouteLineWidth = CGFloat(routeLineWidths.max() ?? 0)
```
Comment (1ec5) [inline MapboxNavigation/RouteMapViewController.swift]: The resulting zoom level is the only one that matters, right?

**Comment by 1ec5** [comment]
#2030 was already fixed in #2022.

**Comment by 1ec5** [comment]
Apparently this issue regresses #2030, but it should be straightforward to isolate and undo that change.

**Comment by 1ec5** [comment]
Current state of this branch when previewing a route to a nearby destination using a search result in search history:

preview

**Comment by frederoni** [comment]
The CarPlay preview is reverted and should behave exactly as before

File: MapboxNavigation/CarPlayManager.swift [hunk 4]
```diff
@@ -587,8 +587,7 @@ extension CarPlayManager: CPMapTemplateDelegate {
         topDownCamera.pitch = 0
         mapView.setCamera(topDownCamera, animated: false)
 
-        let padding = NavigationMapView.defaultPadding + mapView.safeArea
-        mapView.showcase([route], padding: padding)
```
Comment (frederoni) [inline MapboxNavigation/CarPlayManager.swift]: this should also be reverted

File: MapboxNavigation/NavigationMapView.swift (hunk 2 above)
Comment (frederoni) [reply MapboxNavigation/NavigationMapView.swift]: Exactly. The position is fixed unless frame by frame tracking is enabled which is needed when content insets or device orientation changes.

File: MapboxNavigation/CarPlayNavigationViewController.swift [hunk 5]
```diff
@@ -175,12 +179,33 @@ public class CarPlayNavigationViewController: UIViewController {
...
+        
+        mapViewRightSafeAreaBalancingConstraint?.constant = -mapView.safeArea.right
+        mapViewLeftSafeAreaBalancingConstraint?.constant = mapView.safeArea.left
+        view.setNeedsUpdateConstraints()
+        
+        mapView.enableFrameByFrameCourseViewTracking(for: 1)
+        
+        if !tracksUserCourse {
+            mapView.setContentInset(overviewContentInsets(), animated: false)
+            mapView.fit(to: navigationService.route, facing: 0, padding: .zero, animated: false)
```
Comment (1ec5) [inline MapboxNavigation/CarPlayNavigationViewController.swift]: Now if the user pans, disabling course tracking but without entering overview mode, the map will revert to course tracking once the navigation bar goes away. I guess that’s OK but somewhat unexpected.

File: MapboxNavigation/NavigationMapView.swift [hunk 6]
```diff
@@ -1085,12 +1090,13 @@ open class NavigationMapView: MGLMapView, UIGestureRecognizerDelegate {
...
         }
         
-        let cam = self.camera
-        cam.pitch = 0
-        cam.heading = 0
+        let currentCamera = self.camera
+        currentCamera.pitch = 0
+        currentCamera.heading = 0
+        
+        let newCamera = camera(currentCamera, fitting: line, edgePadding: padding)
```
Comment (1ec5) [inline MapboxNavigation/NavigationMapView.swift]: This is equivalent to calling `cameraThatFits(_:direction:edgePadding:)`, since we’re forcing the pitch to be 0° anyways.

File: MapboxNavigation/RouteMapViewController.swift [hunk 7]
```diff
@@ -469,11 +471,22 @@ class RouteMapViewController: UIViewController {
...
+        let bottomBannerHeight = bottomBannerContainerView.bounds.height
+        
+        var insets = UIEdgeInsets(top: instructionBannerHeight, left: 0,
+                                  bottom: bottomBannerHeight, right: 0)
+        
+        if overviewing {
+            insets += NavigationMapView.courseViewMinimumInsets
+            
+            let routeLineWidths = MBRouteLineWidthByZoomLevel.compactMap { $0.value.constantValue as? Int }
+            insets += UIEdgeInsets(floatLiteral: Double(routeLineWidths.max() ?? 0))
```
Comment (1ec5) [inline MapboxNavigation/RouteMapViewController.swift]: 👍 As noted in https://github.com/mapbox/mapbox-navigation-ios/pull/2047#discussion_r267557733, this is rather conservative considering that only one zoom level is active at a given time. But we don‘t have ready access to the evaluated expression (unlike if we were using GL JS), and this method also gets called before calculating a camera rather than after, so choosing the right width isn’t worth the hassle. In practice, it would only be a few extra points on each side at most.

File: MapboxNavigation/CarPlayNavigationViewController.swift (hunk 5 above)
Comment (frederoni) [reply MapboxNavigation/CarPlayNavigationViewController.swift]: You're right. We probably need a flag `isOverviewing` here similar to RouteMapViewController.
Panning around is currently not possible either with course tracking on/off nor overviewing (navigation bar popping in triggers viewSafeAreaInsetsDidChange() which in turn, fits the camera to the route).

Comment (1ec5) [reply MapboxNavigation/CarPlayNavigationViewController.swift]: @JThramer pointed out that this is actually pretty fortuitous. There isn’t a Resume or Recenter button like in NavigationViewController, and there’s no location tracking button like during the CarPlay browsing activity, so this code path is actually the most convenient way to get back into course tracking mode. Otherwise, the user has to tap the Overview button and tap the location tracking button after that.

Comment (JThramer) [reply MapboxNavigation/CarPlayNavigationViewController.swift]: Disagree. This behavior is actually better than it was previously, as there is no resume button in CarPlay.
