### PR TITLE
Stop previewing when swipe to current banner.

### LINKED ISSUE #3784: [Bug]: Top instruction banner cannot swipe back to current one
### Mapbox Navigation SDK version

v2.4.0-beta.1

### Steps to reproduce

1. Build the `Example`, choose a route with multiple steps, start active navigation.
2. Swipe the top instruction banner to the left and to the right

### Expected behavior

1. The top instruction banner could swipe to current step.
3. Under the Night style, the preview instruction banner should have the same color as the `InstructionsBannerView`.

### Actual behavior

1. The top instruction banner couldn't swipe to current step.
3. Under the Night style, the preview instruction banner have the same color as the `StepInstructionsView` in the drop down menu, instead of the normal banner.

### Is this a one-time issue or a repeatable issue?

repeatable

### PR DESCRIPTION
**Pull request by ShanMa1991**
### Description
This PR is to
- [x] fixed #3784 to allow the top banner could swipe to current step by stop previewing and recenter the map. 
- [x] fixed the preview instruction color un-match with the top banner in Night Style. 
- [x] fixed the broken layout constraints broken of instruction cards.

### Implementation
The `TopBannerViewController.previewInstructionsView` should conforms to `InstructionsBannerView` to match the color with top banner. And when in previewing mode and user swipe back to current step, stop previewing mode and recenter map.

### Screenshots or Gifs
nightSwipeBanner

### CODE REVIEW

**Review by 1ec5 — APPROVED** [review]

File: Example/CustomViewController.swift [hunk 1]
```diff
@@ -26,7 +26,7 @@ class CustomViewController: UIViewController {
     var previewStepIndex: Int?
     
     // View that is placed over the instructions banner while we are previewing
-    var previewInstructionsView: StepInstructionsView?
+    var previewInstructionsView: InstructionsBannerView?
```
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Example/CustomViewController.swift:29]: Thanks for the suggestion, I'll rename it.

File: Sources/MapboxNavigation/InstructionsCardViewController.swift [hunk 2]
```diff
@@ -189,25 +189,35 @@ open class InstructionsCardViewController: UIViewController {
             instructionCollectionView.bottomAnchor.constraint(equalTo: view.bottomAnchor)
         ]
         
-        // Device is in landscape mode and notch (if present) is located on the left side.
-        if UIApplication.shared.statusBarOrientation == .landscapeRight {
-            if UIApplication.shared.userInterfaceLayoutDirection == .rightToLeft {
-                // Language with right-to-left interface layout is used.
-                instructionCollectionViewContraints.append(instructionCollectionView.leadingAnchor.constraint(equalTo: view.leadingAnchor,
-                                                                                                              constant: 10.0))
+        switch traitCollection.verticalSizeClass {
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/InstructionsCardViewController.swift:192]: Can you please describe this change? Do you think that `.unspecified` should be always equal to `.regular`?

Comment (ShanMa1991) [reply Sources/MapboxNavigation/InstructionsCardViewController.swift:192]: I add the `verticalSizeClass` check because the previous check only divide into the `landscapeRight` and other. But in the `portrait/unknown` or the `verticalSizeClass` is `regular/unspecified`, it need to choose the `leadingAnchor` of the `navigationView` to allow the bottom banner and the floating buttons align with it. When it's `.unspecified`, it's better to choose the default as the `.regular` to align with the navigationView layout constraints as well.
