### PR TITLE
Fix issue with user course view rendering.

### LINKED ISSUE #3918: [Bug]: User location is not shown correctly if `NavigationMapView.userLocationStyle = .courseView()` is set.
### Mapbox Navigation SDK version

main

### Steps to reproduce

1. Remove example application from device and install it again.
2. Set `NavigationMapView.userLocationStyle = .courseView()`.
3. After opening the app accept location authorization.
4. Observe behavior.

### Expected behavior

Camera should switch to following mode after getting location information. User course view should be updated as well.

### Actual behavior

Camera doesn't switch to following mode. User course view stays in `.zero` position. For example:

Simulator Screen Shot - iPhone 13 - 2022-05-26 at 11 55 40

### Is this a one-time issue or a repeatable issue?

repeatable

### PR DESCRIPTION
**Pull request by MaximAlien**
### Description

Fixes #3918.

PR fixes an issue where in case of initial application launch user course view is always drawn in initial position.

### CODE REVIEW

File: Sources/MapboxNavigation/NavigationMapView.swift [hunk 1]
```diff
@@ -787,6 +787,16 @@ open class NavigationMapView: UIView {
     func setupUserLocation() {
         if !locationManager.isAuthorized() { return }
         
+        // Since Mapbox Maps will not provide location data in case if `LocationOptions.puckType` is
+        // set to nil, we have to draw empty and transparent `UIImage` instead of puck. This is used
+        // in case when user wants to stop showing location puck or draw a custom one.
+        let clearImage = UIColor.clear.image(CGSize(size: 1.0))
```
Comment (bamx23) [inline Sources/MapboxNavigation/NavigationMapView.swift:793]: Should we rather create this image only if `userLocationStyle` is `courseView`?

**Review by bamx23 — APPROVED** [review]

File: Sources/MapboxNavigation/NavigationMapView.swift (hunk 1 above)
Comment (MaximAlien) [reply Sources/MapboxNavigation/NavigationMapView.swift:805]: We need to use `emptyPuckConfiguration` in other cases as well. Code was updated.
