### PR TITLE
Fix user puck transformation in overview

### LINKED ISSUE #1079: User puck is not flat
image

Locks a little off kilter while rotating the map.

/cc @frederoni

### PR DESCRIPTION
**Pull request by frederoni**
Fixes #1079 - User puck is not flat in overview mode

This regressed in #1012

- wip

@akitchen @bsudekum 👀

### CODE REVIEW

File: MapboxNavigation/UserCourseView.swift [hunk 1]
```diff
@@ -37,7 +38,22 @@ extension UIView {
  A view representing the user’s location on screen.
  */
 @objc(MBUserPuckCourseView)
-public class UserPuckCourseView: UIView {
+public class UserPuckCourseView: UIView, UserCourseView {
+    
+    public func update(location: CLLocation, pitch: CGFloat, direction: CLLocationDegrees, animated: Bool, tracksUserCourse: Bool) {
```
Comment (bsudekum) [inline MapboxNavigation/UserCourseView.swift]: This could use some documentation.
