### PR TITLE
Draw roundabout based on maneuver direction

### LINKED ISSUE #638: Incorrect arrow exit indicator on roundabout
On the current 0.80.0 SDK, the navigation displays an incorrect roundabout exit arrow indicator.

img_0012

The roundabout in question is:
https://www.hitta.se/kartan!~59.21583,17.63506,16z/tr!i=6Kbb9lGk/geocode!l=59.21595:17.63450

### PR DESCRIPTION
**Pull request by frederoni**
Fixes #638 

`takeRoundabout`, `turnAtRoundabout`, and `takeRotary` with any maneuver direction were previously drawn as a roundabout with a right turn.

@bsudekum @1ec5 

/cc @Sealos

### CODE REVIEW

File: MapboxNavigation/TurnArrowView.swift [hunk 1]
```diff
@@ -73,7 +73,14 @@ public class TurnArrowView: UIView {
...
             flip = [.right, .slightRight, .sharpRight].contains(direction)
         case .takeRoundabout, .turnAtRoundabout, .takeRotary:
-            StyleKitArrows.drawRoundabout(primaryColor: primaryColor, secondaryColor: secondaryColor, scale: scale)
+            switch direction {
+            case .straightAhead:
+                StyleKitArrows.drawRoundabout_180(primaryColor: primaryColor, secondaryColor: secondaryColor, scale: scale)
+            case .left, .slightLeft, .sharpLeft:
+                StyleKitArrows.drawRoundabout_275(primaryColor: primaryColor, secondaryColor: secondaryColor, scale: scale)
+            default:
+                StyleKitArrows.drawRoundabout(primaryColor: primaryColor, secondaryColor: secondaryColor, scale: scale)
```
Comment (1ec5) [inline MapboxNavigation/TurnArrowView.swift]: @mcwhittemore pointed out that this logic doesn’t seem to account for left-hand driving. @frederoni, do we need to set `flip` somehow here?

Comment (mcwhittemore) [reply MapboxNavigation/TurnArrowView.swift]: this isn't in the OSRM response...

Comment (1ec5) [reply MapboxNavigation/TurnArrowView.swift]: Ah, I see that was ticketed out separately as #575.
