### PR TITLE
Force-Unwrap anchor crash fix

### LINKED ISSUE #1221: Unsafe Unwrap in RouteMapViewController:661
¡Crash!

Looks like an unsafe unwrap in [RouteMapViewController.swift:661](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/RouteMapViewController.swift?utf8=✓#L661)

/cc @mapbox/navigation-ios

### PR DESCRIPTION
**Pull request by JThramer**
Hello darkness my old friend...

* Fixing issue where an unsafe force-unwrap could cause a crash under certain circumstances.

Fixes #1221.

/cc @mapbox/navigation-ios

### CODE REVIEW

File: MapboxNavigation/RouteMapViewController.swift [hunk 1]
```diff
@@ -658,9 +658,13 @@ extension RouteMapViewController: NavigationViewDelegate {
...
-        let endOfRouteTime = (navigationView.endOfRouteView != nil && navigationView.endOfRouteShowConstraint!.isActive == true)
-        guard !endOfRouteTime else { return CGPoint(x: mapView.bounds.midX, y: (mapView.bounds.height * 0.4)) }
-        return delegate?.navigationMapViewUserAnchorPoint?(mapView) ?? .zero
+        //If the end of route component is showing, then put the anchor point slightly above the middle of the map
+        if navigationView.endOfRouteView != nil, let show = navigationView.endOfRouteShowConstraint, show.isActive {
+            return CGPoint(x: mapView.bounds.midX, y: (mapView.bounds.height * 0.4))
+        }
+        
+        //otherwise, ask the delegate or return .zero
+        return self.delegate?.navigationMapViewUserAnchorPoint?(mapView) ?? .zero
```
Comment (frederoni) [inline MapboxNavigation/RouteMapViewController.swift]: nit: self can be dropped
