### PR TITLE
Introduce IdleTimerManager to streamline idle timer management and fix bugs

### LINKED ISSUE #3227: Improve idle time management
# Problem 

Currently, `NavigationViewController` and `CarPlayManager` changes `UIApplication.shared.isIdleTimerDisabled` in a way that if there are two instances of `NavigationViewController` or `CarPlayManager` disconnects, the actual state of `UIApplication.shared.isIdleTimerDisabled` might end up in inconsistent state. 

Also, `CarPlayManager`s `isIdleTimerDisabled` usage should be revisit so that it doesn't enable idle timer on connect/disconnect. 

# Solution

Use singleton idle timer manager of some kind which will track how many requests to disable/enable timer of various kinds were send and send appropriate values to `UIApplication.shared.isIdleTimerDisabled`. 

Possible places for this management code: 
- `NavigationSettings`
- New `IdleTimerManager` type: the favourable choice, because the case with CarPlay is more complex. 
- Your option. 

cc @mapbox/navigation-ios @1ec5

### PR DESCRIPTION
**Pull request by S2Ler**
fixes #3227

I drafted a POC of how idle timer can look like. Then naming is temporary, but for some reason I really like to use token here :)

Given that behaviour in CarPlayManager is very confusing and contradicts itself, I've change the logic to the following:
- If `carPlayManagerShouldDisableIdleTimer` returns true: idle timer is disabled while CarPlay is active, otherwise, do nothing. 
- If NavigationViewController is visible: disable idle timer. 

Does this sound reasonable to you? Should the logic be different?

### CODE REVIEW

**Review by Udumft — COMMENTED** [review]
LGTM, token idea seems fit to me. But maybe we should also couple it with `PassiveLocationProvider` lifecycle to disable idling while free drive is active too?

File: Sources/MapboxNavigation/IdleTimerManager.swift [hunk 1]
```diff
@@ -0,0 +1,43 @@
+import Foundation
+import UIKit
+
+/// Manages UIApplication.shared.isIdleTimerDisabled
+final class IdleTimerManager {
+    final class Token {
```
Comment (bamx23) [inline Sources/MapboxNavigation/IdleTimerManager.swift:6]: Maybe `Handle` is a more natural name for this structure. Similar to `CacheHandle`

File: Sources/MapboxNavigation/IdleTimerManager.swift [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+        didSet {
+            updateIdleTimer()
+        }
+    }
+
+    private init() {}
+
+    /// Disabled idle timer while there is at least one Token alive.
+    func issueIdleToken() -> Token {
+        dispatchPrecondition(condition: .onQueue(.main))
```
Comment (bamx23) [inline Sources/MapboxNavigation/IdleTimerManager.swift:30]: Should this precondition be moved to `updateIdleTimer` so that we check token deallocation too?

File: Sources/MapboxNavigation/IdleTimerManager.swift [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+        let token = Token {
+            self.idleTokenCount -= 1
+        }
+        idleTokenCount += 1
+        return token
+    }
+
+    private func updateIdleTimer() {
+        UIApplication.shared.isIdleTimerDisabled = idleTokenCount > 0
+        print("$$$ Always On: \(UIApplication.shared.isIdleTimerDisabled)")
```
Comment (bamx23) [inline Sources/MapboxNavigation/IdleTimerManager.swift:40]: Don't forget to clean up here

**Review by bamx23 — APPROVED** [review]

File: Sources/MapboxNavigation/IdleTimerManager.swift [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+
+     - Returns: An instance of cancellable that you should retain until you want the idle timer to be disabled.
+     */
+    func disableIdleTimer() -> IdleTimerManager.Cancellable {
+        dispatchPrecondition(condition: .onQueue(.main))
+        let token = Cancellable {
+            self.cancellablesCount -= 1
+        }
+        cancellablesCount += 1
+        return token
```
Comment (bamx23) [inline Sources/MapboxNavigation/IdleTimerManager.swift:42]:
```suggestion
        let cancellable = Cancellable {
            self.cancellablesCount -= 1
        }
        cancellablesCount += 1
        return cancellable
```

File: Sources/MapboxNavigation/NavigationViewController.swift [hunk 5]
```diff
@@ -174,7 +174,13 @@ open class NavigationViewController: UIViewController, NavigationStatusPresenter
     /**
      If `true`, `UIApplication.isIdleTimerDisabled` is set to `true` in `viewWillAppear(_:)` and `false` in `viewWillDisappear(_:)`. If your application manages the idle timer itself, set this property to `false`.
      */
-    public var shouldManageApplicationIdleTimer = true
+    public var shouldManageApplicationIdleTimer = true {
+        didSet {
```
[the remark this answers is not in the document]
Comment (bamx23) [reply Sources/MapboxNavigation/NavigationViewController.swift:178]: Should we initialize a new token here if it was set back to `true`?

File: Sources/MapboxNavigation/IdleTimerManager.swift (hunk 1 above)
Comment (S2Ler) [reply Sources/MapboxNavigation/IdleTimerManager.swift]: I end up with Cancellable similar to Combine.Cancellable concept. But couldn't use Combine due to deployment target limitations.

Comment (S2Ler) [reply Sources/MapboxNavigation/IdleTimerManager.swift]: `Combine.Cancellable`, so be it.

File: Sources/MapboxNavigation/NavigationViewController.swift (hunk 5 above)
[the remark this answers is not in the document]
Comment (S2Ler) [reply Sources/MapboxNavigation/NavigationViewController.swift:178]: Should take into account the case when vc isn't visible.

File: Sources/MapboxNavigation/IdleTimerManager.swift [hunk 6]
```diff
@@ -0,0 +1,43 @@
...
+    private var idleTokenCount: Int = 0 {
+        didSet {
+            updateIdleTimer()
+        }
+    }
+
+    private init() {}
+
+    /// Disabled idle timer while there is at least one Token alive.
+    func issueIdleToken() -> Token {
```
[the remark this answers is not in the document]
Comment (S2Ler) [reply Sources/MapboxNavigation/IdleTimerManager.swift]: yep.

File: Sources/MapboxNavigation/IdleTimerManager.swift (hunk 4 above)
Comment (S2Ler) [reply Sources/MapboxNavigation/IdleTimerManager.swift:42]: done, thanks

File: Sources/MapboxNavigation/IdleTimerManager.swift (hunk 2 above)
Comment (S2Ler) [reply Sources/MapboxNavigation/IdleTimerManager.swift]: I've changed the implementation to be thread-safe.

File: Sources/MapboxNavigation/NavigationViewController.swift (hunk 5 above)
[the remark this answers is not in the document]
Comment (S2Ler) [reply Sources/MapboxNavigation/NavigationViewController.swift:178]: Done.

**Comment by 1ec5** [comment]
> LGTM, token idea seems fit to me. But maybe we should also couple it with `PassiveLocationProvider` lifecycle to disable idling while free drive is active too?

Seems to me that it should be the other way around. An application may want to automatically enable or disable PassiveLocationProvider depending on whether the application is in the foreground or background. I don’t think the presence of PassiveLocationProvider alone is enough to prevent the screen from locking, because the basic use case for it is just to clean up puck and camera behavior on a map that the user is using passively (hence the name of that class).

**Review by 1ec5 — APPROVED** [review]
