### PR TITLE
Location Manager Simulation

### LINKED ISSUE #1804: Need to set CLLocationManager.delegate to nil in delegate's deinit methods
**Mapbox Navigation SDK version:**
We're on 0.18.1, but it looks like this is still the case on master.

We've seen a few crashes that look like they could result from CLLocationManager attempting to message a delegate that's been deallocated. By inspection of the code, it looks like the SDK needs to be updated to set `CLLocationManager.delegate` to `nil` when the delegate gets deallocated. Unlike other delegates, this one is `unowned` rather than `weak` ([link](https://developer.apple.com/documentation/corelocation/cllocationmanager/1423792-delegate)).

### PR DESCRIPTION
**Pull request by JThramer**
Fixes #1804 and #1662.

* Fixes issue where strongly-held `unowned` delegate ref in `CLLocationManager` can cause crash.
* Replaces `performSelector:afterDelay:` based timer mechanism with a dispatch timer source, which fixes crash.

To-do: 

- [x] Settle on scheduling parameters
- [x] Unit Tests
- [x] Write changelog

/cc @mapbox/navigation-ios

### CODE REVIEW

File: MapboxCoreNavigation/SimulatedLocationManager.swift [hunk 1]
```diff
@@ -88,14 +91,18 @@ open class SimulatedLocationManager: NavigationLocationManager {
...
 
-    private func initializeSimulatedLocationManager(for route: Route, currentDistance: CLLocationDistance, currentSpeed: CLLocationSpeed) {
+    private func commonInit(for route: Route, currentDistance: CLLocationDistance, currentSpeed: CLLocationSpeed) {
         
         self.currentSpeed = currentSpeed
         self.currentDistance = currentDistance
         self.route = route
+
+        self.timer = DispatchTimer(countdown: .milliseconds(0), repeating: updateInterval, accuracy: accuracy, executingOn: .main) { [weak self] in
+            DispatchQueue.main.async { self?.tick() }
```
Comment (JThramer) [inline MapboxCoreNavigation/SimulatedLocationManager.swift]: Is this async call necessary if we're `executingOn: .main`?

Comment (akitchen) [reply MapboxCoreNavigation/SimulatedLocationManager.swift]: if you want to defer to a later run loop iteration ...

File: MapboxCoreNavigation/NavigationService.swift [hunk 2]
```diff
@@ -268,6 +268,8 @@ public class MapboxNavigationService: NSObject, NavigationService, DefaultInterf
     deinit {
         suspendNotifications()
         endNavigation()
+        nativeLocationSource.delegate = nil
+        simulatedLocationSource?.delegate = nil
```
Comment (akitchen) [inline MapboxCoreNavigation/NavigationService.swift]: This is an important addition, but I can't help but wonder if there are other places where this needs to be done as well?

**Comment by akitchen** [comment]
> Fixes issue where strongly-held unowned delegate ref in CLLocationManager can cause crash.

This is mildly pedantic, but the issue is that the `assign` reference isn't strongly held, it's just a dangling pointer.

File: MapboxCoreNavigation/NavigationService.swift (hunk 2 above)
Comment (JThramer) [reply MapboxCoreNavigation/NavigationService.swift]: Apparently `CLLocationManager` is an exception because unlike convention, they store their delegate reference as `unowned` instead of `weak`. Apparently you usually you don't have to worry about this.

I also searched the code -- we don't set location manager delegates outside of the navigation service.

File: MapboxCoreNavigation/DispatchTimer.swift [hunk 3]
```diff
@@ -14,16 +14,18 @@ class CountdownTimer {
         }
     }
     private var deadline: DispatchTime { return .now() + countdownInterval }
+    let repititionInterval: DispatchTimeInterval
```
Comment (akitchen) [inline MapboxCoreNavigation/DispatchTimer.swift]: oops, misspelling

File: CHANGELOG.md [hunk 4]
```diff
@@ -2,6 +2,8 @@
 
 ## master
 
+* Fixed issue where a released reference that was kept in `CLLocationManager` as `unowned` could cause crash. ([#1820](https://github.com/mapbox/mapbox-navigation-ios/pull/1820))
```
Comment (1ec5) [inline CHANGELOG.md]: The dangling reference was in SDK code; mentioning it in the changelog entry makes it sound to the developer like the crash would occur when application code had a dangling reference.

```suggestion
* Fixed a crash during turn-by-turn navigation. ([#1820](https://github.com/mapbox/mapbox-navigation-ios/pull/1820))
```

File: CHANGELOG.md [hunk 5]
```diff
@@ -2,6 +2,8 @@
...
+* Replacing `performSelector:afterDelay:` mechanism that was [causing a crash](https://github.com/mapbox/mapbox-navigation-ios/issues/1662) with a DispatchTimerSource-based mechanism. ([#1820](https://github.com/mapbox/mapbox-navigation-ios/pull/1820))
```
Comment (1ec5) [inline CHANGELOG.md]: Similarly, this is a purely internal change. If we expect any reliability or stability improvements to result from this change, we can mention those improvements here; otherwise, the change isn’t actionable to the developer.

File: CHANGELOG.md [hunk 6]
```diff
@@ -2,6 +2,8 @@
 
 ## master
```
Comment (1ec5) [inline CHANGELOG.md]: You’ll probably want to rebase onto master, because the changelog entries need to go in a new master section, not v0.24.0.

File: CHANGELOG.md (hunk 5 above)
Comment (akitchen) [reply CHANGELOG.md]:
```suggestion
* Replaces the `SimulatedLocationManager` timer mechanism with a `DispatchTimerSource`-based mechanism ([#1820](https://github.com/mapbox/mapbox-navigation-ios/pull/1820)), which fixes a crash that was caused by retaining the `SimulatedLocationManager` while it still had a dangling reference to its delegate (https://github.com/mapbox/mapbox-navigation-ios/issues/1662)
```

Comment (1ec5) [reply CHANGELOG.md]: I think the line above (as amended) adequately describes the developer impact of this PR. This PR’s description is the place to provide details about the crash’s root cause and the fix’s implementation.
