### PR TITLE
Fix alternative route line selection.

### LINKED ISSUE #3066: Alternative route selection no longer works after updating to Mapbox Maps `v10.0.0-beta.21`.
**Mapbox Navigation SDK version:** [PR](https://github.com/mapbox/mapbox-navigation-ios/pull/3039)

Alternative route selection no longer works after updating to Mapbox Maps `v10.0.0-beta.21`.

### PR DESCRIPTION
**Pull request by MaximAlien**
### Description

Fixes #3066.

### CODE REVIEW

**Review by azarovalex — APPROVED** [review]
LGTM

File: Sources/MapboxNavigation/NavigationMapView.swift [hunk 1]
```diff
@@ -349,9 +349,10 @@ open class NavigationMapView: UIView {
     }
     
     func setupGestureRecognizers() {
-        for recognizer in mapView.gestureRecognizers ?? [] where recognizer is UITapGestureRecognizer {
```
Comment (S2Ler) [inline Sources/MapboxNavigation/NavigationMapView.swift:352]: So, mayView doesn't have tap gesture anymore?

Comment (MaximAlien) [reply Sources/MapboxNavigation/NavigationMapView.swift:352]: `MapView` keeps track of their own gestures (including taps, e.g. when selecting annotations). If I remember correctly previous implementation was added as a workaround to prevent collision with gesture recognizer, which was added by `AnnotationInteractionDelegate`.
