### PR TITLE
Only set initial maneuver avoidance radius when driving

### LINKED ISSUE #3966: [Bug]: Directions endpoints called with driving parameters in cycling profile
### Mapbox Navigation SDK version

2.5.0 and following

### Steps to reproduce

Probably similar to this issue
https://github.com/mapbox/mapbox-navigation-ios/issues/3495

Easiest approach to copy the tutorial here:
https://docs.mapbox.com/api/navigation/directions/
And add
`options.profileIdentifier = .cycling`
Which will result to this error:
`The operation couldn’t be completed. annotations value must be one of duration, distance, speed, maxspeed, congestion
`

Another case where the Directions API fails is by providing an initial cycling route to the navigation SDK, then follow another way to force the default Mapbox rerouting to trigger.

```
2022-06-24 16:49:28.155732+0200 COWBOY[11859:27554431] [Mapbox] [Error, nav-native]: Couldn't build reroute request URI. Skipping reroute.
16:49:28.1830 :blue_heart: INFO [tracking] MixPanelTracker.log(_:_:):111 - :female-detective::skin-tone-3: event.navigation.rerouting
2022-06-24 16:49:28.192885+0200 COWBOY[11859:27554429] [Mapbox] [Debug, nav-native]: Directions Service: Get route request: https://api.mapbox.com/directions/v5/mapbox/cycling/4.4,50.83%3B4.632334,51.003044?alternatives=false&continue_straight=false&avoid_maneuver_radius=1000.0&geometries=polyline6&overview=full&steps=true&language=en_US&voice_instructions=true&voice_units=imperial&banner_instructions=true&bearings=326.7431335449219,90.0;&access_token=*******
2022-06-24 16:49:28.239776+0200 COWBOY[11859:27556705] [Mapbox] [Warning, nav-native]: Directions Service: FetchDirections No Response code found!
2022-06-24 16:49:28.239898+0200 COWBOY[11859:27556705] [Mapbox] [Debug, nav-native]: Directions Service: FetchDirections Get route request error (type '5'): Invalid query param avoid_maneuver_radius.
```

Looks like the `avoid_maneuver_radius` parameter is used to build the URL while the API documentation states that it should only be used for driving.

### Expected behavior

API calls to the the Directions API should not use driving parameters when cycling.

### Actual behavior

Requests fail and no route is found when rerouting.

### Is this a one-time issue or a repeatable issue?

repeatable

### PR DESCRIPTION
**Pull request by 1ec5**
Only set the initial maneuver avoidance radius when driving; avoid setting it with the cycling and walking profiles, which don’t support the `avoid_maneuver_radius` query parameter yet.

Fixes #3966.

/cc @mandeepsandhu

### CODE REVIEW

File: Sources/MapboxCoreNavigation/Router.swift [hunk 1]
```diff
@@ -397,7 +397,8 @@ extension InternalRouter where Self: Router {
         routeTask?.cancel()
         let options = progress.reroutingOptions(from: origin)
         
-        if isRerouting {
+        // https://github.com/mapbox/mapbox-navigation-ios/issues/3966
+        if isRerouting && options.profileIdentifier != .walking && options.profileIdentifier != .cycling {
```
Comment (1ec5) [inline Sources/MapboxCoreNavigation/Router.swift:401]: I went with a negation instead of checking for the `automobile` and `automobileAvoidingTraffic` profiles because other undocumented profiles may support this query parameter. I’m open to moving this conditional to MapboxDirections, where `initialManeuverAvoidanceRadius` is converted into a `URLQueryItem`, but it seems like we’ve been shying away from hard-coding per-profile support for various parameters in that library, lest the Directions API expand support without us knowing.

/cc @LukasPaczos

Comment (LukasPaczos) [reply Sources/MapboxCoreNavigation/Router.swift:401]: A problem with negation is that if there's an undocumented profile that does not support this query parameter, the whole request will fail, won't it? Not sure what's the lesser of the two - not supporting a query parameter until SDK is updated, or risking a failing request. I think I'd rather opt for the former, especially since this is a parameter that SDK sets automatically under-the-hood for each reroute request and developer cannot exclude it if they use a profile that does not support this parameter.

Comment (1ec5) [reply Sources/MapboxCoreNavigation/Router.swift:401]: Good point. I don’t know of an undocumented profile that lacks support for this parameter, but it’s entirely possible that one may arrive on scene without us knowing on the client side.

I don’t think we can confidently add parameters under the hood like this without giving the developer the opportunity to intervene. #3464 was all about giving the developer this flexibility, but the developer has to implement a full-fledged custom routing provider to take advantage of it. I think it would make sense for… something… to expose a customization hook for the options used when rerouting.

In the meantime, I’ll reverse the negation to fix the immediate regression in the walking and cycling profiles, which are documented.

Comment (LukasPaczos) [reply Sources/MapboxCoreNavigation/Router.swift:401]: >  giving the developer the opportunity to intervene

On the Android side we did recently add a `RerouteOptionsAdapter` which does just that - https://github.com/mapbox/mapbox-navigation-android/pull/5573. The same would have to be added to all native controllers that execute requests on their own for the same precautions though. That said, I'd still feel more confident with solid "backwards compatibility" than "forward compatibility" (if we can call the different paradigms this way).

**Review by MaximAlien — APPROVED** [review]

File: Sources/MapboxCoreNavigation/Router.swift (hunk 1 above)
Comment (1ec5) [reply Sources/MapboxCoreNavigation/Router.swift]: Tracking the forward-compatibility story in #4032.
