### PR TITLE
Safely convert UIViewAnimationCurve to UIViewAnimationOptions

### LINKED ISSUE #1600: Crash showing keyboard
We’ve received the crash reports below numerous times from a limited number of devices running a lightweight application based on this SDK. #1599 attempts to fix this crash speculatively.

Given these stack traces, the crash appears to occur when focusing a text field or search field when a custom keyboard is active. Text fields are fairly obscure within this SDK, appearing only within the end-of-route feedback panel, but the second stack trace appears to come from in a search field that exists outside of NavigationViewController. I wonder if somehow a RouteMapViewController is still in memory but no longer in the view hierarchy. That could prevent `RouteMapViewController.suspendNotifications()` and `unsubscribeFromKeyboardNotifications()` from being called, so `keyboardWillShow(notification:)` would still be called.

```
#0. Crashed: com.apple.main-thread
0  libswiftCore.dylib             0x1011c0abc _stdlib_destroyTLS + 247776
1  libswiftCore.dylib             0x10101ff74 (Missing)
2  MapboxNavigation               0x100747610 $S16MapboxNavigation22RouteMapViewControllerC16keyboardWillShow33_AB58FB88B49AF290C13A69A1EE3638C1LL12notificationySo14NSNotificationC_tF (RouteMapViewController.swift:959)
3  MapboxNavigation               0x100748048 $S16MapboxNavigation22RouteMapViewControllerC16keyboardWillShow33_AB58FB88B49AF290C13A69A1EE3638C1LL12notificationySo14NSNotificationC_tFToTm + 4310974536
4  CoreFoundation                 0x1817b8c3c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
5  CoreFoundation                 0x1817b81b8 _CFXRegistrationPost + 428
6  CoreFoundation                 0x1817b7f14 ___CFXNotificationPost_block_invoke + 216
7  CoreFoundation                 0x18183584c -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1408
8  CoreFoundation                 0x1816eef38 _CFXNotificationPost + 384
9  Foundation                     0x18215fbbc -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
10 UIKit                          0x18b5f510c -[UIInputWindowController postStartNotifications:withInfo:] + 1192
11 UIKit                          0x18bff3948 __77-[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:]_block_invoke.1059 + 540
12 UIKit                          0x18b42b358 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] + 608
13 UIKit                          0x18b5f451c +[UIView(UIViewAnimationWithBlocks) _animateWithDuration:delay:options:animations:start:completion:] + 128
14 UIKit                          0x18b5f35cc -[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:] + 1588
15 UIKit                          0x18b5e8960 -[UIInputWindowController setInputViewSet:] + 1104
16 UIKit                          0x18b5e283c -[UIInputWindowController performOperations:withAnimationStyle:] + 56
17 UIKit                          0x18b5def80 -[UIPeripheralHost(UIKitInternal) setInputViews:animationStyle:] + 1716
18 UIKit                          0x18b43b630 -[UIPeripheralHost(UIKitInternal) _reloadInputViewsForResponder:] + 2472
19 UIKit                          0x18b59c2b4 -[UIResponder(UIResponderInputViewAdditions) reloadInputViews] + 80
20 UIKit                          0x18b6b2544 -[UITextView becomeFirstResponder] + 760
21 UIKit                          0x18b6b2160 -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) setFirstResponderIfNecessary] + 192
22 UIKit                          0x18b6b1298 -[UITextGestureClusterSelection oneFingerTap:] + 3148
```

```
#0	(null) in 0x103b68000 ()
#1	(null) in 0x103b68000 ()
#2	(null) in 0x103b68000 ()
#3	0x000000010388f610 in RouteMapViewController.keyboardWillShow(notification:) at /Users/mxn/hub/mapbox-navigation-ios/MapboxNavigation/RouteMapViewController.swift:959
#4	(null) in @objc RouteMapViewController.keyboardWillShow(notification:) ()
#5	(null) in __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ ()
#6	(null) in _CFXRegistrationPost ()
#7	(null) in ___CFXNotificationPost_block_invoke ()
#8	(null) in -[_CFXNotificationRegistrar find:object:observer:enumerator:] ()
#9	(null) in _CFXNotificationPost ()
#10	(null) in -[NSNotificationCenter postNotificationName:object:userInfo:] ()
#11	(null) in -[UIInputWindowController postStartNotifications:withInfo:] ()
#12	(null) in __77-[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:]_block_invoke.1059 ()
#13	(null) in +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] ()
#14	(null) in +[UIView(UIViewAnimationWithBlocks) _animateWithDuration:delay:options:animations:start:completion:] ()
#15	(null) in -[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:] ()
#16	(null) in -[UIInputWindowController setInputViewSet:] ()
#17	(null) in -[UIInputWindowController performOperations:withAnimationStyle:] ()
#18	(null) in -[UIPeripheralHost(UIKitInternal) setInputViews:animationStyle:] ()
#19	(null) in -[UIPeripheralHost(UIKitInternal) _reloadInputViewsForResponder:] ()
#20	(null) in -[UIResponder(UIResponderInputViewAdditions) reloadInputViews] ()
#21	(null) in -[UITextField becomeFirstResponder] ()
#22	(null) in -[UITextField _clearButtonClicked:] ()
```

/cc @bsudekum @JThramer

### PR DESCRIPTION
**Pull request by 1ec5**
Worked around a compiler crash due to an exhaustive switch statement that, through no fault of its own, failed to account for a common yet private enumeration value.

Fixes #1600 real good.

/cc @akitchen @JThramer

### CODE REVIEW

**Comment by 1ec5** [comment]
It isn’t possible to demonstrate the failure in live code, but here’s what the crash looks like when it reproduces:

**Comment by akitchen** [comment]
I've approved based on the approach/idea, but we still need to work through the type differences in Xcode's 9 & 10

File: MapboxNavigationTests/UIViewAnimationOptionsTests.swift [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import XCTest
+import UIKit
+@testable import MapboxNavigation
+
+class UIViewAnimationOptionsTests: XCTestCase {
+    func testAnimationCurveConversion() {
+        #if swift(>=4.2) // Swift 4.1 turns it into 65536 (!?).
```
Comment (akitchen) [inline MapboxNavigationTests/UIViewAnimationOptionsTests.swift]: really? hmm...
