### PR TITLE
Fix injected map view layout bug

### LINKED ISSUE #4041: [Bug]: `NavigationMapView` injection is not working via `NavigationOptions.`
### Mapbox Navigation SDK version

main

### Steps to reproduce

1. Start active navigation with `NavigationViewController` that contains valid `NavigationOptions.navigationMapView` object.
2. Observe behavior.

### Expected behavior

`NavigationMapView` instance from `NavigationOptions` should be used in `NavigationViewController`.

### Actual behavior

`NavigationMapView` instance from `NavigationOptions` is not used in `NavigationViewController`. Empty view is drawn instead.

### Is this a one-time issue or a repeatable issue?

repeatable

### PR DESCRIPTION
**Pull request by azarovalex**
Fixes #4041

### CODE REVIEW

File: Sources/MapboxNavigation/NavigationView.swift [hunk 1]
```diff
@@ -196,6 +196,7 @@ open class NavigationView: UIView {
     public init(frame: CGRect,
                 tileStoreLocation: TileStoreConfiguration.Location? = .default,
                 navigationMapView: NavigationMapView? = nil) {
+        navigationMapView?.translatesAutoresizingMaskIntoConstraints = false
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/NavigationView.swift:199]: It's also worth noting that if client sets `translatesAutoresizingMaskIntoConstraints` to `false` this issue won't happen.

I also see some potential issues with `didSet` in `NavigationView.navigationMapView`, since it'll not be called in initializers.

It's good that you've fixed original issue, but we'll have to do some more testing in the wild to see what else might be wrong. For that I think having `NavigationMapView` injection in our developer example would be good to have.
