### PR TITLE
Remove the stale style of `UserPuckCourseView`.

### LINKED ISSUE #3812: [Bug]: `UserPuckCourseView` becomes stale after starting active navigation even if location is available.
### Mapbox Navigation SDK version

main

### Steps to reproduce

1. Open Example application and modify line 187 in ViewController.swift from:
```swift
navigationMapView.userLocationStyle = .puck2D()
```
to:
```swift
navigationMapView.userLocationStyle = .courseView()
```

2. Start active navigation and stop it.
3. Wait for a couple of seconds and see how `UserPuckCourseView` changes its style.

### Expected behavior

`UserPuckCourseView` should not change its style if location is available.

### Actual behavior

`UserPuckCourseView` changes its style to stale because internally it listens to updates from `.routeControllerProgressDidChange` only.

Simulator Screen Shot - iPhone 13 - 2022-04-06 at 12 48 35

### Is this a one-time issue or a repeatable issue?

repeatable

### PR DESCRIPTION
**Pull request by ShanMa1991**
### Description
This Pr is to fix #3812 by removing the stale style of `UserPuckCourseView`.

### Implementation
Previously we had `UserPuckCourseView` listening to the `routeControllerProgressDidChange` only, and use its update time for stale styling. But because right now the `NavigationStatus` from `NavNative` navigator constantly provides status update during both passive and active navigation. The stale style of the `UserPuckCourseView` and its fading out appearance would be useless. It's deprecated and will be removed.

### CODE REVIEW

**Review by 1ec5 — APPROVED** [review]
Suggested changelog entries:

* Fixed an issue where `UserPuckCourseView`’s color desaturated during turn-by-turn navigation even as the location was being updated.
* `UserPuckCourseView` no longer desaturates its color based on the age of the last location update. `RouteController` simulates location updates whenever Location Services is unable to receive real location updates. To ensure a steady stream of location updates outside of turn-by-turn navigation, install a `PassiveLocationManager`.

File: Sources/MapboxNavigation/UserCourseView.swift [hunk 1]
```diff
@@ -79,11 +70,8 @@ open class UserPuckCourseView: UIView, CourseUpdatable {
     }
     
     // Sets the color on the user puck in 'stale' state. Puck will gradually transition the color as long as location updates are missing
-    @objc public dynamic var stalePuckColor: UIColor = #colorLiteral(red: 0.6000000238, green: 0.6000000238, blue: 0.6000000238, alpha: 1) {
-        didSet {
-            puckView.stalePuckColor = stalePuckColor
-        }
-    }
+    @available(*, deprecated, message: "No stale status in active navigation anymore.")
+    @objc public dynamic var stalePuckColor: UIColor = #colorLiteral(red: 0.6000000238, green: 0.6000000238, blue: 0.6000000238, alpha: 1)
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/UserCourseView.swift:74]: Please update `DayStyle` to stop using this property.

Comment (ShanMa1991) [reply Sources/MapboxNavigation/UserCourseView.swift:74]: Thanks for the suggestion, I'll update the style part.
