### PR TITLE
Remove route from NavNative Navigator when transition from out of Active Guidance

### LINKED ISSUE #3298: Crash: RouteController.updateIndexes(status:progress:)
Experiencing Crash using Nav SDK
Currently our top crasher
Device States: 21% occurs in background

```
Crashed: com.apple.main-thread
0  Straightaway                   0x10109a910 RouteController.updateIndexes(status:progress:) + 4347160848
1  Straightaway                   0x101099f54 RouteController.update(to:) + 4347158356
2  Straightaway                   0x1010a0104 partial apply for closure #1 in RouteController.navigationStatusDidChange(_:) + 4347183364
3  Straightaway                   0x1010571d8 thunk for @escaping @callee_guaranteed () -> () + 4346884568
4  libdispatch.dylib              0x1804e1a84 _dispatch_call_block_and_release + 32
5  libdispatch.dylib              0x1804e381c _dispatch_client_callout + 20
6  libdispatch.dylib              0x1804f1c70 _dispatch_main_queue_callback_4CF + 884
7  CoreFoundation                 0x180870340 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
8  CoreFoundation                 0x18086a218 __CFRunLoopRun + 2524
9  CoreFoundation                 0x180869308 CFRunLoopRunSpecific + 600
10 GraphicsServices               0x197eec734 GSEventRunModal + 164
11 UIKitCore                      0x1832e775c -[UIApplication _run] + 1072
12 UIKitCore                      0x1832ecfcc UIApplicationMain + 168
13 Straightaway                   0x100b71f1c main + 12 (AppDelegate.swift:12)
14 libdyld.dylib                  0x180525cf8 start + 4
```

**Mapbox Navigation SDK version:**

        "package": "MapboxNavigation",
        "repositoryURL": "https://github.com/mapbox/mapbox-navigation-ios",
        "state": {
          "branch": null,
          "revision": "40b17184f7b67f0019121cdedad190df55b9ea00",
          "version": "2.0.0-beta.21"
        }

### Steps to reproduce

Found in Crashlytics

### Expected behavior

Not Crash

### Actual behavior

Crashes

### PR DESCRIPTION
**Pull request by S2Ler**
When we start active guidance navigation, we update NavNative Navigator with the route for this session. When we end active guidance navigation, though, the route isn't reset, and NavNative continues to think that it is in the Active Guidance. It is incorrect behavior. 

This change is likely to fix #3298.

After the change, some tests started to fail more because the tests were setup in a way that more than one RouteController existed and they interfered with each other. So, I had to fix the tests as well. This work also addressed #3628. 

Even after these changes, there are still some flaky tests. Can it be related to many PassiveLocationProviders at the same time? Will investigate separately. 

_The follow-up will add a debug assertion to telegraph developers that they are not supposed to create more than one RouteController to be alive simultaneously._

### CODE REVIEW

File: Sources/MapboxCoreNavigation/RouteController.swift [hunk 1]
```diff
@@ -570,6 +570,11 @@ open class RouteController: NSObject {
         BillingHandler.shared.stopBillingSession(with: sessionUUID)
         unsubscribeNotifications()
         routeTask?.cancel()
+        Navigator.shared.navigator.setRoutesFor(nil) { _ in
```
Comment (bamx23) [inline Sources/MapboxCoreNavigation/RouteController.swift:573]: For drop-in UI, this `deinit` happens when the view controller is deallocated, which might happen after passive navigation is started. Is there a way to call this earlier?

File: Sources/MapboxNavigation/TopBannerViewController.swift [hunk 2]
```diff
@@ -353,9 +353,7 @@ extension TopBannerViewController: NavigationComponent {
         instructionsBannerView.update(for: instruction)
         lanesView.update(for: instruction)
         nextBannerView.navigationService(service, didPassVisualInstructionPoint: instruction, routeProgress: routeProgress)
-        DispatchQueue.main.async {
```
Comment (bamx23) [inline Sources/MapboxNavigation/TopBannerViewController.swift:356]: Is it guaranteed to be called on the main queue?

File: CHANGELOG.md [hunk 3]
```diff
@@ -17,6 +17,10 @@
 * Added the `RouterDelegate.router(_:initialManeuverBufferWhenReroutingFrom:)` method and related `NavigationServiceDelegate` and `NavigationViewControllerDelegate` methods to configure rerouting buffering. ([#3454](https://github.com/mapbox/mapbox-navigation-ios/pull/3454))
 * Added `RouterDelegate.router(_:requestBehaviorForReroutingWith:)` and related `NavigationServiceDelegate` and `NavigationViewControllerDelegate` methods to provide customization for rerouting mechanism by providing a user-defined route as a reroute. ([#3472](https://github.com/mapbox/mapbox-navigation-ios/pull/3472))
 
+### Location tracking
+
+* Fixed an issue where the transition from Active to Passive navigation didn't update underlying Navigator properly. It is a programmer error to have more than one active RouteController simultaneously. ([#3652](https://github.com/mapbox/mapbox-navigation-ios/pull/3652))
```
Comment (bamx23) [inline CHANGELOG.md:22]: Should we have this disclaimer here about simultaneous instances? 
And it sounds a bit strange to me. Maybe this is better?
```suggestion
* Fixed an issue where the transition from Active to Passive navigation didn't update underlying Navigator properly. It is an integration issue to have more than one active RouteController simultaneously. ([#3652](https://github.com/mapbox/mapbox-navigation-ios/pull/3652))
```

**Review by bamx23 — APPROVED** [review]

File: Sources/MapboxNavigation/TopBannerViewController.swift (hunk 2 above)
Comment (S2Ler) [reply Sources/MapboxNavigation/TopBannerViewController.swift:356]: Other views are modified here. So I would say yes. We will have a main thread sanitizer yelling at us if it won't be.

File: CHANGELOG.md (hunk 3 above)
Comment (S2Ler) [reply CHANGELOG.md:22]: > And it sounds a bit strange to me. Maybe this is better?

This is a commonly used phrase. For example, take a look on this Apple documentation: https://developer.apple.com/documentation/watchconnectivity/wcsessionactivationstate/wcsessionactivationstateinactive?changes=_2_6&language=objc

Comment (S2Ler) [reply CHANGELOG.md:22]: > Should we have this disclaimer here about simultaneous instances?

Isn't "It is a programmer error to have more than one active RouteController simultaneously." enough?

File: Sources/MapboxCoreNavigation/RouteController.swift (hunk 1 above)
Comment (S2Ler) [reply Sources/MapboxCoreNavigation/RouteController.swift:573]: I don't know how to call it earlier unless we create an explicit method. 

IMHO, We shall improve FD/AG transition similar to the Android way in v3. These modes should be tightly coupled as our underlying library is.

Comment (S2Ler) [reply Sources/MapboxCoreNavigation/RouteController.swift:573]: @1ec5 please review this code, maybe you have some suggestions.

File: CHANGELOG.md (hunk 3 above)
Comment (bamx23) [reply CHANGELOG.md:22]: Nevermind, I'm okay with this text, just didn't get the reason why dow we mention it here.

Comment (S2Ler) [reply CHANGELOG.md:22]: I have a follow up PR that will add a documentation entry related to this requirement. If this change is accepted at all.

File: Sources/MapboxCoreNavigation/RouteController.swift (hunk 1 above)
Comment (1ec5) [reply Sources/MapboxCoreNavigation/RouteController.swift:573]: Would it be possible to do some of this teardown when canceling or arriving? If there needs to be an explicit method, some kind of counterpart to `updateRoute(with:routeOptions:completion:)`, that wouldn’t be so bad as long as NavigationViewController would normally take care of calling it for the developer. Changing the behavior in this way wouldn’t necessarily be a breaking change: if an application uses RouteController directly but doesn’t call the explicit teardown method, it would just mean that #3298 would go unfixed for the application, right?

By the way, `MapboxCoreNavigation.Navigator` should encapsulate `MapboxNavigationNative.Navigator` well enough that RouteController shouldn’t have to root around `MapboxCoreNavigation.Navigator.navigator`.

> IMHO, We shall improve FD/AG transition similar to the Android way in v3. These modes should be tightly coupled as our underlying library is.

Broadly speaking, I would normally say the reverse: maybe MapboxNavigationNative needs to be less tightly coupled in the long run rather than forcing MapboxCoreNavigation to be more tightly coupled.

A developer might reasonably expect to be able to initialize a view controller and hang onto it for a while before presenting it. The more we tie underlying behavior to the lifecycle of the view controller object, the more we open ourselves up to side effects when the view controller leaks, either due to a bug in the SDK or unanticipated application behavior.

Comment (S2Ler) [reply Sources/MapboxCoreNavigation/RouteController.swift:580]: > Broadly speaking, I would normally say the reverse: maybe MapboxNavigationNative needs to be less tightly coupled in the long run rather than forcing MapboxCoreNavigation to be more tightly coupled.

> A developer might reasonably expect to be able to initialize a view controller and hang onto it for a while before presenting it. The more we tie underlying behavior to the lifecycle of the view controller object, the more we open ourselves up to side effects when the view controller leaks, either due to a bug in the SDK or unanticipated application behavior.

For you information: @mapbox/navnative

Comment (S2Ler) [reply Sources/MapboxCoreNavigation/RouteController.swift:580]: > Would it be possible to do some of this teardown when canceling or arriving? If there needs to be an explicit method, some kind of counterpart to updateRoute(with:routeOptions:completion:), that wouldn’t be so bad as long as NavigationViewController would normally take care of calling it for the developer. 

I'll try. It should be possible, yes. 

> Changing the behavior in this way wouldn’t necessarily be a breaking change: if an application uses RouteController directly but doesn’t call the explicit teardown method, it would just mean that #3298 would go unfixed for the application, right?

Yes, I think so. 

> By the way, MapboxCoreNavigation.Navigator should encapsulate MapboxNavigationNative.Navigator well enough that RouteController shouldn’t have to root around MapboxCoreNavigation.Navigator.navigator.

Agree.

Comment (S2Ler) [reply Sources/MapboxCoreNavigation/RouteController.swift]: Updated.

File: Sources/MapboxCoreNavigation/Router.swift [hunk 4]
```diff
@@ -167,6 +167,15 @@ public protocol Router: CLLocationManagerDelegate {
     func updateRoute(with indexedRouteResponse: IndexedRouteResponse,
                      routeOptions: RouteOptions?,
                      completion: ((Bool) -> Void)?)
+
+    /**
+     Asynchronously removes currently active route.
+
+     This method is called automatically by `NavigationViewController` at the end of the navigation.
+     If you use `Router` without `NavigationViewController`, you are supposed to call this method when you are done
```
Comment (bamx23) [inline Sources/MapboxCoreNavigation/Router.swift:175]: It would be great to add this to the CHANGELOG. As it was said, it's not a breaking change, but something we should proactively point developers to.

**Review by bamx23 — APPROVED** [review]

File: CHANGELOG.md [hunk 5]
```diff
@@ -29,6 +29,10 @@
 
 * Extracted `MapboxNavigationNative_Private` usage into a type alias to fix a compilation in Xcode 12.4. ([#3662](https://github.com/mapbox/mapbox-navigation-ios/pull/3662))
 
+### Location tracking
+
+* Fixed an issue where dismissing `NavigationViewController` didn't update underlying Navigator properly. If you use `RouteController` or `NavigationService` outside of `NavigationViewController` you should call `RouteController.removeRoute(completion:)` at the end of the navigation. ([#3652](https://github.com/mapbox/mapbox-navigation-ios/pull/3652))
```
Comment (1ec5) [inline CHANGELOG.md:34]: Navigator is an implementation detail:

```suggestion
* Fixed an issue where dismissing `NavigationViewController` could cause `RouteController` to crash or `PassiveLocationProvider` to behave like active turn-by-turn navigation. If you use `RouteController` or `NavigationService` outside of `NavigationViewController` you should call `RouteController.removeRoute(completion:)` at the end of the turn-by-turn navigation session. ([#3652](https://github.com/mapbox/mapbox-navigation-ios/pull/3652))
```

File: Sources/MapboxCoreNavigation/Router.swift [hunk 6]
```diff
@@ -167,6 +167,15 @@ public protocol Router: CLLocationManagerDelegate {
...
+     with `Router`.
+     */
+    func removeRoute(completion: (() -> Void)?)
```
Comment (1ec5) [inline Sources/MapboxCoreNavigation/Router.swift:178]: Should the completion handler accept a Boolean-typed success argument, similar to `updateRoute(with:options:completion:)`? It may not be necessary now, but it would be more difficult to introduce later.

**Review by 1ec5 — APPROVED** [review]

File: Sources/MapboxCoreNavigation/Router.swift (hunk 6 above)
Comment (S2Ler) [reply Sources/MapboxCoreNavigation/Router.swift:178]: I agree, thanks.

Comment (S2Ler) [reply Sources/MapboxCoreNavigation/Router.swift:178]: Although it shouldn't fail I would say.

File: CHANGELOG.md (hunk 5 above)
Comment (S2Ler) [reply CHANGELOG.md:34]: Thanks

File: Sources/MapboxCoreNavigation/Router.swift (hunk 6 above)
Comment (S2Ler) [reply Sources/MapboxCoreNavigation/Router.swift]: Done

**Review by 1ec5 — APPROVED** [review]
