### PR TITLE
Fix the memory cache loss when App in the background.

### LINKED ISSUE #3839: [Bug]: Image loss when app goes to background state.
### Mapbox Navigation SDK version

2.4.0

### Steps to reproduce

1. Start active navigation in the `Example` App choose a road with shield to drive on.
2. When the road shield shown on the bottom, go the mobile home, let the `Example` App runs in the background.
3. Go back to the `Example` App again.

### Expected behavior

The road shield stays in the bottom `WayNameView`

### Actual behavior

The road shield is gone.
memoryLoss

### Is this a one-time issue or a repeatable issue?

repeatable

### PR DESCRIPTION
**Pull request by ShanMa1991**
### Description
This PR is to fix #3839 by making the image stored in `ImageCache`, and the `SpriteInfo` in the `SpriteInfoCache` won't be discarded when App goes into the background state.

### Implementation
Right now the `SpriteInfo` in the `SpriteInfoCache` and the image in the `ImageCache` are both stored in `NSCache`. And when App goes into the background, the `NSCache` will discard its memory cache. Right now we're using the `ImageCache` for the road name shield and also the top banners. The would lead to the cached image loss. 

So this Pr wrap the `UIImage` as the `ImageMemory` and make it conform to `NSDiscardableContent` and won't allowed it to be discarded, same as the `SpriteInfoWrapper`. So when the App goes to the background and then back, the cached images and `SpriteInfo` would still be available.

### Screenshots or Gifs
keepMemory

### CODE REVIEW

File: Sources/MapboxNavigation/ImageCache.swift [hunk 1]
```diff
@@ -1,11 +1,23 @@
 import UIKit
 
+internal class ImageMemory: NSObject, NSDiscardableContent {
+    func beginContentAccess() -> Bool { return true }
+    func endContentAccess() { }
+    func discardContentIfPossible() {}
```
Comment (Udumft) [inline Sources/MapboxNavigation/ImageCache.swift:6]: Doesn't that result in images data being never evicted? Should we still clear this cache at some point? For example after app was shut down or after some disk quota exceeded?

Comment (ShanMa1991) [reply Sources/MapboxNavigation/ImageCache.swift:6]: We clear the memory when the `style` change or when `traitCollection` change. because it's used in `WayNameView` and `InstructionLabel` right now. The `NSDiscardableContent` only prevents the cached content removing when App goes to the background. But because we don't store it to the disk. When the App is shut down, it will be cleared as well.

File: CHANGELOG.md [hunk 2]
```diff
@@ -10,6 +10,7 @@
 
 * Fixed an issue where `UserPuckCourseView`’s color desaturated during turn-by-turn navigation even as the location was being updated. ([#3836](https://github.com/mapbox/mapbox-navigation-ios/pull/3836))
 * `UserPuckCourseView` no longer desaturates its color based on the age of the last location update. `RouteController` simulates location updates whenever Location Services is unable to receive real location updates. To ensure a steady stream of location updates outside of turn-by-turn navigation, install a `PassiveLocationManager`. ([#3836](https://github.com/mapbox/mapbox-navigation-ios/pull/3836))
+* Fixed the image cache loss when App goes to background. ([#3840](https://github.com/mapbox/mapbox-navigation-ios/pull/3840))
```
Comment (1ec5) [inline CHANGELOG.md:13]:
```suggestion
* Fixed an issue where shields disappeared after the application returns to the foreground. ([#3840](https://github.com/mapbox/mapbox-navigation-ios/pull/3840))
```

**Review by 1ec5 — APPROVED** [review]

File: CHANGELOG.md (hunk 2 above)
Comment (ShanMa1991) [reply CHANGELOG.md]: Thanks for the suggestion, I'll update the ChangeLog.
