### PR TITLE
Fixed an issue related to `StyleManager` usage on iOS and CarPlay.

### LINKED ISSUE #3883: [Bug]: Style changes that are made via `StyleManager` on CarPlay cause changes on iOS as well.
### Mapbox Navigation SDK version

main

### Steps to reproduce

1. Add this code to `CarPlayMapViewController`'s `viewDidLoad()` method:
```swift
DispatchQueue.main.asyncAfter(deadline: .now() + 5.0) {
    self.styleManager?.applyStyle(type: .night)
}
```

1. Start Example-CarPlay and open CarPlay application, wait till application changes its style (after 5 seconds).
2. During style change see how iOS counterpart behaves.

### Expected behavior

iOS application should not change its style to dark.

### Actual behavior

iOS application changes its style to dark (e.g. feedback button).

### Is this a one-time issue or a repeatable issue?

repeatable

### PR DESCRIPTION
**Pull request by MaximAlien**
### Description

Fixes #3883.

PR fixes an issue where changes to `StyleManager` on one platform caused instant style updates on other platform as well.

### CODE REVIEW

File: Sources/MapboxNavigation/StyleManager.swift [hunk 1]
```diff
@@ -58,7 +59,23 @@ open class StyleManager {
...
+     update style whenever it changes only for that specific user interface idiom (e.g. when changing
+     style on CarPlay, style on iOS should remain unchanged).
+     */
+    var traitCollection: UITraitCollection?
+    
     public init() {
+        commonInit()
+    }
+    
+    init(_ traitCollection: UITraitCollection) {
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/StyleManager.swift:73]: Don't see any better way for `StyleManager` to know for what platform it was created.

**Review by Udumft — APPROVED** [review]
LGTM

File: CHANGELOG.md [hunk 2]
```diff
@@ -14,6 +14,7 @@
 
 * Fixed an issue where shields would become invisible when users drive through the tunnel. ([#3882](https://github.com/mapbox/mapbox-navigation-ios/pull/3882))
 * Added the ability to change map style depending on the option that was set in `Always show dark maps`. ([#3882](https://github.com/mapbox/mapbox-navigation-ios/pull/3882))
+* Fixed an issue where `StyleManager` appearance update on CarPlay would cause appearance update on iOS as well. ([#3914](https://github.com/mapbox/mapbox-navigation-ios/pull/3914))
```
Comment (1ec5) [inline CHANGELOG.md:17]:
```suggestion
* Fixed an issue where a `StyleManager` for CarPlay would update the appearance on both CarPlay and the iOS device simultaneously. ([#3914](https://github.com/mapbox/mapbox-navigation-ios/pull/3914))
```

File: Sources/MapboxNavigation/StyleManager.swift (hunk 1 above)
Comment (1ec5) [inline Sources/MapboxNavigation/StyleManager.swift:73]: Nit: Remove the `_`. Label-less arguments are only for situations where doing so would allow the call site to read like a natural sentence. This is rarely the case for initializers.

File: Sources/MapboxNavigation/StyleManager.swift [hunk 3]
```diff
@@ -193,18 +210,38 @@ open class StyleManager {
...
+        } else {
+            refreshAppearance(for: UIApplication.shared.windows)
         }
         
         delegate?.styleManagerDidRefreshAppearance(self)
     }
+    
+    func refreshAppearance(for windows: [UIWindow]) {
+        // Workaround to refresh appearance by removing all views and then adding them again.
+        // UITextEffectsWindow will be created when system keyboard is shown and cannot be safely removed.
```
Comment (1ec5) [inline Sources/MapboxNavigation/StyleManager.swift:235]: Nit: This is basically a documentation comment.

```suggestion
    /**
     Workaround to refresh appearance by removing all views and then adding them again.
     UITextEffectsWindow will be created when system keyboard is shown and cannot be safely removed.
     */
    func refreshAppearance(for windows: [UIWindow]) {
```

**Review by 1ec5 — APPROVED** [review]

**Review by MaximAlien — COMMENTED** [review]
Unfortunately this PR doesn't fully fix the problem (it allows to prevent style update of the window itself by picking the right one for specific platform). `.carPlay` and `.phone` user interface idioms should be fully independent for default `DayStyle` and `NightStyle`. At this point style updates of some views that are reused across CarPlay and iOS cause global changes for all platforms. This will be fixed in scope of https://github.com/mapbox/mapbox-navigation-ios/issues/3917.
