### PR TITLE
Fix #3056 RouteController shouldDiscard location logic

### LINKED ISSUE #3056: [Bug] RouterDelegate.router(_:shouldDiscard:) handled incorrectly
**Mapbox Navigation SDK version:** "release-v2.0 branch"
https://github.com/mapbox/mapbox-navigation-ios/blob/bb6c0c1d3e69b765aa986a18eb8fa98a775802eb/Sources/MapboxCoreNavigation/RouteController.swift#L247-L252

This code seems to have inverted logic. If `shouldDiscard` returns true, then the discard won't happen. And visa versa.

### PR DESCRIPTION
**Pull request by S2Ler**
This is kind of bug with a "breaking change" fix because some users can depend on this bug now as our tests have shown.

### CODE REVIEW

File: Sources/MapboxCoreNavigation/RouteController.swift [hunk 1]
```diff
@@ -247,7 +247,7 @@ open class RouteController: NSObject {
     public func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
         guard let location = locations.last else { return }
         
-        guard delegate?.router(self, shouldDiscard: location) ?? DefaultBehavior.shouldDiscardLocation else {
+        guard !(delegate?.router(self, shouldDiscard: location) ?? DefaultBehavior.shouldDiscardLocation) else {
```
Comment (Udumft) [inline Sources/MapboxCoreNavigation/RouteController.swift:250]: Maybe we should also invert `DefaultBehavior.shouldDiscardLocation` to maintain existing 'default' behavior? This will not only also make the fix 'less breaking' since many users rely on defaults but also won't require that many unit tests changes below

File: Tests/MapboxCoreNavigationTests/RouteControllerTests.swift [hunk 2]
```diff
@@ -65,3 +68,13 @@ extension RouteControllerTests: RouterDataSource {
         return NavigationLocationManager.self
     }
 }
+
+extension RouteControllerTests: RouterDelegate {
+    func router(_ router: Router, didRefresh routeProgress: RouteProgress) {
```
Comment (Udumft) [inline Tests/MapboxCoreNavigationTests/RouteControllerTests.swift:73]: Why did you add this implementation too?

**Comment by zugaldia** [comment]
Looks like this is one we want to highlight in the release notes too.

File: Tests/MapboxCoreNavigationTests/RouteControllerTests.swift (hunk 2 above)
Comment (S2Ler) [reply Tests/MapboxCoreNavigationTests/RouteControllerTests.swift:73]: Xcode said that I must implement this method, I will remove and check again, Thanks.

File: Sources/MapboxCoreNavigation/RouteController.swift (hunk 1 above)
Comment (S2Ler) [reply Sources/MapboxCoreNavigation/RouteController.swift:250]: Great idea! I will give it a try.

File: CHANGELOG.md [hunk 3]
```diff
@@ -99,6 +99,7 @@
 * Fixed an issue where 'Navigation cancel' event might be not logged. ([#3050](https://github.com/mapbox/mapbox-navigation-ios/pull/3050))
 * Fixed an issue where offline route calculation might hang up. ([#3040](https://github.com/mapbox/mapbox-navigation-ios/pull/3040))
 * Fixed the moment of custom feedback event creation. ([#3049](https://github.com/mapbox/mapbox-navigation-ios/pull/3049))
+* Fixed `RouterDelegate.router(_:shouldDiscard:)` handling. If you implement this method, you will need to reverse the value you return from this method. Previously, if you returned `true`, the `Router` wouldn't discard the location.
```
Comment (Udumft) [inline CHANGELOG.md:102]:
```suggestion
* Fixed a bug in `RouterDelegate.router(_:shouldDiscard:)` handling. If you implemented this method, you will need to reverse the value you return. Previously, if you returned `true`, the `Router` wouldn't discard the location. ([#3058](https://github.com/mapbox/mapbox-navigation-ios/pull/3058))
```

**Review by Udumft — APPROVED** [review]
LGTM with NIT correction.

File: CHANGELOG.md (hunk 3 above)
Comment (S2Ler) [reply CHANGELOG.md]: Thank you for the fix!
