### PR TITLE
Fix issues with calling NavigationViewControllerDelegate methods.

### LINKED ISSUE #2962: Waypoint styling delegate methods in NavigationViewController are not called.
**Mapbox Navigation SDK version:** `release-v2.0`

### Steps to reproduce

 1. Run https://github.com/mapbox/mapbox-navigation-ios-examples/blob/release-v2.0/Navigation-Examples/Examples/Custom-Waypoints.swift.
 2. Start active guidance navigation.
 3. Observe how intermediate waypoint is drawn.

### Expected behavior

Waypoint in `NavigationViewController` should be drawn similarly to `NavigationMapView`.

### Actual behavior

[These](https://github.com/mapbox/mapbox-navigation-ios-examples/blob/671564bb4c014168794a5e5c87483b601eb3e48e/Navigation-Examples/Examples/Custom-Waypoints.swift#L186-L198) styling methods are not called.

### PR DESCRIPTION
**Pull request by MaximAlien**
After dropping `RouteMapViewController` certain `NavigationViewControllerDelegate` delegate methods were not called anymore.

Fixes #2962.

### CODE REVIEW

File: Sources/MapboxNavigation/NavigationViewControllerDelegate.swift [hunk 1]
```diff
@@ -165,14 +165,6 @@ public protocol NavigationViewControllerDelegate: VisualInstructionDelegate {
      */
     func navigationViewController(_ navigationViewController: NavigationViewController, shapeFor waypoints: [Waypoint], legIndex: Int) -> FeatureCollection?
     
-    /**
-     Called when the user taps to select a route on the navigation view controller’s map view.
-     
-     - parameter navigationViewController: The navigation view controller presenting the route that the user selected.
-     - parameter route: The route on the map that the user selected.
-     */
-    func navigationViewController(_ navigationViewController: NavigationViewController, didSelect route: Route)
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/NavigationViewControllerDelegate.swift:174]: Since `NavigationViewController` only allows to show one route this method is not relevant and is not used anywhere.

**Review by ShanMa1991 — APPROVED** [review]
