### PR TITLE
Replace ImageCache, DataCache with URLCache

### LINKED ISSUE #3841: Replace ImageCache, DataCache with URLCache
ImageCache and DataCache currently store their contents in NSCache, which has an overly aggressive eviction policy for the kinds of resources we put in it. #3840 would adjust the eviction policy using NSDiscardableContent as a stopgap fix for unexpected eviction while in the background (#3839). In the medium term, we should replace our use of these classes with URLCache, which has more appropriate eviction behavior by default and integrates with URLRequest so that there’s no need to come up with our own caching keys. It also has simple controls for maximum memory and disk usage, so we don’t need to explicitly purge the cache.

Currently, the only resources not tied to URLs are generic shield images, which we can composite on demand without noticeably impacting performance. We should wean these resources off caching altogether. Then everything else can be tied to the request URLs.

For forward compatibility, our use of URLCache should be kept as an internal implementation detail. If we have to expose a cache publicly, we should expose it through a protocol such as `BimodalCache` in case there’s ever a need to replace the URLCache with a lower-level solution that’s unified with tile caching. However, for the time being, I think it’s fine to use a different solution for transient resources than we do for more expensive resources like tiles.

https://github.com/mapbox/mapbox-navigation-ios/blob/1bbdc3a7166e89caaf0d1c1dffc0a3a0ac63936c/Sources/MapboxNavigation/ImageCache.swift#L4 https://github.com/mapbox/mapbox-navigation-ios/blob/1bbdc3a7166e89caaf0d1c1dffc0a3a0ac63936c/Sources/MapboxNavigation/DataCache.swift#L4

/cc @mapbox/navigation-ios @abhishek1508 @LukasPaczos

### LINKED ISSUE #4001: [Bug]: Mapbox designed shield changes its style on both iOS and CarPlay at the same time.
### Mapbox Navigation SDK version

v2.7.0-alpha.1

### Steps to reproduce

1. Open example application on iOS and CarPlay.
2. Request route that contains `GenericRouteShield`s. 
3. Start active navigation.
4. Change appearance in CarPlay settings. 
5. Observe behavior.

### Expected behavior

`GenericRouteShield` style should be changed only on CarPlay.

### Actual behavior

`GenericRouteShield` changes its style on both iOS and CarPlay.

### Is this a one-time issue or a repeatable issue?

repeatable

### PR DESCRIPTION
**Pull request by ShanMa1991**
### Description

- This pr is to fix #3841 by replacing ImageCache, DataCache with URLCache.
- This PR is also to fix #4001 by adding the `UIUserInterfaceIdiom` information to `SpriteRepository`, so different device could use separate styles.
- This Pr also align the size of Mapbox designed shields, legacy shields, exit views and generic shields in instruction banner by resizing the  Mapbox designed shields, legacy shields through the `UIImage.scale(to:)` in `InstructionPresenter`

### Implementation
For `DataCache`,  it's only used for the speech caching from the result of `SpeechSynthesizer.audioData(with:completionHandler:)`  from `MapboxSpeech`. It only receives the data and error information. So the `URLCache` is not capable in this case. 

For the `ImageCache`, when used in `ImageRepository`, it's only responsible for the `JunctionView` update, and it already supports the local disk caching. So it won't be changed.

In `SpriteRepository`, the previous `spriteCache`, `legacyCache` and `infoCache` is replaced with the `derivedCache` as `ImageCache` and `requestCache` of a `URLCache`.  The `requestCache` is used to store downloaded Sprite image, Sprite Info and single legacy shields. The `derivedCache` is used to store the generated generic shields, exit views and the single sprite shield icon.

The `UIUserInterfaceIdiom` is added to `SpriteRepository` to request style update and images. When the device is CarPlay, it will use the `.carPlay`  UIUserInterfaceIdiom, otherwise, others will all use the default `,phone`.

### Screenshots or Gifs
The `Night` style for CarPlay in the gray background shield in the instruction:
carPlay_night

The `Day` style for mobile in the white background shield in the instruction:
mobile_day

### CODE REVIEW

File: Sources/MapboxNavigation/SpriteRepository.swift [hunk 1]
```diff
@@ -22,47 +19,49 @@ class SpriteRepository {
...
+    func urlRequest(with url: URL) -> URLRequest {
+        var request = URLRequest(url: url)
+        request.allHTTPHeaderFields = self.headers
+        request.cachePolicy = .reloadIgnoringCacheData
+        request.setValue(URLSession.userAgent, forHTTPHeaderField: "User-Agent")
+        return request
+    }
+    
     func updateStyle(styleURI: StyleURI?, completion: @escaping CompletionHandler) {
+        resetStyleCache()
```
Comment (ShanMa1991) [inline Sources/MapboxNavigation/SpriteRepository.swift:35]: Only clear the Sprite cache when style changes.

File: Sources/MapboxNavigation/RequestDownload.swift [hunk 2]
```diff
@@ -6,14 +6,14 @@ enum DownloadError: Error {
     case noImageData
 }
 
-protocol ImageDownload: URLSessionDataDelegate {
+protocol RequestDownload: URLSessionDataDelegate {
     init(request: URLRequest, in session: URLSession)
-    func addCompletion(_ completion: @escaping ImageDownloadCompletionBlock)
+    func addCompletion(_ completion: @escaping CachedResponseCompletionBlock)
```
Comment (ShanMa1991) [inline Sources/MapboxNavigation/RequestDownload.swift:11]: Update the `ImageDownload` to a more generic `RequestDownload`. The repository will be responsible for generating urlRequest and converting data to image.

File: Sources/MapboxNavigation/SpriteRepository.swift [hunk 3]
```diff
@@ -4,16 +4,13 @@ import MapboxCoreNavigation
...
-    let legacyCache = ImageCache()
-    // Caching the metadata info for Sprite.
-    let infoCache =  SpriteInfoCache()
     let baseURL: URL = URL(string: "https://api.mapbox.com/styles/v1")!
     var styleURI: StyleURI = .navigationDay
-    fileprivate(set) var imageDownloader: ReentrantImageDownloader = ImageDownloader()
+    fileprivate(set) var requestDownloader: ReentrantRequestDownloader = RequestDownloader()
+    private let headers: [String: String] = ["Accept": "image/*;q=0.8"]
     
+    let requestCache: BimodalURLCache = URLDataCache()
```
Comment (ShanMa1991) [inline Sources/MapboxNavigation/SpriteRepository.swift:12]: Use the requestCache to store downloaded Sprite image, Sprite Info and single legacy shield. The derivedCache is used to store the generated shield, exit views and the single sprite shield icon.

File: Sources/MapboxNavigation/Cache.swift [hunk 4]
```diff
@@ -27,6 +27,52 @@ public protocol BimodalDataCache: BimodalCache {
...
+}
+
+/**
+ A general purpose URLCache used by `SpriteRepository` implementations.
+ */
+internal class URLDataCache: BimodalURLCache {
+    let capcity = 10 * 1024 * 1024
+    let diskCacheURL: URL = {
+        let fileManager = FileManager.default
+        let basePath = fileManager.urls(for: .documentDirectory, in: .userDomainMask).first!
```
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/Cache.swift:44]: So do you think it's better that we use the `cachesDirectory` for the urlCache files? Because we could always re-download it and don't need the back-up for it.

File: Sources/MapboxNavigation/ImageRepository.swift [hunk 5]
```diff
@@ -39,8 +48,11 @@ class ImageRepository {
             return
         }
 
-        let _ = imageDownloader.downloadImage(with: imageURL, completion: { [weak self] (image, data, error) in
-            guard let strongSelf = self, let image = image else {
+        let request = urlRequest(with: imageURL)
+        let _ = requestDownloader.download(with: request, completion: { [weak self] (cachedResponse, error) in
+            guard let strongSelf = self,
+                  let data = cachedResponse?.data,
+                  let image = UIImage(data: data, scale: UIScreen.main.scale) else {
```
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/ImageRepository.swift:55]: We may make it another ticket to handle all the `UIScreen.main.scale` for the new beta version.

File: Sources/MapboxNavigation/SpriteRepository.swift [hunk 6]
```diff
@@ -113,95 +97,141 @@ class SpriteRepository {
...
+        
+        return spriteInfoDictionary[key]
     }
+    
+    func parseSpriteInfo(data: Data) -> [String: SpriteInfo]? {
+        do {
+            let decodedObject = try JSONDecoder().decode([String : SpriteInfo].self, from: data)
+            return decodedObject
+        } catch {
+            NSLog("Failed to parse requested data to Sprite info due to: \(error.localizedDescription).")
```
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/SpriteRepository.swift:206]: We could update this part when #3944 landed.

File: Sources/MapboxNavigation/ImageRepository.swift (hunk 5 above)
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/ImageRepository.swift:55]: So from `Directions` side to our side, we all request images based on the `UIScreen.main.scale` for iOS. And in our side, we also parse the data to image with the `UIScreen.main.scale`. so it should be fine because they're consistent.

File: Sources/MapboxNavigation/Cache.swift [hunk 7]
```diff
@@ -27,6 +27,51 @@ public protocol BimodalDataCache: BimodalCache {
...
+        return basePath.appendingPathComponent(identifier + ".URLCacheFiles")
+    }()
+    
+    let urlCache: URLCache
+    
+    init() {
+        if #available(iOS 13.0, *) {
+            urlCache = URLCache(memoryCapacity: 5 * 1024 * 1024, diskCapacity: 5 * 1024 * 1024, directory: diskCacheURL)
+        } else {
+            urlCache = URLCache()
```
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/Cache.swift:54]: Yes. Thanks for the suggestion, the `URLCache(memoryCapacity:diskCapacity:diskPath:)` for lower iOS version will be used to provide the path.

File: Sources/MapboxNavigation/Cache.swift [hunk 8]
```diff
@@ -27,6 +27,51 @@ public protocol BimodalDataCache: BimodalCache {
...
+
+/**
+ A general purpose URLCache used by `SpriteRepository` implementations.
+ */
+internal class URLDataCache: BimodalURLCache {
+    let diskCacheURL: URL = {
+        let fileManager = FileManager.default
+        let basePath = fileManager.urls(for: .cachesDirectory, in: .userDomainMask).first!
+        let identifier = Bundle.mapboxNavigation.bundleIdentifier!
+        return basePath.appendingPathComponent(identifier + ".URLCacheFiles")
```
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/Cache.swift:45]: If we have multiple `URLDataCache`, I think we should have a `name` parameter for the initializer and add it to the directory. But the issue right now is that we only have one `URLDataCache` used in `SpriteRepository`. And `SpriteRepository` is used as a singleton across the NavSDK. So I think it should be fine right now?

File: Sources/MapboxNavigation/InstructionPresenter.swift [hunk 9]
```diff
@@ -265,7 +263,7 @@ class InstructionPresenter {
             genericRouteShield.cornerRadius = appearance.cornerRadius
             
             guard let image = takeSnapshot(on: genericRouteShield) else { return nil }
-            spriteRepository.legacyCache.store(image, forKey: key, toDisk: false, completion: nil)
+            spriteRepository.derivedCache.store(image, forKey: key, toDisk: true, completion: nil)
```
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/InstructionPresenter.swift:266]: Because the `legacyCache` we used to have is used to store all the legacy shield icons and the generated exit views and generic shields, along with the SpritInfoCache and the SpriteCache. Right now we have the `derivedCache` to store the generated shields and the single cut Sprite shield icons. So they have different functions. And also now it defaults to save the generated ones to disk in the `ImageCache`, which would avoid the re-downloading when the memory capacity is reached and memory is cleared out.

**Comment by ShanMa1991** [comment]
> Don't forget to add a changelog entry.

Because the `SpriteRepository` is not public, the newly added cache type is internal. There won't be any changes to users. I'm not sure what to add to the changelog.

File: Sources/MapboxNavigation/SpriteRepository.swift (hunk 6 above)
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/SpriteRepository.swift]: Thanks for the notification, it's updated.

**Review by 1ec5 — COMMENTED** [review]
> I'm not sure what to add to the changelog.

Does this refactor improve upon #3840 by persisting the resources after quitting and relaunching the application? That’s the only thing I can think of; otherwise, it’d be fine to leave these changes out of the changelog.

File: Sources/MapboxNavigation/SpriteRepository.swift [hunk 10]
```diff
@@ -22,47 +19,63 @@ class SpriteRepository {
...
+                  derivedCache: BimodalImageCache = ImageCache()) {
+        requestDownloader = downloader
+        self.requestCache = requestCache
+        self.derivedCache = derivedCache
+    }
+    
+    func urlRequest(with url: URL) -> URLRequest {
+        var request = URLRequest(url: url)
+        request.allHTTPHeaderFields = self.headers
+        request.cachePolicy = .reloadIgnoringCacheData
```
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/SpriteRepository.swift:37]: Because we check whether the response is cached in the `URLCache` before the downloading. Only when it's not cached, we send the urlRequest to download the images and metadata to the `URLCache`. And the `URLCache` won't discard the response when the cachePolicy is `. reloadIgnoringCacheData `.

File: Sources/MapboxNavigation/Cache.swift [hunk 11]
```diff
@@ -27,6 +27,51 @@ public protocol BimodalDataCache: BimodalCache {
     func data(forKey: String?) -> Data?
 }
 
+protocol BimodalURLCache {
```
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/Cache.swift:30]: Thanks for the suggestion, I'll rename this protocol and add tests for the `URLDataCache`.

File: Sources/MapboxNavigation/SpriteRepository.swift (hunk 10 above)
[the remark this answers is not in the document]
Comment (1ec5) [reply Sources/MapboxNavigation/SpriteRepository.swift:37]: Does this mean we don’t need to explicit check beforehand whether something is in the cache if we use a different policy? Relying on the cache to do that check automatically could reduce the potential for errors on our side, in case in the future there’s a code path in which we neglect to check first. On the other hand, the default policy is dependent on the correct caching headers being sent by the server; I’m unsure if relying on the current headers would result in the same behavior as that explicit check.

File: Sources/MapboxNavigation/Cache.swift (hunk 8 above)
[the remark this answers is not in the document]
Comment (1ec5) [reply Sources/MapboxNavigation/Cache.swift:45]: This path would place the files in a folder called “com.mapbox.MapboxNavigation.URLCacheFiles”, but most of the other folders under Caches are named according to a bundle identifier by itself. If the intention is to separate the URLCache files from other files that may be cached by other parts of this library, then it should be in a subfolder of the “com.mapbox.MapboxNavigation” folder. I’d go ahead and name it after the class that’s using this cache as well.

```suggestion
        return basePath.appendingPathComponent(identifier).appendingPathComponent("URLDataCache")
```

File: Sources/MapboxNavigation/SpriteRepository.swift (hunk 10 above)
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/SpriteRepository.swift:37]: Yes. If we choose other policy such as the default `.useProtocolCachePolicy`, it would automatically check the existence of the cache when downloading without the manually check. But the issue is that if we don't use the manually check, they'll all call the `RequestDownloader` to download and are added to the download queue. But if we manually check the existence of the URLCaChe, then it would skip the downloading process and return the image and info more quickly directly from the cache. It follows the same logic as the `ImageRepository` for handling image as before.

**Comment by MaximAlien** [comment]
@ShanMa1991, sorry, looks like https://github.com/mapbox/mapbox-navigation-ios/pull/4004 brought multiple conflicts with your current PR. Would you be able to resolve them? (let me know if any help is needed)

**Comment by ShanMa1991** [comment]
@MaximAlien Thanks for the reminder, currently it's rebased to catch the change from #4004

File: Sources/MapboxNavigation/Cache.swift [hunk 12]
```diff
@@ -27,6 +27,51 @@ public protocol BimodalDataCache: BimodalCache {
...
+        let basePath = fileManager.urls(for: .cachesDirectory, in: .userDomainMask).first!
+        let identifier = Bundle.mapboxNavigation.bundleIdentifier!
+        return basePath.appendingPathComponent(identifier).appendingPathComponent("URLDataCache")
+    }()
+    
+    let urlCache: URLCache
+    
+    init() {
+        if #available(iOS 13.0, *) {
+            urlCache = URLCache(memoryCapacity: 5 * 1024 * 1024, diskCapacity: 5 * 1024 * 1024, directory: diskCacheURL)
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/Cache.swift:52]: We can expose initializer that allows to set `memoryCapacity` and `diskCapacity` as well. These constants can also be extracted into separate constants to prevent duplication.

File: Tests/MapboxNavigationTests/URLDataCacheTests.swift [hunk 13]
```diff
@@ -0,0 +1,87 @@
...
+    }
+    
+    private func exampleResponse(with storagePolicy: URLCache.StoragePolicy) -> CachedURLResponse {
+        let data = Fixture.JSONFromFileNamed(name: "sprite-info")
+        let response = URLResponse(url: url, mimeType: nil, expectedContentLength: data.count, textEncodingName: nil)
+        let cachedResponse = CachedURLResponse(response: response, data: data, storagePolicy: storagePolicy)
+        return cachedResponse
+    }
+    
+    private func urlRequest(with url: URL) -> URLRequest {
```
Comment (MaximAlien) [inline Tests/MapboxNavigationTests/URLDataCacheTests.swift:23]: This method is duplicated three times. We can create `URLRequest` extension and move it there to prevent duplication.

File: Tests/MapboxNavigationTests/URLDataCacheTests.swift [hunk 14]
```diff
@@ -0,0 +1,87 @@
...
+        let request = urlRequest(with: url)
+        
+        cache.store(response, for: request)
+        XCTAssertNotNil(cache.response(for: request))
+        
+        cache.removeCache(for: request)
+        XCTAssertNil(cache.response(for: request)?.data)
+    }
+
+    func testStoreCacheInMemoryOnly() {
```
Comment (MaximAlien) [inline Tests/MapboxNavigationTests/URLDataCacheTests.swift:65]: We can also create stress test that generates response that is larger than allowed `memoryCapacity` and `diskCapacity` to verify that there are no leaks and cache behaves correctly.

File: Sources/MapboxNavigation/ImageRepository.swift (hunk 5 above)
[the remark this answers is not in the document]
Comment (MaximAlien) [reply Sources/MapboxNavigation/ImageRepository.swift:55]: Scale factor might be different on iOS and CarPlay. `ImageRepository` should be aware of that to correctly generate image. In case of CarPlay we can use `UIScreen.mainCarPlay` extension.

File: CHANGELOG.md [hunk 15]
```diff
@@ -25,6 +25,7 @@
 
 * Fixed the unmatched language issue of some localized strings in the feedback view. ([#4007](https://github.com/mapbox/mapbox-navigation-ios/pull/4007))
 * Added `NavigationSettings.utilizeSensorData` toggle to allow navigator to use additional device sensors data for better positioning. ([#3973](https://github.com/mapbox/mapbox-navigation-ios/pull/3973))
+* Kept the road shield image resources after quiting and relaudnching the application. ([#3930](https://github.com/mapbox/mapbox-navigation-ios/pull/3930))
```
Comment (MaximAlien) [inline CHANGELOG.md:28]: Proposed changelog entry:
```suggestion
* Road shield images are now cached and re-used across multiple application sessions. ([#3930](https://github.com/mapbox/mapbox-navigation-ios/pull/3930))
```

File: Sources/MapboxNavigation/Cache.swift (hunk 12 above)
Comment (ShanMa1991) [reply Sources/MapboxNavigation/Cache.swift]: Thanks for the suggestion, the parameter for `memoryCapacity` and `diskCapacity`  are added. I'll add test for the capacity limit.

File: Tests/MapboxNavigationTests/URLDataCacheTests.swift (hunk 13 above)
Comment (ShanMa1991) [reply Tests/MapboxNavigationTests/URLDataCacheTests.swift]: Thanks for the suggestion, the extension of `URLRequest.init(_:)` is added and the functions are removed.

File: Sources/MapboxNavigation/ImageRepository.swift (hunk 5 above)
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/ImageRepository.swift:46]: Because different platforms may have different scale factors. The `SpriteRepository` is used as a singleton across the platform. #4001 will add the ability to cache and provide the images for different platform with its scale factor. The issue will be solved by #4001

File: CHANGELOG.md (hunk 15 above)
Comment (ShanMa1991) [reply CHANGELOG.md]: Thanks for the suggestion, the changeLog entry is added

File: Tests/MapboxNavigationTests/URLDataCacheTests.swift (hunk 14 above)
Comment (ShanMa1991) [reply Tests/MapboxNavigationTests/URLDataCacheTests.swift:57]: Thanks for the suggestion, the limit unit test is added.

File: MapboxNavigation.xcodeproj/project.pbxproj [hunk 16]
```diff
@@ -937,6 +938,9 @@
 		B419BFF125F00A9C0086639B /* Feature.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = Feature.swift; sourceTree = "<group>"; };
 		B430D2F925534FDC0088CC23 /* UserHaloCourseView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = UserHaloCourseView.swift; sourceTree = "<group>"; };
 		B4319F2E27A35EA8005A706E /* SpriteRepository.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = SpriteRepository.swift; sourceTree = "<group>"; };
+		B432985C28D53A6F005AFB98 /* URLRequest.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; path = URLRequest.swift; sourceTree = "<group>"; };
+		B432985E28D53AB8005AFB98 /* URLSessionDelegateProxy.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; path = URLSessionDelegateProxy.swift; sourceTree = "<group>"; };
```
Comment (ShanMa1991) [inline MapboxNavigation.xcodeproj/project.pbxproj:942]: It's introduced by #3782 but not added.

File: Sources/MapboxNavigation/WayNameLabel.swift [hunk 17]
```diff
@@ -21,25 +21,26 @@ open class WayNameLabel: StylableLabel {
     @objc dynamic public var roadShieldDefaultColor: UIColor = .roadShieldDefaultColor
     
     // When the map style changes, update the sprite repository and the label.
-    func updateStyle(styleURI: StyleURI?) {
-        spriteRepository.updateStyle(styleURI: styleURI) { [weak self] _ in
-            guard let self = self,
-                  let roadName = self.text else { return }
+    func updateStyle(styleURI: StyleURI?, idiom: UIUserInterfaceIdiom = .phone) {
+        spriteRepository.updateStyle(styleURI: styleURI, idiom: idiom) { [weak self] _ in
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/WayNameLabel.swift:25]: Do we really need to wait for completion handler to call `self.setup(with: roadName, idiom: idiom)`?

File: Sources/MapboxNavigation/SpriteRepository.swift [hunk 18]
```diff
@@ -4,79 +4,93 @@ import MapboxCoreNavigation
...
+    func updateStyle(styleURI: StyleURI?,
+                     idiom: UIUserInterfaceIdiom = .phone,
+                     completion: @escaping ImageDownloadCompletionHandler) {
         // If no valid StyleURI provided, use the default Day style.
-        let newStyleURI = styleURI ?? self.styleURI
-        guard newStyleURI != self.styleURI || getSpriteImage() == nil else {
+        let newStyleURI = styleURI ?? defaultStyleURI
+        
+        if !userInterfaceIdiomStyles.values.contains(newStyleURI) {
+            updateUserInterfaceIdiomStyles(styleURI: newStyleURI, idiom: idiom)
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/SpriteRepository.swift:40]: `updateUserInterfaceIdiomStyles(styleURI: newStyleURI, idiom: idiom)` is called in both cases, can it be moved outside of condition check?

File: Sources/MapboxNavigation/SpriteRepository.swift [hunk 19]
```diff
@@ -4,79 +4,93 @@ import MapboxCoreNavigation
...
-        // Update the styleURI just after the Sprite memory reset. When the connection is poor, the next round of style update
-        // or the representation update could use the correct ones.
-        self.styleURI = newStyleURI
-        updateSprite(completion: completion)
+    }
+    
+    func updateUserInterfaceIdiomStyles(styleURI: StyleURI, idiom: UIUserInterfaceIdiom) {
+        if let previousStyleURI = userInterfaceIdiomStyles[idiom],
+           previousStyleURI != styleURI {
+            userInterfaceIdiomStyles[idiom] = styleURI
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/SpriteRepository.swift:52]: Can we call `userInterfaceIdiomStyles[idiom] = styleURI` once at the beginning of this method?

File: Sources/MapboxNavigation/InstructionPresenter.swift [hunk 20]
```diff
@@ -212,38 +220,43 @@ class InstructionPresenter {
...
         attachment.font = dataSource.font
         let shieldColor = dataSource.shieldColor(from: shield.textColor)
         let fontSize = dataSource.font.with(multiplier: 0.4)
-        attachment.image = cachedImage.withCenteredText(shield.text,
-                                                        color: shieldColor,
-                                                        font: fontSize)
+        let shieldWithCenteredText = cachedImage.withCenteredText(shield.text,
+                                                                  color: shieldColor,
+                                                                  font: fontSize)
+        let image = shieldWithCenteredText.scale(to: dataSource.font.pointSize * 1.2)
```
Comment (MaximAlien) [inline Sources/MapboxNavigation/InstructionPresenter.swift:244]: It'd be good to extract `1.2` into separate constant as it's called from two places.

**Review by MaximAlien — APPROVED** [review]

File: Sources/MapboxNavigation/InstructionPresenter.swift [hunk 21]
```diff
@@ -147,9 +146,16 @@ class InstructionPresenter {
...
+                                        idiom: idiom,
+                                        in: spriteRepository,
+                                        dataSource: dataSource,
+                                        onImageDownload: onImageDownload)
                     // Fall back to a generic shield if no shield image is available.
-                    ?? genericShield(text: alternativeText.text, dataSource: dataSource, cacheKey: component.cacheKey!)
+                    ?? genericShield(text: alternativeText.text,
+                                     idiom: idiom,
+                                     dataSource: dataSource,
+                                     cacheKey: component.cacheKey!)
```
[the remark this answers is not in the document]
Comment (ShanMa1991) [reply Sources/MapboxNavigation/InstructionPresenter.swift:158]: `component.cacheKey` has non-nil value for `.exitCode` and `.image`. So I think we could keep it.

File: Sources/MapboxNavigation/WayNameLabel.swift (hunk 17 above)
Comment (ShanMa1991) [reply Sources/MapboxNavigation/WayNameLabel.swift:25]: I think so, in case there's no road name update.

File: Sources/MapboxNavigation/SpriteRepository.swift (hunk 19 above)
Comment (ShanMa1991) [reply Sources/MapboxNavigation/SpriteRepository.swift:52]: Yes, the previous way to call `updateUserInterfaceIdiomStyles(styleURI: idiom:)` is to remove the previous style used by the `UIUserInterfaceIdiom`, if it's not used by other `UIUserInterfaceIdiom`. We removed the unused style cache because we used to use memory. but right now we have the URLCache with capacity limits, we could keep the old style cache incase the style change and re-use it in offline mode. So `userInterfaceIdiomStyles[idiom] = styleURI` will be used to replaced the `updateUserInterfaceIdiomStyles(styleURI: idiom:)`.
