### PR TITLE
Fix build related warnings when using Xcode 12.5

### LINKED ISSUE #3013: Fix build related warnings when using Xcode `12.5`.
**Mapbox Navigation SDK version:** `v2.0.0-beta.9`
 
While building Mapbox Navigation SDK for iOS using SPM such warnings are emitted:
```
'MapboxNavigation' /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios: warning: resource 'Localizable.strings' in target 'MapboxNavigation' is missing the default localization 'en'; the default localization is used as a fallback when no other localization matches
'MapboxNavigation' /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios: warning: resource 'Navigation.strings' in target 'MapboxNavigation' is missing the default localization 'en'; the default localization is used as a fallback when no other localization matches
'MapboxNavigation' /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios: warning: found 7 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios/Sources/TestHelper/tiles/liechtenstein/1/049/509.gph.gz
    /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios/Sources/TestHelper/li.tar
    /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios/Sources/TestHelper/GGPark-to-BernalHeights.route
    /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios/Sources/TestHelper/tiles/liechtenstein/2/000/789/878.gph.gz
    /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios/Sources/TestHelper/UnionSquare-to-GGPark.route
    /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios/Sources/TestHelper/tiles/liechtenstein/0/003/107.gph.gz
    /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios/Sources/TestHelper/turn_left.data

'MapboxNavigation' /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios: warning: found 7 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios/Tests/MapboxCoreNavigationTests/Fixtures/tunnel.json
    /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios/Tests/MapboxCoreNavigationTests/Fixtures/routeWithInstructions.json
    /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios/Tests/MapboxCoreNavigationTests/Fixtures/routeWithTunnels_9thStreetDC.json
    /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios/Tests/MapboxCoreNavigationTests/Fixtures/route.json
    /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios/Tests/MapboxCoreNavigationTests/Fixtures/tunnel.route
    /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios/Tests/MapboxCoreNavigationTests/Fixtures/dc-line.geojson
    /Users/maksimmakhun/Desktop/Mapbox/src/mapbox-navigation-ios/Tests/MapboxCoreNavigationTests/Fixtures/straight-line.json
```

In scope of this ticket unused resources which cause such warnings should be removed, localization related warnings should be fixed as well.

/cc @mapbox/navigation-ios

### PR DESCRIPTION
**Pull request by S2Ler**
### Description
- Fixes #3013.
- Please read commit messages for more info.
- I didn't check unused resources (**help** is welcomed) for the following reasons:
  It is hard to find out if the resource is used.
  - Can't run all the tests locally. 
  - We might need these test in the future.

### CODE REVIEW

File: Sources/TestHelper/NavigationPlotter.swift [hunk 1]
```diff
@@ -160,14 +160,14 @@ public class NavigationPlotter: UIView {
...
         navigationMapView = NavigationMapView(frame: bounds)
-        let padding = UIEdgeInsets(top: 50, left: 50, bottom: 50, right: 50)
+//        let padding = UIEdgeInsets(top: 50, left: 50, bottom: 50, right: 50)
         
         coordinateBounds = allBoundingCoordinates.bounds
         
-        if let coordinateBounds = coordinateBounds {
+//        if let coordinateBounds = coordinateBounds {
             // FIXME: As of Mapbox Maps `v10.0.0-beta.17` such method is no longer present.
             // navigationMapView?.mapView.cameraManager.transitionCoordinateBounds(to: coordinateBounds, edgePadding: padding, completion: nil)
```
Comment (1ec5) [inline Sources/TestHelper/NavigationPlotter.swift:169]: If I’m not mistaken, it should be possible to fit a camera to these bounds using `MapboxMap.camera(for:padding:bearing:pitch:)`, then set the camera.

File: MapboxNavigation.xcodeproj/project.pbxproj [hunk 2]
```diff
@@ -2317,12 +2328,16 @@
 			isa = PBXResourcesBuildPhase;
 			buildActionMask = 2147483647;
 			files = (
+				E27A20D02654EBED00AA935F /* li.tar in Resources */,
 				B4A78D19261FD47700FDF212 /* route-with-banner-instructions.json in Resources */,
 				B4A78D1A261FD47700FDF212 /* route-with-missing-road-classes.json in Resources */,
+				E27A20CF2654EBED00AA935F /* GGPark-to-BernalHeights.route in Resources */,
```
Comment (1ec5) [inline MapboxNavigation.xcodeproj/project.pbxproj:2334]: The only use of this test fixture appears to have been removed in #785.

File: MapboxNavigation.xcodeproj/project.pbxproj [hunk 3]
```diff
@@ -2317,12 +2328,16 @@
...
 				B4A78D1B261FD47700FDF212 /* route-with-instructions.json in Resources */,
 				B4A78D1C261FD47700FDF212 /* routeWithTunnels_9thStreetDC.json in Resources */,
 				B4A78D1D261FD47700FDF212 /* PipeFittersUnion-FourSeasonsBoston.json in Resources */,
+				E27A20D12654EBED00AA935F /* UnionSquare-to-GGPark.route in Resources */,
 				B4A78D1E261FD47700FDF212 /* route-with-straight-roundabout.json in Resources */,
+				E27A20D22654EBED00AA935F /* turn_left.data in Resources */,
```
Comment (1ec5) [inline MapboxNavigation.xcodeproj/project.pbxproj:2340]: These test fixtures were added in #1813, but I don’t see how they were ever used in this project.

File: MapboxNavigation.xcodeproj/project.pbxproj [hunk 4]
```diff
@@ -3106,7 +3118,6 @@
 		DAAE5F321EAE4C4700832871 /* Localizable.strings */ = {
 			isa = PBXVariantGroup;
 			children = (
-				DAAE5F311EAE4C4700832871 /* Base */,
```
Comment (1ec5) [inline MapboxNavigation.xcodeproj/project.pbxproj:3109]: Transifex is currently configured to expect Base localization:

https://github.com/mapbox/mapbox-navigation-ios/blob/1783c9b6e2556b41b79851522dfe943b108af2e2/.tx/config#L9

I was under the impression that Base localization is a best practice. Xcode even issued a warning for us to adopt it at one point. Is it unsupported by SPM?

Comment (S2Ler) [reply MapboxNavigation.xcodeproj/project.pbxproj:3109]: I was under the same expression, but the situation is a bit more complicated: Base internationalization is still a preferred approach, but it is designed only for .storyboard and .xib files. From the docs:
```
Base internationalization separates user-facing strings from .storyboard and .xib files. It relieves localizers of the need to modify .storyboard and .xib files in Interface Builder. Instead, an app has just one set of .storyboard and .xib files where strings are in the development language—the language that you used to create the .storyboard and .xib files. These .storyboard and .xib files are called the base internationalization. When you export localizations, the development language strings are the source that is translated into multiple languages. When you import localizations, Xcode generates language-specific strings files for each .storyboard and .xib file. The strings files don't appear in the project navigator until you import localizations or add languages.

In Xcode 5 and later, base internationalization is enabled by default. If you have an older project, enable base internationalization before continuing, as described in Enabling Base Internationalization.
```
It clearly says that base internationalization is just for .storyboard and .xib files. I tried to verify this information and created a new project. When I try to localize a xib file, Xcode allows me to select base localization and all the other supported languages I've added in settings. If I choose a string file, then Xcode doesn't show Base localization. This matches with the documentation. 

Having said above, I will:
- [ ] Verify Transifex integration and see how we can fix it. 

Thanks for letting me know about Transifex, gotta read more about it.

File: Sources/TestHelper/NavigationPlotter.swift (hunk 1 above)
Comment (S2Ler) [reply Sources/TestHelper/NavigationPlotter.swift:169]: Even though I can verify that it will work at this point, I will update the code with the suggested replacement.

File: MapboxNavigation.xcodeproj/project.pbxproj (hunk 3 above)
Comment (S2Ler) [reply MapboxNavigation.xcodeproj/project.pbxproj:2340]: Ok, removing.

File: MapboxNavigation.xcodeproj/project.pbxproj (hunk 2 above)
Comment (S2Ler) [reply MapboxNavigation.xcodeproj/project.pbxproj:2334]: Thanks, removing.

File: MapboxNavigation.xcodeproj/project.pbxproj (hunk 4 above)
Comment (1ec5) [reply MapboxNavigation.xcodeproj/project.pbxproj:3109]: We probably need to update extract_localizable.sh to put non-IB strings in en.lproj instead of Base.lproj:

https://github.com/mapbox/mapbox-navigation-ios/blob/68f671d7633d8201cd01cc7f20dccc38f43ae4e5/scripts/extract_localizable.sh#L9

File: .tx/config [hunk 5]
```diff
@@ -6,7 +6,7 @@ type = STRINGS
 
 [mapbox-navigation-ios.LocalizableStrings]
 file_filter = Sources/MapboxNavigation/Resources/<lang>.lproj/Localizable.strings
-source_file = Sources/MapboxNavigation/Resources/Base.lproj/Localizable.strings
+source_file = Sources/MapboxNavigation/Resources/en.lproj/Localizable.strings
```
Comment (1ec5) [inline .tx/config:9]: We probably need to update extract_localizable.sh to put non-IB strings in en.lproj instead of Base.lproj:

https://github.com/mapbox/mapbox-navigation-ios/blob/68f671d7633d8201cd01cc7f20dccc38f43ae4e5/scripts/extract_localizable.sh#L9

**Review by 1ec5 — APPROVED** [review]
Looks good apart from updating one of our localization scripts (which isn’t urgent but best to get out of the way before we forget).

File: .tx/config (hunk 5 above)
Comment (S2Ler) [reply .tx/config:9]: Fixed

**Comment by S2Ler** [comment]
> Looks good apart from updating one of our localization scripts (which isn’t urgent but best to get out of the way before we forget).

Fixed it in https://github.com/mapbox/mapbox-navigation-ios/pull/3017/commits/7978d29bce9f9a5fb1534fc6e9ae85250d2c42b0. It was broken even without my changes.
